module.exports = {
  "site": "https://foreignassistance.gov",
  "urls": [
    "/cd/zimbabwe/2023/disbursements/2",
    "/cd/united%20states/",
    "/cd/el%20salvador/",
    "/cd/jordan/2025/obligations/0",
    "/cd/bosnia%20and%20herzegovina/",
    "/cd/indonesia/",
    "/cd/egypt/2024/obligations/0",
    "/cd/antigua%20and%20barbuda/",
    "/cd/korea%20democratic%20republic/",
    "/cd/serbia/",
    "/cd/south%20sudan/",
    "/cd/colombia/2025/obligations/0",
    "/cd/israel/2021/obligations/0",
    "/cd/israel/2023/disbursements/0",
    "/cd/united%20arab%20emirates/",
    "/cd/zambia/",
    "/cd/korea%20republic/",
    "/cd/panama/",
    "/cd/zimbabwe/2015/disbursements/0",
    "/cd/ireland/",
    "/cd/qatar/",
    "/cd/botswana/",
    "/cd/cameroon/",
    "/cd/georgia/",
    "/cd/georgia/2020/obligations/0",
    "/cd/kosovo/",
    "/cd/belize/",
    "/cd/ghana/",
    "/cd/canada/2025/obligations/0",
    "/cd/ethiopia/2025/obligations/0",
    "/cd/sudan/2025/obligations/0",
    "/cd/brazil/2019/obligations/0",
    "/cd/china%20(p.r.c.)/2008/obligations/1",
    "/cd/egypt/2023/obligations/0",
    "/cd/italy/",
    "/cd/morocco/",
    "/cd/peru/",
    "/cd/sudan/2024/obligations/0",
    "/cd/brazil/2022/obligations/0",
    "/cd/brazil/2025/obligations/0",
    "/cd/mongolia/",
    "/cd/afghanistan/2025/disbursements/0",
    "/cd/burkina%20faso/",
    "/cd/finland/",
    "/cd/taiwan/",
    "/cd/el%20salvador/current/obligations/1",
    "/cd/somalia/2023/obligations/0",
    "/cd/bulgaria/",
    "/cd/jordan/2023/obligations/0",
    "/cd/lebanon/current/obligations/1"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://foreignassistance.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}