module.exports = {
  "site": "https://www.usagm.gov",
  "urls": [
    "/burke_candidate/han-dongfang/",
    "/burke_candidate/mandarin-apr-and-digital-teams/",
    "/2024/09/30/marti-condemns-the-arrest-of-oscar-elias-biscet/",
    "/news-and-information/threats-to-press/mohammad-ilyas-dayee/",
    "/work-with-us/contract-opportunities/our-procurement-authority/",
    "/who-we-are/management-team/paul-kollmer-dorsey/",
    "/burke_candidate/robyn-kriel/",
    "/burke_candidate/sailab-mahsud/",
    "/our-work/strategy-and-results/strategic-priorities/research-reports/tsi/",
    "/news-and-information/press-releases/usagm/",
    "/2024/06/28/voa-news-launches-new-coverage-initiatives-for-2024-us-presidential-election/",
    "/2024/06/03/voa-wins-five-chesapeake-ap-awards-in-multiple-categories-3/",
    "/awards/burke-awards-archive/2003-winners/",
    "/2024/07/15/ai-and-its-role-in-journalism/",
    "/burke_candidate/afghan-crisis-response-team/",
    "/2021/12/16/cote-divoire-factchecking-and-fighting-fake-news/",
    "/our-work/strategy-and-results/strategic-priorities/research-reports/embarking-on-reform-of-the-office-of-cuba-broadcasting/",
    "/our-work/strategy-and-results/strategic-priorities/research-reports/fair-act/",
    "/burke_candidate/gaza-team/",
    "/2025/02/28/haiti-mentoring-and-team-building/",
    "/news-and-information/threats-to-press/ihar-losik/",
    "/burke_candidate/karen-caballero/",
    "/burke_candidate/lobsang-chophel/",
    "/2024/04/17/mbn-podcast-marking-the-last-days-in-kojo-wins-gold/",
    "/2024/05/24/mbn-wins-three-telly-awards/",
    "/burke_candidate/maryana-torocheshnikova/",
    "/who-we-are/board/michelle-s-giuda/",
    "/news-and-information/threats-to-press/mohammed-bdaiwi-owaid-al-shammari/",
    "/2018/07/16/navbahor-imamova/",
    "/2018/12/07/not-in-our-name-counter-extremism-project-lauded-in-kazakhstan/",
    "/2020/04/17/radio-free-asia-hosts-secure-mirror-websites-for-asian-chinese-audiences/",
    "/tag/radio-sawa/",
    "/burke_candidate/staff-and-journalists-of-radio-azadi/",
    "/2024/03/19/understanding-ai-and-the-future-of-journalism/",
    "/news-and-information/threats-to-press/vladyslav-yesypenko/",
    "/2024/07/22/american-rfe-rl-reporter-alsu-kurmasheva-tried-convicted-in-russian-court/",
    "/our-work/strategy-and-results/strategic-priorities/research-reports/federal-employee-viewpoint-surveys/",
    "/work-with-us/contract-opportunities/how-to-do-business-with-us/",
    "/burke_candidate/ibrahim-ahmed-hausa-service/",
    "/burke_candidate/joe-cardona/",
    "/burke_candidate/john-miller/",
    "/2023/11/02/marti-launches-groundbreaking-new-fact-checking-service-to-counter-propaganda-in-cuba/",
    "/who-we-are/management-team/michael-pack/",
    "/burke_candidate/moe-thu-aung/",
    "/apps/news-apps-ios-android/",
    "/news-and-information/threats-to-press/nika-novak/",
    "/2023/12/21/office-of-cuba-broadcasting-partners-with-odesa-center-for-disinformation-studies-to-counter-russian-propaganda/",
    "/news-and-information/press-releases/rfa/",
    "/burke_candidate/radio-ozodi/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.usagm.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}