module.exports = {
  "site": "https://www.usagm.gov",
  "urls": [
    "/burke_candidate/tseten-dolkar/",
    "/burke_candidate/vuthy-khin-huot/",
    "/who-we-are/oversight/legislation/international-broadcast-act-amendment/",
    "/2017/11/20/malawi-investigative-journalism/",
    "/who-we-are/ceo-and-entity-leadership/sylvia-rosabal/",
    "/2024/11/01/usagm-ceo-amanda-bennett-reflects-ahead-of-international-day-to-end-impunity-for-crimes-against-journalists/",
    "/burke_candidate/alvaro-alba/",
    "/burke_candidate/asia-fact-check-lab/",
    "/news-and-information/threats-to-press/nguyen-vu-binh/",
    "/news-and-information/threats-to-press/pham-chi-dung/",
    "/2024/03/28/rfa-burmese-imprisoned-filmmaker-win-gracie-award-for-environmental-story/",
    "/news-and-information/threats-to-press/sithu-aung-myint/",
    "/2024/10/31/mbns-wins-gold-silver-and-listeners-choice-at-the-signal-awards/",
    "/news-and-information/threats-to-press/nguyen-tuong-thuy/",
    "/burke_candidate/oscar-elias-biscet/",
    "/2023/08/17/rfa-brand-%E6%AD%AA%E8%84%91-whynot-wins-online-journalism-award/",
    "/burke_candidate/ricardo-quintana/",
    "/burke_candidate/salih-mohammed-salih/",
    "/burke_candidate/vanessa-ruiz/",
    "/who-we-are/management-team/yolanda-lopez/",
    "/burke_candidate/aslanbek-dadyev/",
    "/burke_candidate/ayesha-tanzeem/",
    "/2023/06/21/ecuador-best-practices-for-covering-the-amazon-and-climate-change/",
    "/2017/09/01/hai-do/",
    "/2021/06/17/investigative-series-on-xinjiang-detention-camps-wins-pulitzer-prize-in-international-reporting/",
    "/burke_candidate/nat-kretchun/",
    "/news-and-information/press-releases/otf/",
    "/2020/01/09/rfa-publishes-rebel-pepper-e-book-with-hong-kong-uyghur-focus/",
    "/burke_candidate/ukrainian-service/",
    "/news-and-information/threats-to-press/abdulrachmann-fatalibey/",
    "/burke_candidate/alisha-ryu/",
    "/news-and-information/threats-to-press/alisher-saipov/",
    "/burke_candidate/ashyrkuli-bayriev/",
    "/our-work/strategy-and-results/strategic-priorities/strategic-plan-faq/",
    "/2017/09/03/desalenge-des-mekonnen/",
    "/burke_candidate/rferls-kyiv-bureau/",
    "/burke_candidate/miao-yu-shih-wei-chou-bo-xu-shaorong-wu-mandarin-service/",
    "/our-work/transmissions-and-broadcasting/new-media/",
    "/news-and-information/threats-to-press/nguyen-lan-thang/",
    "/2018/07/17/paris-huang/",
    "/2024/08/19/rfa-special-report-on-myanmar-crisis-wins-national-murrow-award/",
    "/2024/09/02/reimagined-middle-east-broadcasting-networks/",
    "/work-with-us/content-requests/voa/",
    "/burke_candidate/shohret-hoshur-uyghur-service/",
    "/our-work/transmissions-and-broadcasting/television-and-satellite/",
    "/burke_candidate/adrian-criscaut/",
    "/burke_candidate/anne-look/",
    "/news-and-information/press-releases/bbg/",
    "/2024/09/09/ethical-use-of-artificial-intelligence-in-journalism/",
    "/burke_candidate/fahem-omer-zana-omar/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.usagm.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}