module.exports = {
  "site": "https://www.usagm.gov",
  "urls": [
    "/our-work/strategy-and-results/",
    "/2023/04/21/youre-invited-22nd-david-burke-distinguished-journalism-awards/",
    "/news-and-information/events/",
    "/2025/02/12/trump-administration-secures-release-of-radio-liberty-journalist-andrey-kuznechyk-from-detention-in-belarus/",
    "/our-work/strategy-and-results/strategic-priorities/budget-submissions/",
    "/office-internet-freedom/",
    "/our-work/media-development/",
    "/2023/09/05/egyptian-trendsetters-bring-their-popular-content-exclusively-to-el-saha/",
    "/vulnerability-disclosure-policy/",
    "/2025/01/17/usagm-networks-reached-record-global-audience-in-fy-2024-according-to-new-report/",
    "/foia-reports/",
    "/work-with-us/equal-employment/",
    "/who-we-are/management-team/former-ceos/",
    "/category/event/burke-awards/",
    "/2016/01/12/radio-free-asia-releases-english-e-book-on-north-koreas-prison-camps/",
    "/who-we-are/ceo-and-entity-leadership/jeffrey-gedmin/",
    "/2021/12/16/20th-annual-david-burke-distinguished-journalism-awards-ceremony/",
    "/artificial-intelligence/",
    "/who-we-are/oversight/legislation/standards-principles/",
    "/2018/09/21/radio-free-asia-launches-documentary-on-former-uyghur-detainees/",
    "/work-with-us/content-requests/",
    "/who-we-are/the-ceo/amanda-bennett/",
    "/job-listings/",
    "/who-we-are/oversight/legislation/voa-charter/",
    "/who-we-are/management-team/amanda-bennett/",
    "/2013/05/16/board-members-discuss-media-freedom-and-other-ongoing-bbg-priorities-and-hold-a-town-hall-meeting-on-the-budget/",
    "/2025/02/14/marc-thiessen-and-ilan-berman-join-rfe-rl-board-of-directors/",
    "/burke_candidate/mohamed-moawad/",
    "/who-we-are/ceo-and-entity-leadership/bay-fang/",
    "/2025/01/21/celia-mendoza-2/",
    "/2022/12/09/21st-annual-david-burke-awards-ceremony/",
    "/2024/08/26/voa-launches-fulani-language-programming/",
    "/accessibility/",
    "/2024/08/01/american-rfe-rl-reporter-alsu-kurmasheva-released-from-russian-custody/",
    "/2012/09/19/dana-perino-to-leave-the-broadcasting-board-of-governors/",
    "/2024/01/31/haiti-video-journalism-ethics-and-marketing/",
    "/burke_candidate/uyhgur-service/",
    "/awards/burke-awards-archive/",
    "/2024/04/18/otf-increases-funding-for-circumvention-tools-to-support-46-million-monthly-users/",
    "/our-work/transmissions-and-broadcasting/radio/",
    "/2019/08/08/countering-chinese-censorship/",
    "/who-we-are/board/d-jeffrey-hirschberg/",
    "/our-work/strategy-and-results/strategic-priorities/annual-reports/",
    "/2024/03/11/usagm-budget-request-rises-to-meet-growing-global-challenges-in-fy-2025/",
    "/who-we-are/ceo-and-entity-leadership/laura-cunningham/",
    "/who-we-are/board/steven-j-simmons/",
    "/news-and-information/threats-to-press/truong-duy-nhat/",
    "/who-we-are/board/former-governors/",
    "/who-we-are/board/joaquin-f-blaya/",
    "/2024/10/24/mbn-names-jeff-gedmin-president-ceo/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.usagm.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}