module.exports = {
  "site": "https://foreignassistance.gov",
  "urls": [
    "/",
    "/cd",
    "/data",
    "/api-docs",
    "/cd/israel/",
    "/cd/afghanistan/",
    "/cd/zimbabwe/current/obligations/1",
    "/aid-trends",
    "/about",
    "/agencies",
    "/reports",
    "/cd/canada/",
    "/cd/israel/2024/obligations/0",
    "/cd/egypt/",
    "/cd/israel/2025/obligations/0",
    "/cd/ukraine/",
    "/cd/mexico/",
    "/cd/albania/",
    "/cd/pakistan/",
    "/cd/india/",
    "/cd/jordan/",
    "/cd/algeria/",
    "/cd/brazil/",
    "/cd/china%20(p.r.c.)/",
    "/cd/south%20africa/",
    "/cd/australia/",
    "/cd/colombia/",
    "/cd/afghanistan/2025/obligations/0",
    "/cd/ethiopia/",
    "/cd/angola/",
    "/cd/sudan/",
    "/cd/zimbabwe/2015/obligations/0",
    "/cd/israel/2023/obligations/0",
    "/cd/argentina/",
    "/cd/bangladesh/",
    "/cd/zimbabwe/2018/disbursements/2",
    "/cd/zimbabwe/2010/disbursements/2",
    "/cd/philippines/",
    "/cd/iraq/",
    "/cd/haiti/",
    "/cd/france/",
    "/cd/zimbabwe/2015/disbursements/2",
    "/cd/afghanistan/2024/obligations/0",
    "/cd/zimbabwe/2022/disbursements/2",
    "/cd/zimbabwe/2021/disbursements/2",
    "/cd/zimbabwe/",
    "/donor",
    "/cd/somalia/",
    "/cd/zimbabwe/2013/disbursements/2",
    "/cd/turkey/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://foreignassistance.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}