module.exports = {
  "site": "https://foreignassistance.gov",
  "urls": [
    "/cd/germany/",
    "/cd/united%20kingdom/",
    "/cd/russia/",
    "/cd/uganda/",
    "/cd/venezuela/",
    "/cd/west-bank-gaza/",
    "/cd/cambodia/",
    "/cd/nigeria/",
    "/cd/zimbabwe/2024/disbursements/1",
    "/cd/honduras/",
    "/cd/ukraine/2025/obligations/0",
    "/cd/cuba/",
    "/cd/brazil/2024/obligations/1",
    "/cd/iran/",
    "/cd/israel/2022/obligations/0",
    "/cd/ukraine/2024/obligations/0",
    "/cd/austria/",
    "/cd/belgium/",
    "/cd/canada/2023/obligations/0",
    "/cd/yemen/",
    "/cd/armenia/",
    "/cd/israel/2025/disbursements/0",
    "/cd/greece/",
    "/cd/afghanistan/2023/obligations/0",
    "/cd/syria/",
    "/cd/azerbaijan/",
    "/cd/afghanistan",
    "/cd/bahrain/",
    "/cd/congo%20(kinshasa)/",
    "/cd/egypt/2025/obligations/0",
    "/cd/saudi%20arabia/",
    "/cd/ukraine/2023/obligations/0",
    "/cd/guatemala/",
    "/cd/pakistan/2025/obligations/0",
    "/cd/bahamas/",
    "/cd/japan/",
    "/cd/tunisia/",
    "/cd/belarus/",
    "/cd/israel/2024/disbursements/0",
    "/cd/kenya/",
    "/cd/zimbabwe",
    "/cd/chad/current/obligations/1",
    "/cd/denmark/",
    "/cd/lebanon/",
    "/cd/canada/2022/obligations/0",
    "/cd/liberia/",
    "/cd/mexico/2025/obligations/0",
    "/cd/vietnam/",
    "/cd/zimbabwe/2023/disbursements/0",
    "/cd/canada/2024/obligations/0"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://foreignassistance.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}