module.exports = {
  "site": "https://www.usagm.gov",
  "urls": [
    "/",
    "/who-we-are/oversight/legislation/smith-mundt-faqs/",
    "/2025/03/15/u-s-agency-for-global-media-complies-with-presidential-executive-order-to-reduce-the-federal-bureaucracy/",
    "/networks/mbn/",
    "/who-we-are/oversight/legislation/smith-mundt/",
    "/work-with-us/careers/",
    "/who-we-are/ceo-and-entity-leadership/",
    "/contact-us/",
    "/news-and-information/press-releases/",
    "/networks/voa/",
    "/who-we-are/",
    "/who-we-are/the-international-broadcasting-advisory-board/",
    "/who-we-are/organizational-chart/",
    "/who-we-are/mission/",
    "/work-with-us/usagm-intern-and-student-programs/",
    "/2024/09/27/u-s-agency-for-global-media-awards-lease-securing-voice-of-america-move-to-a-modern-new-downtown-d-c-headquarters/",
    "/networks/ocb/",
    "/news-and-information/",
    "/who-we-are/history/",
    "/awards/",
    "/networks/rferl/",
    "/work-with-us/contract-opportunities/",
    "/news-and-information/threats-to-press/georgi-markov/",
    "/networks/rfa/",
    "/networks/",
    "/our-work/strategy-and-results/strategic-priorities/budget-and-financial-reports/",
    "/rumors-myths-untruths/",
    "/who-we-are/ceo-and-entity-leadership/michael-abramowitz/",
    "/networks/otf/",
    "/foia/",
    "/our-work/",
    "/our-work/strategy-and-results/strategic-priorities/performance-plans-and-reports/",
    "/our-work/strategy-and-results/strategic-priorities/research-reports/",
    "/news-and-information/threats-to-press/",
    "/our-work/transmissions-and-broadcasting/",
    "/who-we-are/oversight/legislation/international-broadcasting-act/",
    "/our-work/strategy-and-results/strategic-priorities/research-reports/open-government/",
    "/who-we-are/oversight/",
    "/who-we-are/board/",
    "/employee-resources-and-guidelines/",
    "/work-with-us/contract-opportunities/what-we-buy-and-current-opportunities/",
    "/work-with-us/become-an-affiliate/",
    "/work-with-us/",
    "/who-we-are/firewall/",
    "/news-and-information/press-room/",
    "/privacy-policy/",
    "/burke_candidate/rahman-bunairee/",
    "/who-we-are/oversight/legislation/",
    "/who-we-are/oversight/legislation/smith-mundt-modernization/",
    "/2024/06/24/michael-abramowitz-takes-the-helm-as-new-voice-of-america-director/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.usagm.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}