module.exports = {
  "site": "https://fs.usda.gov",
  "urls": [
  "/r02/psicc/recreation",
  "/r02/arp/recreation",
  "/",
  "/r03/coconino/recreation",
  "/r05/inyo/recreation",
  "/r02/whiteriver/recreation",
  "/r06/deschutes/recreation",
  "/r08/northcarolina/recreation",
  "/r06/willamette/recreation",
  "/r06/mthood/recreation",
  "/r06/okanogan-wenatchee/recreation",
  "/r06/giffordpinchot/recreation",
  "/r04/uinta-wasatch-cache/recreation",
  "/r02/gmug/recreation",
  "/working-with-us/careers",
  "/r06/passes",
  "/r09/whitemountain/recreation",
  "/r06",
  "/r06/siuslaw/recreation",
  "/r08/florida/recreation",
  "/r05/stanislaus/recreation",
  "/r06/mbs/recreation",
  "/r08/chattahoochee-oconee/recreation",
  "/r05/sanbernardino/recreation",
  "/r03/tonto/recreation",
  "/r05/tahoe/recreation",
  "/r04/caribou-targhee/recreation",
  "/visit/maps",
  "/r05/sequoia/recreation",
  "/r05/eldorado/recreation",
  "/r08/elyunque",
  "/r08/danielboone/recreation",
  "/r04/bridger-teton/recreation",
  "/r03/apache-sitgreaves/recreation",
  "/r04/sawtooth/recreation",
  "/r09/huron-manistee/recreation",
  "/r02/mbrtb/recreation",
  "/r08/gwj/recreation",
  "/r06/olympic/recreation",
  "/r04/boise/recreation",
  "/r05/sierra/recreation",
  "/r03/coconino",
  "/r06/umpqua/recreation",
  "/r06/okanogan-wenatchee",
  "/r09/hiawatha/recreation",
  "/r02/sanjuan/recreation",
  "/r05/inyo",
  "/r09/shawnee/recreation",
  "/r05/laketahoebasin/recreation",
  "/r02/blackhills/recreation",
  "/r09/superior/recreation",
  "/r03/santafe/recreation",
  "/r06/columbiarivergorge/recreation",
  "/r03/coronado/recreation",
  "/r10/chugach/recreation",
  "/r02/riogrande/recreation",
  "/r05/lospadres/recreation",
  "/r04/humboldt-toiyabe/recreation",
  "/r03/tonto",
  "/r02/whiteriver/recreation/camping-cabins",
  "/r05/angeles",
  "/r06/mbs",
  "/r06/rogue-siskiyou/recreation",
  "/r05",
  "/r04/uinta-wasatch-cache",
  "/visit/passes-permits",
  "/r02/psicc",
  "/r06/mthood",
  "/r08/northcarolina",
  "/r01/beaverhead-deerlodge/recreation",
  "/r03/carson/recreation",
  "/r06/columbiarivergorge",
  "/r05/cleveland/recreation",
  "/r09/monongahela/recreation",
  "/r09/chequamegon-nicolet/recreation",
  "/r05/plumas/recreation",
  "/r01/idahopanhandle/recreation",
  "/r06/willamette",
  "/r05/lassen/recreation"
],
  "scanner": {
    "crawler": false,
    "sitemap": false,
    "robotsTxt": false
  },
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-dev-shm-usage"
    ]
  }
}