module.exports = {
  "site": "https://www.fs.usda.gov",
  "urls": [
    "/",
    "/r03/coconino/recreation",
    "/working-with-us/careers",
    "/r08/northcarolina/recreation",
    "/r02/arp/recreation",
    "/r02/psicc/recreation",
    "/r05/inyo/recreation",
    "/visit/maps",
    "/r02/whiteriver/recreation",
    "/r06/passes",
    "/r09/whitemountain/recreation",
    "/r06/deschutes/recreation",
    "/r06/siuslaw/recreation",
    "/r06/mthood/recreation",
    "/r06/willamette/recreation",
    "/r04/uinta-wasatch-cache/recreation",
    "/r06/giffordpinchot/recreation",
    "/r03/coconino",
    "/r03/tonto/recreation",
    "/r02/gmug/recreation",
    "/r06/okanogan-wenatchee/recreation",
    "/r01/custergallatin/recreation",
    "/r05/angeles/recreation",
    "/r08/chattahoochee-oconee/recreation",
    "/r08/gwj/recreation",
    "/r05/sanbernardino/recreation",
    "/r06/mbs/recreation",
    "/r05/sequoia/recreation",
    "/r08/florida/recreation",
    "/r06/okanogan-wenatchee",
    "/r04/bridger-teton/recreation",
    "/r08/elyunque",
    "/search",
    "/r03/coronado/recreation",
    "/wildflowers/pollinators/pollinator-of-the-month/hummingbird_moth.shtml",
    "/r09/hiawatha/recreation",
    "/r02/arp",
    "/r06/umpqua/recreation",
    "/r04/caribou-targhee/recreation",
    "/r05/eldorado/recreation",
    "/r06",
    "/r05/stanislaus/recreation",
    "/r05",
    "/r09/huron-manistee/recreation",
    "/r05/tahoe/recreation",
    "/r05/inyo",
    "/r04/sawtooth/recreation",
    "/r08/danielboone/recreation",
    "/r04/humboldt-toiyabe/recreation",
    "/r08/cherokee/recreation",
    "/r03/apache-sitgreaves/recreation",
    "/r09/shawnee/recreation",
    "/r09/superior/recreation",
    "/r06/giffordpinchot",
    "/visit/passes-permits",
    "/r06/willamette/permits/central-cascades-wilderness-permits",
    "/r08/northcarolina"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.fs.usda.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 114,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}