module.exports = {
  "site": "https://www.abmc.gov",
  "urls": [
    "/video/meuse-argonne-american-cemetery/",
    "/plan/plan-your-visit-to-cambridge-american-cemetery/",
    "/cemeteries-memorials/operational-status/",
    "/news-events/news/parking-changes-set-at-normandy-to-improve-traffic-flow/",
    "/video/lorraine-american-cemetery/",
    "/news-events/news/new-inscription-honors-merchant-mariners-lost-in-wwii/",
    "/cemeteries-memorials/about-st-mihiel-american-cemetery/",
    "/news-events/news/american-battle-monuments-commission-offers-free-online-training-for-commercial-tour-guides/",
    "/cemeteries-memorials/about-suresnes-american-cemetery/",
    "/cemeteries-memorials/about-oise-aisne-american-cemetery/",
    "/video/japan-surrenders-1945/",
    "/cemeteries-memorials/about-somme-american-cemetery/",
    "/news-events/news/new-normandy-american-cemetery-visitor-center-opens/",
    "/video/brittany-american-cemetery/",
    "/education/teaching-aid/abmc-commemorative-sites-for-commercial-guides/",
    "/cemeteries-memorials/about-corozal-american-cemetery/",
    "/news-events/news/interactive-timeline-and-map-allows-you-explore-history-world-war-i/",
    "/plan/plan-your-visit-to-luxembourg-american-cemetery/",
    "/news-events/news/christmas-eve-1944-brief-moment-peace-battlefield/",
    "/cemeteries-memorials/about-clark-veterans-cemetery/",
    "/d-day80/",
    "/cemeteries-memorials/vintage-posters/",
    "/multimedia/",
    "/news-events/news/5-things-you-may-not-know-about-luxembourg-american-cemetery/",
    "/news-events/news/world-war-ii-ssgt-salvador-lara-receives-posthumous-medal-honor-nearly-70-years/",
    "/cemeteries-memorials/about-guadalcanal-memorial/",
    "/cemeteries-memorials/about-honolulu-memorial/",
    "/video/epinal-american-cemetery/",
    "/plan/plan-your-visit-to-manila-american-cemetery/",
    "/cemeteries-memorials/about-brookwood-american-cemetery/",
    "/cemeteries-memorials/about-midway-monument/",
    "/video/flanders-field-american-cemetery/",
    "/cemeteries-memorials/about-montfaucon-american-monument/",
    "/about-us/reports-policy/accessibility/",
    "/cemeteries-memorials/about-west-coast-memorial/",
    "/profiles/",
    "/about-us/our-services/flowers-our-sites/",
    "/cemeteries-memorials/about-cabanatuan-american-memorial/",
    "/news-events/news/five-things-you-may-not-know-about-netherlands-american-cemetery/",
    "/plan/plan-your-visit-to-florence-american-cemetery/",
    "/video/rhone-american-cemetery/",
    "/cemeteries-memorials/about-mexico-city-national-cemetery/",
    "/plan/plan-your-visit-to-henri-chapelle-american-cemetery/",
    "/cemeteries-memorials/about-utah-beach-american-memorial/",
    "/about-us/",
    "/news-events/news/caring-sick-and-wounded-establishing-first-us-army-medical-units-france-and-england/",
    "/profile/sergeant-teofilo-yldefonzo/",
    "/news-events/",
    "/news-events/news/five-things-discover-normandy-american-cemetery/",
    "/plan/plan-your-visit-to-sicily-rome-american-cemetery/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.abmc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}