module.exports = {
  "site": "https://www.abmc.gov",
  "urls": [
    "/cemeteries-memorials/about-normandy-american-cemetery/",
    "/",
    "/cemeteries-memorials/",
    "/cemeteries-memorials/about-netherlands-american-cemetery/",
    "/plan/plan-your-visit-to-normandy-american-cemetery/",
    "/video/normandy-american-cemetery/",
    "/cemeteries-memorials/about-pointe-du-hoc-ranger-monument/",
    "/cemeteries-memorials/about-cambridge-american-cemetery/",
    "/cemeteries-memorials/about-luxembourg-american-cemetery/",
    "/interactive/ww2/",
    "/cemeteries-memorials/about-florence-american-cemetery/",
    "/cemeteries-memorials/about-manila-american-cemetery/",
    "/cemeteries-memorials/about-lorraine-american-cemetery/",
    "/cemeteries-memorials/about-henri-chapelle-american-cemetery/",
    "/about-us/faqs/",
    "/cemeteries-memorials/about-sicily-rome-american-cemetery/",
    "/cemeteries-memorials/about-brittany-american-cemetery/",
    "/cemeteries-memorials/cemeteries-memorials-map/",
    "/cemeteries-memorials/virtual-360s/",
    "/video/cambridge-american-cemetery/",
    "/cemeteries-memorials/about-meuse-argonne-american-cemetery/",
    "/about-us/contact-us/",
    "/cemeteries-memorials/about-ardennes-american-cemetery/",
    "/news-events/news/general-george-s-patton-jr-buried-luxembourg-american-cemetery/",
    "/video/this-day-in-history-november-11-1918-world-war-i-ends/",
    "/about-us/the-commission/",
    "/event/memorial-day-2025/",
    "/video/manila-american-cemetery/",
    "/about-us/employment/",
    "/cemeteries-memorials/about-aisne-marne-american-cemetery/",
    "/video/luxembourg-american-cemetery/",
    "/video/netherlands-american-cemetery/",
    "/video/henri-chapelle-american-cemetery/",
    "/cemeteries-memorials/about-east-coast-memorial/",
    "/plan/plan-your-visit-to-pointe-du-hoc-ranger-monument/",
    "/cemeteries-memorials/about-epinal-american-cemetery/",
    "/news-events/news/",
    "/about-us/our-services/",
    "/plan/plan-your-visit-to-netherlands-american-cemetery/",
    "/cemeteries-memorials/about-belleau-wood/",
    "/cemeteries-memorials/about-chateau-thierry-monument/",
    "/education/",
    "/event/",
    "/cemeteries-memorials/about-montsec-american-monument/",
    "/cemeteries-memorials/about-rhone-american-cemetery/",
    "/cemeteries-memorials/about-flanders-field-american-cemetery/",
    "/news-events/news/harlem-hellfighters-most-storied-african-american-combat-unit-world-war-i/",
    "/about-us/history/",
    "/printing-tips/",
    "/cemeteries-memorials/about-north-africa-american-cemetery/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.abmc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}