module.exports = {
  "site": "https://www.abmc.gov",
  "urls": [
    "/plan/plan-your-visit-to-belleau-wood/",
    "/news-events/news/5-things-you-may-not-know-about-clark-veterans-cemetery/",
    "/video/today-in-history-may-8-1945-the-war-ends-in-europe/",
    "/video/florence-american-cemetery/",
    "/about-us/reports-policy/budget-and-performance/",
    "/plan/plan-your-visit-to-lorraine-american-cemetery/",
    "/news-events/news/cemeteries-add-rosettes-for-july-service-member-id-announcements/",
    "/video/honolulu-memorial/",
    "/news-events/news/5-things-you-may-not-know-about-manila-american-cemetery/",
    "/about-us/reports-policy/film-permits-copyright-information/",
    "/about-us/contracting-rfp/",
    "/news-events/news/why-would-anyone-jump-out-perfectly-good-airplane-part-2-509th-parachute-infantry/",
    "/cemeteries-memorials/about-sommepy-american-monument/",
    "/news-events/news/about-inscriptions-new-normandy-visitors-center/",
    "/news-events/news/remembering-four-chaplains-75th-anniversary-their-death/",
    "/news-events/news/abmc-unveils-unique-vintage-works-art-its-cemeteries-and-iconic-monuments/",
    "/news-events/news/remembering-iwo-jima-80-years-later/",
    "/news-events/news/five-things-you-may-not-know-about-cambridge-american-cemetery/",
    "/video/sicily-rome-american-cemetery/",
    "/education/teaching-aid/teaching-and-mapping-geography-meuse-argonne-offensive/where-why-there/",
    "/news-events/news/battle-midway-through-eyes-those-who-were-there/",
    "/history/discover-the-history-of-pointe-du-hoc-ranger-monument/",
    "/news-events/news/eagle-squadrons-wwii-american-volunteers-fly-royal-air-force/",
    "/cemeteries-memorials/about-saipan-memorial/",
    "/news-events/news/remembering-operation-torch-allied-forces-land-north-africa-during-world-war-ii/",
    "/cemeteries-memorials/about-bellicourt-american-monument/",
    "/video/brookwood-american-cemetery/",
    "/event/netherlands-american-cemetery-special-event/",
    "/cemeteries-memorials/about-naval-monument-at-brest/",
    "/video/ardennes-american-cemetery/",
    "/news-events/news/new-us-ambassador-to-france-visits-suresnes-american-cemetery/",
    "/about-us/reports-policy/annual-reports/",
    "/cemeteries-memorials/about-audenarde-american-monument/",
    "/news-events/news/february-2025-marks-80-years-battle-manila/",
    "/news-events/news/as-world-war-ii-ends-in-europe-abmcs-mission-is-renewed/",
    "/plan/plan-your-visit-to-meuse-argonne-american-cemetery/",
    "/news-events/news/last-american-killed-action-europe-during-world-war-ii/",
    "/plan/plan-your-visit-to-epinal-american-cemetery/",
    "/news-events/news/abmc-hosts-83rd-anniversary-of-battle-of-guadalcanal/",
    "/cemeteries-memorials/about-kemmel-american-monument/",
    "/cemeteries-memorials/about-santiago-surrender-tree/",
    "/news-events/news/chateau-thierry-monument-visitor-center-closed-august-22-23-and-24/",
    "/news-events/news/rhone-american-cemetery-honors-world-war-ii-fallen-on-operation-dragoon-anniversary/",
    "/video/east-coast-and-west-coast-memorials/",
    "/video/historic-coverage-d-day-invasion/",
    "/cemeteries-memorials/about-korean-war-monument-at-busan/",
    "/news-events/news/americans-great-britain-world-war-ii-online-interactive-released/",
    "/history/discover-the-history-of-netherlands-american-cemetery/",
    "/news-events/news/philippine-site-staff-share-mission-at-history-convention/",
    "/plan/plan-your-visit-to-brittany-american-cemetery/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.abmc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}