module.exports = {
  "site": "https://www.usccr.gov",
  "urls": [
    "/reports/historical-publications",
    "/news/advisory-committees-news",
    "/advisory-committees/ohio",
    "/reports/no-fear-act",
    "/news/2025/statement-chair-rochelle-m-garza-national-disability-independence-day",
    "/news/2025/us-commission-civil-rights-approves-report-teacher-shortages-affecting-students",
    "/advisory-committees/tennessee",
    "/reports/budget-and-performance",
    "/reports/2020/subminimum-wages-impacts-civil-rights-people-disabilities",
    "/news/2025/us-commission-civil-rights-appoints-members-tennessee-and-wisconsin-state-advisory",
    "/reports/2025/examining-access-adequate-healthcare-within-northern-mariana-islands-justice-system",
    "/about/martin-castro",
    "/meetings/2025/08-19-ohio-advisory-committee-announces-study-antisemitism-ohio-panel-iii",
    "/news/2025/us-commission-civil-rights-releases-report-enforcing-religious-freedom-prisons",
    "/meetings/2025/09-03-colorado-advisory-committee-virtual-panel-examining-allegations-antisemitism",
    "/advisory-committees/florida",
    "/reports/2024/accessing-services-students-disabilities-dc-public-schools",
    "/about/victoria-nourse",
    "/es/contact/complaints",
    "/advisory-committees/texas",
    "/reports/2024/rising-use-artificial-intelligence-k-12-education",
    "/accessibility",
    "/reports/2021/racial-disparities-maternal-health",
    "/about/acquisitions",
    "/reports/2025/examining-implementation-rylans-law-and-disparate-impact-north-carolina",
    "/reports/historical-publications/catalog",
    "/advisory-committees/oregon",
    "/meetings",
    "/about/karen-narasaki",
    "/news/2025/commonwealth-northern-mariana-islands-cnmi-advisory-committee-releases-report-access",
    "/reports/2024/right-counsel-arkansas",
    "/reports/2024/federal-efforts-examining-racial-and-ethnic-disparities-among-victims-violent-crime",
    "/about/jennifer-braceras",
    "/advisory-committees/puerto-rico",
    "/reports/2024/insular-cases-and-doctrine-unincorporated-territory-and-its-effects-civil-rights",
    "/about/norma-cantu",
    "/meetings/2025/07-18-commission-business-meeting",
    "/advisory-committees/maryland",
    "/about/patricia-timmons-goodson",
    "/privacy-policy",
    "/reports/2018/broken-promises-continuing-federal-funding-shortfall-native-americans",
    "/reports/FOIA",
    "/meetings/2024/11-15-federal-response-teacher-shortage-impacts-students-disabilities",
    "/reports/2025/civil-rights-and-education-funding-mississippi",
    "/reports/2022/civil-rights-and-protections-during-federal-response-hurricanes-harvey-and-maria",
    "/reports/2024/mental-healthcare-texas-juvenile-justice-system",
    "/news/2024/pennsylvania-advisory-committee-releases-report-rising-use-artificial-intelligence-k-12",
    "/reports/2025/insular-cases-and-doctrine-unincorporated-territory-and-their-effects-civil-rights",
    "/reports/data-inventory-program",
    "/news/2025/us-commission-civil-rights-hold-public-briefing-language-access-individuals-limited"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.usccr.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}