module.exports = {
  "site": "https://www.usccr.gov",
  "urls": [
    "/disclaimer",
    "/reports/2025/examining-racial-impact-public-school-attendance-zones-colorado",
    "/advisory-committees/new-mexico",
    "/reports/2025/disproportionate-impact-covid-19-pandemic-communities-color-delaware",
    "/reports/2023/federal-response-anti-asian-racism-united-states",
    "/advisory-committees/wisconsin",
    "/news/2024/arkansas-advisory-committee-releases-report-right-counsel-arkansas",
    "/about/ashley-taylor",
    "/meetings/2025/08-20-colorado-advisory-committee-virtual-panel-examining-allegations-antisemitism",
    "/about/debo-adegbile",
    "/advisory-committees/district-of-columbia",
    "/about/mauro-morales",
    "/advisory-committees/virginia",
    "/reports/2019/collateral-consequences-crossroads-punishment-redemption-and-effects-communities",
    "/about/dina-titus",
    "/reports/2025/request-congressional-appropriation-fiscal-year-2026",
    "/reports/2025/access-mental-and-behavioral-health-care-students-k-12-schools",
    "/advisory-committees/california",
    "/reports/2025/fy-2025-no-fear-act-report",
    "/about/library",
    "/reports/2020/women-prison-seeking-justice-behind-bars",
    "/about/gerald-reynolds",
    "/reports/2018/police-use-force-examination-modern-policing-practices",
    "/news/2025/puerto-rico-advisory-committee-publishes-its-third-memorandum-right-vote-federal-level",
    "/reports/2024/status-civil-rights-us-virgin-islands",
    "/reports/2019/beyond-suspensions-examining-school-discipline-policies-and-connections-school-prison",
    "/reports/2024/source-income-housing-discrimination-ohio",
    "/states/arkansas",
    "/meetings/2024/03-08-civil-rights-implications-federal-use-facial-recognition-technology",
    "/reports/2025/housing-discrimination-fair-housing-practices-wyoming",
    "/reports/2023/police-oversight-and-accountability-virginia",
    "/reports/2018/public-education-funding-inequity-era-increasing-concentration-poverty-and",
    "/reports/2024/insular-cases-and-doctrine-unincorporated-territory-and-their-effects-civil-rights",
    "/news/2023/us-commission-civil-rights-releases-report-federal-response-anti-asian-racism-united",
    "/news/2025/us-commission-civil-rights-appoints-members-state-advisory-committees-1",
    "/about/abigail-thernstrom",
    "/reports/2018/assessment-minority-voting-rights-access-united-states",
    "/news/2024/arizona-advisory-committee-releases-report-examining-disparities-access-and-quality",
    "/meetings/2025/07-16-colorado-advisory-committee-virtual-panel-examining-allegations-antisemitism",
    "/news/correspondence",
    "/reports/2024/examining-new-york-child-welfare-system-and-its-impact-black-children-and-families",
    "/advisory-committees/georgia",
    "/advisory-committees/indiana",
    "/advisory-committees/north-carolina",
    "/meetings/2025/08-05-south-carolina-advisory-committee-business-meeting",
    "/news/2025/statement-chair-rochelle-m-garza-mens-mental-health-awareness-month",
    "/videos",
    "/about/david-kladney",
    "/advisory-committees/minnesota",
    "/advisory-committees/montana"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.usccr.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}