module.exports = {
  "site": "https://www.cbp.gov",
  "urls": [
    "/travel/trusted-traveler-programs/global-entry",
    "/",
    "/trade/automated/cargo-systems-messaging-service",
    "/travel/us-citizens/mobile-passport-control",
    "/travel/trusted-traveler-programs/global-entry/how-apply",
    "/travel/trusted-traveler-programs/global-entry/enrollment-centers",
    "/travel/international-visitors/i-94",
    "/travel/trusted-traveler-programs/global-entry/enrollment-arrival",
    "/search",
    "/travel/trusted-traveler-programs/global-entry/eligibility",
    "/travel/trusted-traveler-programs/global-entry/global-entry-mobile-application",
    "/travel/trusted-traveler-programs/nexus",
    "/newsroom/publications/forms",
    "/trade/programs-administration/entry-summary/232-tariffs-aluminum-and-steel-faqs",
    "/travel/international-visitors/esta",
    "/travel/trusted-traveler-programs",
    "/travel/us-citizens/know-before-you-go/prohibited-and-restricted-items",
    "/travel/trusted-traveler-programs/global-entry/frequently-asked-questions",
    "/about/contact",
    "/travel",
    "/travel/international-visitors/know-before-you-visit/customs-duty-information",
    "/about/contact/ports",
    "/about/mobile-apps-directory/cbphome",
    "/travel/preclearance",
    "/travel/trusted-traveler-programs/global-entry/card",
    "/travel/us-citizens",
    "/travel/trusted-traveler-programs/sentri",
    "/travel/trusted-traveler-programs/tsa-precheck",
    "/travel/international-visitors",
    "/travel/trusted-traveler-programs/global-entry/airports-with-global-entry",
    "/document/bulletins/six-month-validity-update",
    "/travel/trusted-traveler-programs/global-entry/enrollment-departure",
    "/about/contact/ports/deferred-inspection-sites",
    "/travel/us-citizens/know-before-you-go",
    "/trade/programs-administration/trade-remedies/IEEPA-FAQ",
    "/document/forms/form-6059b-customs-declaration-english-fillable",
    "/about/mobile-apps-directory",
    "/travel/trusted-traveler-programs/global-entry/enrollment-centers/california",
    "/travel/trusted-traveler-programs/sentri/how-apply-sentri",
    "/travel/international-visitors/visa-waiver-program",
    "/travel/international-visitors/agricultural-items",
    "/newsroom/local-media-release/cbp-officers-seize-137k-unreported-us-currency-gateway-international",
    "/travel/international-visitors/i-94/traveler-compliance",
    "/newsroom/local-media-release/cbp-full-bloom-seizes-76-million-methamphetamine-found-shipment-roses",
    "/trade/basic-import-export",
    "/travel/trusted-traveler-programs/global-entry/enrollment-centers/new-york",
    "/newsroom/media-releases/all",
    "/trade/basic-import-export/e-commerce/faqs",
    "/about/contact/brokers-listing",
    "/travel/trusted-traveler-programs/global-entry/benefits"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.cbp.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}