module.exports = {
  "site": "https://cbp.gov",
  "urls": [
    "/travel/trusted-traveler-programs/global-entry",
    "/",
    "/travel/us-citizens/mobile-passport-control",
    "/trade/automated/cargo-systems-messaging-service",
    "/travel/trusted-traveler-programs/global-entry/how-apply",
    "/travel/trusted-traveler-programs/global-entry/eligibility",
    "/travel/trusted-traveler-programs/global-entry/enrollment-arrival",
    "/travel/international-visitors/i-94",
    "/travel/trusted-traveler-programs/global-entry/enrollment-centers",
    "/travel/trusted-traveler-programs/global-entry/global-entry-mobile-application",
    "/newsroom/local-media-release/cbp-arrests-two-us-citizens-port-buffalo-possession-narcotics-and",
    "/travel/trusted-traveler-programs/nexus",
    "/travel/trusted-traveler-programs/global-entry/frequently-asked-questions",
    "/travel/international-visitors/esta",
    "/newsroom/local-media-release/cbp-officers-apprehend-previously-deported-salvadoran-extensive",
    "/travel/us-citizens/know-before-you-go/prohibited-and-restricted-items",
    "/travel/trusted-traveler-programs",
    "/newsroom/publications/forms",
    "/about/mobile-apps-directory/cbphome",
    "/travel",
    "/about/contact",
    "/newsroom/local-media-release/cbp-seizes-nearly-150000-contraband-cigarettes-couple-arriving-cruise",
    "/travel/international-visitors/know-before-you-visit/customs-duty-information",
    "/about/contact/ports",
    "/travel/trusted-traveler-programs/global-entry/card",
    "/travel/trusted-traveler-programs/tsa-precheck",
    "/travel/trusted-traveler-programs/sentri",
    "/travel/us-citizens/know-before-you-go",
    "/travel/trusted-traveler-programs/global-entry/airports-with-global-entry",
    "/travel/us-citizens",
    "/newsroom/local-media-release/philadelphia-cbp-officers-seize-nearly-300-pounds-dried-opium-poppy",
    "/newsroom/local-media-release/cbp-officers-seize-177k-unreported-us-currency-hidalgo-international",
    "/travel/preclearance",
    "/travel/international-visitors",
    "/travel/international-visitors/visa-waiver-program",
    "/newsroom/local-media-release/cbp-officers-seize-78k-unreported-us-currency-brownsville-and",
    "/document/forms/form-6059b-customs-declaration-english-fillable",
    "/newsroom/local-media-release/cbp-officers-apprehend-woman-transporting-fentanyl-internal-cavity",
    "/document/bulletins/six-month-validity-update",
    "/newsroom/local-media-release/cbp-officers-seize-over-48-million-hard-narcotics-colombia-solidarity",
    "/travel/international-visitors/agricultural-items",
    "/newsroom/local-media-release/cbp-officers-seize-more-74k-unreported-us-currency-brownsville-and",
    "/newsroom/local-media-release/massachusetts-woman-arrested-after-pittsburgh-cbp-officers-intercept",
    "/travel/trusted-traveler-programs/global-entry/enrollment-departure",
    "/travel/trusted-traveler-programs/sentri/how-apply-sentri",
    "/travel/trusted-traveler-programs/global-entry/benefits",
    "/travel/trusted-traveler-programs/global-entry/enrollment-centers/california",
    "/newsroom/media-releases/all"
  ],
  "scanner": {
    "crawler": false,
    "sitemap": false,
    "robotsTxt": false
  },
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-dev-shm-usage"
    ]
  }
}