module.exports = {
  "site": "https://www.usccr.gov",
  "urls": [
    "/",
    "/contact/complaints",
    "/eeo",
    "/contact/offices",
    "/search",
    "/about/commissioners",
    "/advisory-committees",
    "/reports",
    "/about/careers",
    "/news/2024/us-commission-civil-rights-releases-report-civil-rights-implications-federal-use-facial",
    "/about/mission",
    "/reports/briefing-reports",
    "/about/offices",
    "/news/2022/us-commission-civil-rights-releases-report-civil-rights-implications-cash-bail",
    "/news",
    "/meetings/event-calendar",
    "/reports/advisory-committees-reports",
    "/news/commission-news",
    "/historical-documents",
    "/limited-english-proficiency-plan",
    "/reports/civil-rights-complaints",
    "/about/stephen-gilchrist",
    "/reports/2024/civil-rights-implications-federal-use-facial-recognition-technology",
    "/meetings/advisory-committees-meetings",
    "/about/rochelle-garza",
    "/archives",
    "/about/faqs",
    "/advisory-committees/membership",
    "/meetings/2025/08-20-colorado-advisory-committee-community-forum-examining-allegations-antisemitism",
    "/news/2024/us-commission-civil-rights-releases-report-federal-efforts-examining-racial-and-ethnic",
    "/meetings/2025/03-21-language-access-individuals-limited-english-proficiency",
    "/about/catherine-lhamon",
    "/reports/annual-statutory-enforcement",
    "/about/mondaire-jones",
    "/news/2021/us-commission-civil-rights-marks-100th-anniversary-tulsa-race-massacre",
    "/advisory-committees/colorado",
    "/reports/2021/civil-rights-implications-cash-bail",
    "/about/j-christian-adams",
    "/meetings/commission-meetings",
    "/about/former-commissioners",
    "/about/glenn-magpantay",
    "/news/2025/us-commission-civil-rights-votes-advance-investigation-campus-antisemitism",
    "/about/peter-kirsanow",
    "/foia",
    "/meetings/public-briefings",
    "/reports/2010/impact-illegal-immigration-wages-and-employment-opportunities-black-workers",
    "/advisory-committees/new-york",
    "/advisory-committees/alaska",
    "/about/gail-heriot",
    "/reports/2025/enforcing-religious-freedom-prisons"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.usccr.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}