module.exports = {
  "site": "https://www.energy.gov",
  "urls": [
    "/",
    "/newsroom",
    "/search",
    "/search",
    "/fecm/key-publications-natural-gas-regulation",
    "/articles/energy-department-announces-actions-secure-american-critical-minerals-and-materials-supply",
    "/ceser/news-highlights",
    "/swpa/generation-schedules",
    "/articles/department-energy-announces-initial-selections-new-reactor-pilot-program",
    "/fecm/office-fossil-energy-and-carbon-management",
    "/scep/wap/how-apply-weatherization-assistance",
    "/topics/climate",
    "/mesc/listings/news-and-insights",
    "/careers/search",
    "/save/home-upgrades",
    "/nepa/listings/categorical-exclusion-cx-determinations-date",
    "/cmm/events/domestic-critical-minerals-and-materials-supply-chains-workshop",
    "/our-leadership-offices",
    "/scep/wap/weatherization-assistance-program",
    "/eere/wind/how-do-wind-turbines-work",
    "/eere/office-energy-efficiency-and-renewable-energy",
    "/work-us-department-energy",
    "/em/office-environmental-management",
    "/cio/login-cloudspacevdi-using-piv-card-or-rsa-token",
    "/eere/solar/homeowners-guide-going-solar",
    "/ne/articles/nuclear-101-how-does-nuclear-reactor-work",
    "/energysaver/heat-pump-systems",
    "/swpa/southwestern-power-administration",
    "/eere/ammto/critical-minerals-and-materials-accelerator-0",
    "/articles/department-energy-issues-report-evaluating-impact-greenhouse-gasses-us-climate-invites",
    "/ne/us-department-energy-reactor-pilot-program",
    "/nnsa/national-nuclear-security-administration",
    "/policy/articles/making-our-homes-more-efficient-clean-energy-tax-credits-consumers",
    "/science/office-science",
    "/topics",
    "/save",
    "/nepa/listings/categorical-exclusion-determinations-a9",
    "/articles/us-department-energy-distribute-next-round-haleu-us-nuclear-industry",
    "/energysaver/energy-saver",
    "/articles/history-light-bulb",
    "/energysaver/new-and-used-clean-vehicle-tax-credits",
    "/nepa/listings/categorical-exclusion-determinations-b36",
    "/national-laboratories",
    "/ne/articles/advantages-and-challenges-nuclear-energy",
    "/eere/solar/how-does-solar-work",
    "/energysaver/purchasing-and-maintaining-water-softener",
    "/articles/doe-releases-new-report-evaluating-increase-electricity-demand-data-centers",
    "/energysaver/types-insulation",
    "/eere/wind/advantages-and-challenges-wind-energy",
    "/energysaver/estimating-appliance-and-home-electronic-energy-use",
    "/energysaver/heat-pump-water-heaters",
    "/articles/energy-department-announces-over-35-million-advance-emerging-energy-technologies",
    "/ne/articles/energy-department-establish-new-consortium-nuclear-fuel-supply-chain"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.energy.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 106,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}