module.exports = {
  "site": "https://epa.gov",
  "urls": [
    "/",
    "/renewable-fuel-standard-program/news-notices-and-announcements-renewable-fuel-standard",
    "/fuels-registration-reporting-and-compliance-help/spreadsheet-available-rins-date-renewable-fuel",
    "/ghgemissions/sources-greenhouse-gas-emissions",
    "/ingredients-used-pesticide-products/glyphosate",
    "/energy/greenhouse-gas-equivalencies-calculator",
    "/newsreleases/epa-announces-it-will-keep-maximum-contaminant-levels-pfoa-pfos",
    "/pfas/pfas-explained",
    "/ghgemissions/overview-greenhouse-gases",
    "/bedbugs/bed-bugs-appearance-and-life-cycle",
    "/acidrain/what-acid-rain",
    "/fuels-registration-reporting-and-compliance-help/spreadsheet-rin-generation-and-renewable-fuel-0",
    "/bedbugs/do-it-yourself-bed-bug-control",
    "/recycle/composting-home",
    "/air-emissions-factors-and-quantification/ap-42-compilation-air-emissions-factors-stationary-sources",
    "/ghgemissions/carbon-footprint-calculator",
    "/climatechange-science/causes-climate-change",
    "/recycle/recycling-basics-and-benefits",
    "/fuels-registration-reporting-and-compliance-help/spreadsheet-rin-generation-data-renewable-fuel",
    "/aboutepa/forms/contact-epa",
    "/ground-water-and-drinking-water/national-primary-drinking-water-regulations",
    "/sdwa/and-polyfluoroalkyl-substances-pfas",
    "/lead/protect-your-family-lead-your-home-english",
    "/pm-pollution/particulate-matter-pm-basics",
    "/climateimpacts/climate-change-impacts-agriculture-and-food-supply",
    "/risk/regional-screening-levels-rsls-generic-tables",
    "/pets/controlling-fleas-and-ticks-around-your-home",
    "/greenvehicles/electric-vehicle-myths",
    "/hw/defining-hazardous-waste-listed-characteristic-and-mixed-radiological-wastes",
    "/acidrain/effects-acid-rain",
    "/newsreleases/epa-launches-biggest-deregulatory-action-us-history",
    "/plastics/impacts-plastic-pollution",
    "/greenvehicles/greenhouse-gas-emissions-typical-passenger-vehicle",
    "/climateleadership/ghg-emission-factors-hub",
    "/laws-regulations/summary-clean-water-act",
    "/septic/types-septic-systems",
    "/pesticide-registration/selected-epa-registered-disinfectants",
    "/environmental-topics",
    "/environmental-topics/air-topics",
    "/pfas/our-current-understanding-human-health-and-environmental-risks-pfas",
    "/energy/greenhouse-gas-equivalencies-calculator-calculations-and-references",
    "/facts-and-figures-about-materials-waste-and-recycling/national-overview-facts-and-figures-materials",
    "/indoor-air-quality-iaq/should-you-have-air-ducts-your-home-cleaned",
    "/safepestcontrol/termites-how-identify-and-control-them",
    "/toxics-release-inventory-tri-program",
    "/ground-water-and-drinking-water",
    "/mold/brief-guide-mold-moisture-and-your-home",
    "/careers",
    "/lead",
    "/pfas",
    "/ground-water-and-drinking-water/basic-information-about-lead-drinking-water",
    "/aboutepa/our-mission-and-what-we-do",
    "/section608/section-608-technician-certification-requirements",
    "/tsca-inventory",
    "/indoor-air-quality-iaq/ozone-generators-are-sold-air-cleaners",
    "/climate-indicators/weather-climate",
    "/ground-level-ozone-pollution/ground-level-ozone-basics",
    "/ghgemissions/global-greenhouse-gas-overview",
    "/laws-regulations/summary-clean-air-act",
    "/topics-epa-web",
    "/goldkingmine/what-ph",
    "/superfund",
    "/tsca-inventory/how-access-tsca-inventory",
    "/aboutepa",
    "/outdoor-air-quality-data",
    "/cameo/aloha-software"
  ],
  "scanner": {
    "crawler": false,
    "sitemap": false,
    "robotsTxt": false
  },
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-dev-shm-usage"
    ]
  }
}