module.exports = {
  "site": "https://www.epa.gov",
  "urls": [
    "/newsreleases/search",
    "/renewable-fuel-standard/news-notices-and-announcements-renewable-fuel-standard",
    "/",
    "/fuels-registration-reporting-and-compliance-help/spreadsheet-available-rins-date-renewable-fuel",
    "/bedbugs/do-it-yourself-bed-bug-control",
    "/energy/greenhouse-gas-equivalencies-calculator",
    "/bedbugs/how-find-bed-bugs",
    "/regulations-emissions-vehicles-and-engines/proposed-rule-reconsideration-2009-endangerment-finding",
    "/pets/controlling-fleas-and-ticks-around-your-home",
    "/newsreleases/epa-releases-proposal-rescind-obama-era-endangerment-finding-regulations-paved-way",
    "/fuels-registration-reporting-and-compliance-help/rins-generated-transactions",
    "/superfund/search-superfund-sites-where-you-live",
    "/bedbugs/bed-bugs-appearance-and-life-cycle",
    "/newsreleases/epa-launches-biggest-deregulatory-action-us-history",
    "/newsreleases/iowa-state-fair-epa-administrator-zeldin-announces-diesel-exhaust-fluid-def-fix",
    "/fuels-registration-reporting-and-compliance-help/spreadsheet-rin-generation-and-renewable-fuel-0",
    "/air-emissions-factors-and-quantification/ap-42-compilation-air-emissions-factors-stationary-sources",
    "/ingredients-used-pesticide-products/glyphosate",
    "/mold/brief-guide-mold-moisture-and-your-home",
    "/ground-water-and-drinking-water/national-primary-drinking-water-regulations",
    "/lead/protect-your-family-lead-your-home-english",
    "/ghgemissions/sources-greenhouse-gas-emissions",
    "/water-research/epanet",
    "/fuels-registration-reporting-and-compliance-help/spreadsheet-rin-generation-data-renewable-fuel",
    "/lead",
    "/ground-water-and-drinking-water",
    "/aboutepa/forms/contact-epa",
    "/recycle/composting-home",
    "/pfas/pfas-explained",
    "/risk/regional-screening-levels-rsls-generic-tables",
    "/indoor-air-quality-iaq/should-you-have-air-ducts-your-home-cleaned",
    "/ghgemissions/carbon-footprint-calculator",
    "/hw/defining-hazardous-waste-listed-characteristic-and-mixed-radiological-wastes",
    "/egrid/power-profiler",
    "/acidrain/what-acid-rain",
    "/dwucmr/fifth-unregulated-contaminant-monitoring-rule-data-finder",
    "/pesticide-registration/selected-epa-registered-disinfectants",
    "/tsca-inventory/how-access-tsca-inventory",
    "/energy/greenhouse-gas-equivalencies-calculator-calculations-and-references",
    "/indoor-air-quality-iaq/ozone-generators-are-sold-air-cleaners",
    "/laws-regulations/summary-clean-water-act",
    "/sdwa/and-polyfluoroalkyl-substances-pfas",
    "/ghgemissions/overview-greenhouse-gases",
    "/comptox-tools",
    "/climateleadership/ghg-emission-factors-hub",
    "/mold/mold-cleanup-your-home",
    "/careers",
    "/septic/types-septic-systems",
    "/pm-pollution/particulate-matter-pm-basics",
    "/greenvehicles/electric-vehicle-myths",
    "/recycle/recycling-basics-and-benefits",
    "/water-research/storm-water-management-model-swmm",
    "/regulations-emissions-vehicles-and-engines/diesel-exhaust-fluid",
    "/section608/section-608-technician-certification-requirements",
    "/climatechange-science/causes-climate-change",
    "/insect-repellents/find-repellent-right-you",
    "/fuels-registration-reporting-and-compliance-help/rfs-small-refinery-exemptions",
    "/ground-water-and-drinking-water/basic-information-about-lead-drinking-water",
    "/environmental-topics",
    "/tsca-inventory",
    "/laws-regulations/summary-clean-air-act",
    "/bedbugs",
    "/hwgenerators/instructions-and-form-hazardous-waste-generators-transporters-and-treatment-storage",
    "/laws-regulations",
    "/radon",
    "/topics-epa-web",
    "/dwcapacity/midsize-and-large-drinking-water-system-infrastructure-resilience-and-sustainability",
    "/mold",
    "/aboutepa",
    "/environmental-topics/air-topics",
    "/sites/default/files/widgets/mywaterway/index.html",
    "/aboutepa/our-mission-and-what-we-do",
    "/guidance",
    "/greenhouse-gas-reduction-fund/solar-all",
    "/facts-and-figures-about-materials-waste-and-recycling/national-overview-facts-and-figures-materials",
    "/aboutepa/regional-and-geographic-offices",
    "/watersense",
    "/pfas/our-current-understanding-human-health-and-environmental-risks-pfas",
    "/lead/lead-renovation-repair-and-painting-program",
    "/climateimpacts/climate-change-impacts-agriculture-and-food-supply"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.epa.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 160,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}