module.exports = {
  "site": "https://www.eeoc.gov",
  "urls": [
    "/youth/frequently-asked-questions",
    "/federal-sector",
    "/laws/guidance/applying-performance-and-conduct-standards-employees-disabilities",
    "/field-office/miami/location",
    "/federal-sector/contacting-eeo-counselor",
    "/ar/althrsh",
    "/youth/your-rights",
    "/laws/guidance/background-checks-what-employers-need-know",
    "/field-office/houston/location",
    "/field-office/newyork/location",
    "/laws/guidance/questions-and-answers-enforcement-guidance-retaliation-and-related-issues",
    "/statutes/equal-pay-act-1963",
    "/genetic-information-discrimination",
    "/initiatives/e-race/significant-eeoc-racecolor-casescovering-private-and-federal-sectors",
    "/field-office/philadelphia/location",
    "/wysk/state-eeoc-frequently-asked-questions",
    "/fair-employment-practices-agencies-fepas-and-dual-filing",
    "/laws/guidance/qa-understanding-waivers-discrimination-claims-employee-severance-agreements",
    "/pre-employment-inquiries-and-medical-questions-examinations",
    "/summary-key-provisions-eeocs-final-rule-implement-pregnant-workers-fairness-act-pwfa",
    "/youth/what-employment-discrimination",
    "/zipcode/search",
    "/youth/real-eeoc-cases",
    "/employers/small-business/what-shouldnt-i-ask-when-hiring",
    "/newsroom/eeoc-issues-three-significant-federal-sector-appellate-decisions-0",
    "/laws/guidance/job-applicants-and-ada",
    "/laws/guidance/fact-sheet-disability-discrimination",
    "/field-office/sanantonio/location",
    "/federal-sector/management-directive/management-directives-guidance-and-resource-documents",
    "/employers/small-business/3-who-protected-employment-discrimination",
    "/eeoc-disability-related-resources/reasonable-accommodation",
    "/field-office/tampa/location",
    "/litigation/briefs/xxxxxxxxxx-v-xxxxxxxxx-inc",
    "/data/eeo-1-employer-information-report-statistics",
    "/foia/contact-us",
    "/field-office/denver/location",
    "/youth/time-limits-filing-complaint",
    "/statutes/pregnancy-discrimination-act-1978",
    "/laws/guidance/background-checks-what-job-applicants-and-employees-should-know",
    "/employers/small-business/4-what-cant-i-ask-when-hiring",
    "/select-task-force-study-harassment-workplace",
    "/field-office/detroit/location",
    "/fact-sheet-religious-accommodations-workplace",
    "/field-office/charlotte/location",
    "/data/sexual-harassment-our-nations-workplaces",
    "/field-office/losangeles/location",
    "/field-office/indianapolis/location",
    "/statutes/genetic-information-nondiscrimination-act-2008",
    "/proposed-enforcement-guidance-harassment-workplace",
    "/publications/federal-eeo-complaint-processing-procedures"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.eeoc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}