module.exports = {
  "site": "https://www.eeoc.gov",
  "urls": [
    "/",
    "/filing-charge-discrimination",
    "/how-file-charge-employment-discrimination",
    "/ar/althrsh-aljnsy",
    "/field-office",
    "/search",
    "/poster",
    "/statutes/title-vii-civil-rights-act-1964",
    "/employees-job-applicants",
    "/laws/guidance/enforcement-guidance-reasonable-accommodation-and-undue-hardship-under-ada",
    "/harassment",
    "/time-limits-filing-charge",
    "/wysk/what-you-should-know-about-pregnant-workers-fairness-act",
    "/prohibited-employment-policiespractices",
    "/filing-lawsuit",
    "/contact-eeoc",
    "/newsroom/search",
    "/what-you-can-expect-after-you-file-charge",
    "/youth/how-file-complaint",
    "/retaliation",
    "/federal-sector/overview-federal-sector-eeo-complaint-process",
    "/eeoc-disability-related-resources",
    "/sexual-harassment",
    "/youth/filing-complaint",
    "/newsroom",
    "/federal-sector/filing-formal-complaint",
    "/publications/ada-your-responsibilities-employer",
    "/wysk/what-you-should-know-about-dei-related-discrimination-work",
    "/overview",
    "/ar/altmyyz-alqaym-ly-aljns",
    "/age-discrimination",
    "/laws/guidance/enforcement-guidance-harassment-workplace",
    "/know-your-rights-workplace-discrimination-illegal",
    "/federal-sector/appellate-decisions",
    "/disability-discrimination-and-employment-decisions",
    "/data/eeo-data-collections",
    "/eeoc-legal-resources",
    "/racecolor-discrimination",
    "/confidentiality",
    "/statutes/pregnant-workers-fairness-act",
    "/sex-based-discrimination",
    "/pregnancy-discrimination",
    "/employers/what-you-can-expect-after-charge-filed",
    "/laws/guidance/work-hometelework-reasonable-accommodation",
    "/religious-discrimination",
    "/what-do-if-you-experience-discrimination-related-dei-work",
    "/laws/guidance/depression-ptsd-other-mental-health-conditions-workplace-your-legal-rights",
    "/employers",
    "/eeoc-public-portal",
    "/laws/guidance/employer-provided-leave-and-americans-disabilities-act"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.eeoc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}