module.exports = {
  "site": "https://www.eeoc.gov",
  "urls": [
    "/remedies-employment-discrimination",
    "/es/initial-consultation",
    "/statutes/age-discrimination-employment-act-1967",
    "/youth/harassment-faqs",
    "/data/enforcement-and-litigation-statistics-0",
    "/laws/guidance/legal-rights-pregnant-workers-under-federal-law",
    "/newsroom/largest-eeoc-public-settlement-almost-20-years-columbia-university-agrees-pay-21-million",
    "/after-you-have-filed-charge",
    "/equal-employment-opportunity-laws",
    "/employers/recordkeeping-requirements",
    "/laws",
    "/publications/ada-your-employment-rights-individual-disability",
    "/field-office/atlanta/location",
    "/laws/guidance/section-12-religious-discrimination",
    "/checking-status-your-charge",
    "/laws/guidance/enforcement-guidance-disability-related-inquiries-and-medical-examinations-employees",
    "/laws/guidance/what-you-should-know-workplace-religious-accommodation",
    "/pre-employment-inquiries-and-gender",
    "/search/advanced-search",
    "/federal-sector/federal-agency-eeo-directors",
    "/newsroom/200-days-eeoc-action-protect-religious-freedom-work",
    "/facts-about-retaliation",
    "/employers/effective-position-statements",
    "/equal-paycompensation-discrimination",
    "/laws/guidance/fact-sheet-sexual-harassment-discrimination",
    "/statutes/titles-i-and-v-americans-disabilities-act-1990-ada",
    "/outreach-extravaganza-2025",
    "/youth/who-can-file-complaint",
    "/federal-sector/management-directive/management-directive-110",
    "/questions-and-answers-charging-parties-eeocs-new-position-statement-procedures",
    "/laws/guidance/enforcement-guidance-retaliation-and-related-issues",
    "/publications/abcs-schedule-tips-applicants-disabilities-getting-federal-jobs",
    "/laws/guidance/enforcement-guidance-pregnancy-discrimination-and-related-issues",
    "/field-office/dallas/location",
    "/coverage",
    "/wysk",
    "/newsroom/mercyhealth-pay-over-1-million-settle-eeoc-covid-19-vaccine-mandate-related-religious",
    "/field-office/phoenix/location",
    "/laws/guidance/enforcement-guidance-consideration-arrest-and-conviction-records-employment-decisions",
    "/eeoc-guidance",
    "/field-office/chicago/location",
    "/eeoc-publications",
    "/wysk/what-you-should-know-about-covid-19-and-ada-rehabilitation-act-and-other-eeo-laws",
    "/retaliation-making-it-personal",
    "/national-origin-discrimination",
    "/foia",
    "/mediation",
    "/statutes/ada-amendments-act-2008",
    "/questions-and-answers-employees-harassment-work",
    "/summary-key-provisions-eeoc-enforcement-guidance-harassment-workplace"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.eeoc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}