module.exports = {
  "site": "https://www.nitrd.gov",
  "urls": [
    "/",
    "/news/",
    "/coordination-areas/ai/90-fr-9088-responses/",
    "/about-nitrd/",
    "/ai-rd-investments/",
    "/publications/",
    "/coordination-areas/ai/",
    "/national-artificial-intelligence-research-and-development-strategic-plan-2023-update/",
    "/stem4all/",
    "/coordination-areas/ai/90-fr-17835-responses/",
    "/90-fr-17835-responses/",
    "/request-for-information-on-the-development-of-a-2025-national-artificial-intelligence-ai-research/",
    "/nitrd-national-coordination-office-nco/",
    "/ai-rd-testbed-inventory/",
    "/search/",
    "/90-fr-9088-responses/",
    "/resources/",
    "/request-for-information-on-the-development-of-an-artificial-intelligence-ai-action-plan/",
    "/nsci/",
    "/spsq-cmu-software-ai-engineering-workshop-report-2024/",
    "/ai-research-and-development-progress-report-2020-2024/",
    "/nitrd-dashboard/",
    "/fy2025-nitrd-naiio-supplement/",
    "/program-component-areas/",
    "/presentations/",
    "/big-data-strategic-plan-2024/",
    "/program-component-areas/nitrd-pcas-2026/",
    "/national-spectrum-rd-plan-2024/",
    "/category/ai/",
    "/ai-research-program-repository/",
    "/ai-bill-of-rights/",
    "/foundation-llm-health-workshop-report/",
    "/nitrd-nco-announces-kirk-dohne-as-deputy-director/",
    "/networking-and-information-technology-research-and-development-request-for-information-on-digital/",
    "/nitrd-30th-symposium-panel-3-recap/",
    "/national-privacy-research-strategy/",
    "/category/supplement-to-the-presidents-budget/",
    "/request-for-information-to-the-update-of-the-national-artificial-intelligence-research-and-development-strategic-plan/",
    "/legislation/",
    "/30th-anniversary-of-the-nitrd-program/robert-bonneau/",
    "/historical-documents/pitac/",
    "/framework-for-improving-critical-infrastructure-cybersecurity/",
    "/events/",
    "/30th-anniversary-of-the-nitrd-program/erwin-gianchandani/",
    "/cybersecurity/",
    "/hecportal/",
    "/30th-anniversary-of-the-nitrd-program/richard-conroy/",
    "/federal-cybersecurity-rd-strategic-plan-2023/",
    "/program-component-areas/nitrd-pcas-2025/",
    "/big-data-measuring-the-impact-of-digital-repositories/",
    "/nitrd-nco-staff-and-personnel/faisal-dsouza/",
    "/30th-anniversary-of-the-nitrd-program/joydip-kundu/",
    "/privacy-policy/",
    "/fy2024-nitrd-naiio-supplement/",
    "/wsrd-workshop-on-the-national-spectrum-rd-plan/",
    "/coordination-areas/",
    "/coordination-areas/digital-twins/89-fr-51554-responses/",
    "/artificial-intelligence-wireless-spectrum-opportunities-and-challenges/",
    "/cybersecurity/jscore/",
    "/pcast-releases-report-on-revitalizing-the-u-s-semiconductor-ecosystem/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nitrd.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 120,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}