module.exports = {
  "site": "https://www.fcsic.gov",
  "urls": [
    "/",
    "/about/leadership",
    "/news",
    "/about/faqs_new/the-basics",
    "/insurance-fund/insurance-fund",
    "/about/faqs_new/the-farm-credit-system",
    "/about/faqs_new/how-fcsic-insurance-works",
    "/notices/site-security",
    "/insurance-fund/insurance-premiums",
    "/about/glen-r.-smith",
    "/regulations/regulations",
    "/about/faqs_new/the-insurance-fund",
    "/news/detail/fcsic-board-of-directors-approves-the-mid-year-2025-premium-review-july-10-2025",
    "/about/general-information",
    "/notices/accessibility",
    "/notices/foia",
    "/financials/financial-statements",
    "/about/careers",
    "/notices/vulnerability-disclosure-policy",
    "/notices/no-fear-act-data",
    "/notices/data-and-other-information",
    "/notices/privacy",
    "/financials/annual-reports",
    "/notices/employee-survey-results",
    "/news/detail/2024-fcsic-annual-report-is-available",
    "/notices/operating-status-at-fcsic",
    "/notices/eeo-and-diversity",
    "/news/detail/fcsic-notice-of-regular-board-meeting-april-9-2025",
    "/news/detail/fcsic-notice-of-regular-board-meeting-july-9-2025",
    "/regulations/laws-regulations",
    "/financials/investment-portfolio",
    "/about/strategic-annual-plans",
    "/about/helfpul-links",
    "/about/mission",
    "/about/faqs_new/premiums",
    "/insurance-fund/insured-debt",
    "/news/",
    "/regulations/policies",
    "/news/board-meetings",
    "/risk/fcsics-risk-profile",
    "/risk/risk-management",
    "/about/faqs_new/troubled-system-institutions",
    "/risk/loss-protection-layers-for-system-investors",
    "/about/compensation",
    "/about/faqs_new/fcsic-operations",
    "/about/faqs",
    "/notices/index/accessibility",
    "/news/detail/fcsic-notice-of-regular-board-meeting-february-7-2024",
    "/news/detail/fcsic-notice-of-regular-board-meeting-february-8-2023",
    "/news/detail/fcsic-notice-of-regular-board-meeting-october-11-2023",
    "/news/detail/fcsic-reports-third-quarter-2018-financial-statements",
    "/news/detail/fcsic-votes-to-return-excess-funds-to-farm-credit-institutions",
    "/about/fcsic-benefits",
    "/news/detail/fcsic-seeks-comments-on-draft-strategic-plan-fy-2024-2029"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.fcsic.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 108,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}