module.exports = {
  "site": "https://fcsic.gov",
  "urls": [
    "/",
    "/news",
    "/about/faqs_new/the-basics",
    "/about/leadership",
    "/insurance-fund/insurance-fund",
    "/financials/annual-reports",
    "/about/faqs_new/the-farm-credit-system",
    "/insurance-fund/insurance-premiums",
    "/notices/site-security",
    "/about/general-information",
    "/about/glen-r.-smith",
    "/notices/privacy",
    "/notices/foia",
    "/about/faqs_new/the-insurance-fund",
    "/about/faqs_new/how-fcsic-insurance-works",
    "/notices/accessibility",
    "/about/careers",
    "/financials/financial-statements",
    "/news/detail/fcsic-notice-of-regular-board-meeting-april-9-2025",
    "/news/detail/fcsic-board-of-directors-votes-to-return-excess-funds-to-farm-credit-system-banks",
    "/notices/data-and-other-information",
    "/notices/eeo-and-diversity",
    "/regulations/regulations",
    "/notices/vulnerability-disclosure-policy",
    "/news/detail/fcsic-notice-of-regular-board-meeting-march-12-2025",
    "/about/faqs_new/premiums",
    "/news/detail/fcsic-board-approves-premium-rates-for-2025-calendar-year",
    "/notices/no-fear-act-data",
    "/notices/employee-survey-results",
    "/notices/operating-status-at-fcsic",
    "/insurance-fund/insured-debt",
    "/regulations/laws-regulations",
    "/about/mission",
    "/news/board-meetings",
    "/about/strategic-annual-plans",
    "/financials/investment-portfolio",
    "/about/compensation",
    "/about/jeffery-s-hall",
    "/about/faqs",
    "/news/detail/2024-fcsic-annual-report-is-available",
    "/about/helfpul-links",
    "/about/fcsic-benefits",
    "/regulations/policies",
    "/site/contact",
    "/about/faqs_new/troubled-system-institutions",
    "/news/",
    "/risk/risk-management",
    "/risk/loss-protection-layers-for-system-investors",
    "/about/vincent-g-logan",
    "/about/faqs_new/fcsic-operations",
    "/risk/fcsics-risk-profile"
  ],
  "scanner": {
    "crawler": false,
    "sitemap": false,
    "robotsTxt": false
  },
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-dev-shm-usage"
    ]
  }
}