module.exports = {
  "site": "https://www.fec.gov",
  "urls": [
    "/data/receipts/individual-contributions/?two_year_transaction_period=2026&min_date=01/01/2025&max_date=12/31/2026",
    "/",
    "/",
    "/",
    "/data/receipts/?two_year_transaction_period=2026&min_date=01/01/2025&max_date=12/31/2026",
    "/",
    "/data/disbursements/?two_year_transaction_period=2026&min_date=01/01/2025&max_date=12/31/2026",
    "/",
    "/",
    "/",
    "/",
    "/",
    "/",
    "/data/filings/",
    "/",
    "/",
    "/data/elections/",
    "/",
    "/data/committees/",
    "/",
    "/",
    "/data/candidates/",
    "/",
    "/data/browse-data/",
    "/",
    "/data/candidates/house/",
    "/",
    "/",
    "/data/candidate/H6TX31078/",
    "/",
    "/data/receipts/individual-contributions/?two_year_transaction_period=2026&min_date=01/01/2025&max_date=12/31/2026",
    "/",
    "/",
    "/",
    "/",
    "/",
    "/",
    "/",
    "/",
    "/",
    "/data/raising-bythenumbers/",
    "/",
    "/",
    "/",
    "/data/independent-expenditures/?most_recent=true",
    "/",
    "/",
    "/data/candidates/senate/",
    "/",
    "/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.fec.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}