module.exports = {
  "site": "https://www.ftc.gov",
  "urls": [
    "/",
    "/legal-library/browse/cases-proceedings",
    "/legal-library/browse/early-termination-notices",
    "/enforcement/refunds/fortnite-refunds",
    "/rn-database/search",
    "/legal-library/browse/cases-proceedings/banned-debt-collectors/list",
    "/business-guidance/resources/complying-coppa-frequently-asked-questions",
    "/enforcement/refunds",
    "/news-events/events",
    "/business-guidance/blog/2019/11/youtube-channel-owners-your-content-directed-children",
    "/news-events/news/press-releases",
    "/legal-library/browse/statutes/fair-credit-reporting-act",
    "/news-events/news/press-releases/2025/09/ftc-takes-action-against-operators-pornhub-other-pornographic-sites-deceiving-users-about-efforts",
    "/enforcement/refunds/equifax-data-breach-settlement",
    "/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa",
    "/about-ftc/contact",
    "/news-events/news/press-releases/2025/08/ftc-sues-la-fitness-making-it-difficult-consumers-cancel-gym-memberships",
    "/legal-library/browse/cases-proceedings/case-document-search",
    "/legal-library/browse/rules/fair-debt-collection-practices-act-text",
    "/news-events/news/press-releases/2025/08/ftc-data-show-more-four-fold-increase-reports-impersonation-scammers-stealing-tens-even-hundreds",
    "/business-guidance/resources/can-spam-act-compliance-guide-business",
    "/media/71268",
    "/news-events/events/events-calendar",
    "/news-events/news/press-releases/2024/04/ftc-announces-rule-banning-noncompetes",
    "/news-events/news/press-releases/2025/08/ftc-takes-action-against-ticket-resellers-using-illegal-tactics-bypass-ticket-limit-protections",
    "/policy-notices/privacy-policy",
    "/news-events/events/2025/08",
    "/news-events/events/2025/07",
    "/business-guidance/resources/qa-telemarketers-sellers-about-dnc-provisions-tsr-0",
    "/about-ftc/bureaus-offices/bureau-consumer-protection",
    "/enforcement/refunds/t-mobile-refunds",
    "/enforcement/recent-ftc-cases-resulting-refunds/refund-programs-frequently-asked-questions",
    "/business-guidance/privacy-security/gramm-leach-bliley-act",
    "/legal-library/browse/warning-letters",
    "/business-guidance/privacy-security/childrens-privacy",
    "/legal-library/search",
    "/news-events/news/commission-actions",
    "/es",
    "/legal-library",
    "/legal-library/browse/advocacy-filings",
    "/enforcement/refunds/arise-settlement",
    "/news-events/news/press-releases/2025/08/match-group-agrees-pay-14-million-permanently-stop-deceptive-advertising-cancellation-billing",
    "/news-events/news/press-releases/2025/08/assurance-iq-mediaalpha-pay-total-145-million-settle-ftc-charges-they-misled-consumers-seeking",
    "/news-events/news/press-releases/2025/08/ftc-chairman-ferguson-warns-companies-against-censoring-or-weakening-data-security-americans-behest",
    "/news-events/news/press-releases/2025/03/new-ftc-data-show-big-jump-reported-losses-fraud-125-billion-2024",
    "/legal-library/browse/cases-proceedings/241-0095-gtcr-bc-holdings-llc-surmodics-inc-matter",
    "/business-guidance/resources/ftcs-endorsement-guides-what-people-are-asking",
    "/news-events/topics/identity-theft/report-identity-theft",
    "/news-events/news/press-releases/2025/09/disney-pay-10-million-settle-ftc-allegations-company-enabled-unlawful-collection-childrens-personal",
    "/business-guidance/resources/disclosures-101-social-media-influencers",
    "/news-events/explore-data",
    "/business-guidance/privacy-security",
    "/enforcement/premerger-notification-program",
    "/legal-library/browse/advisory-opinions/opinion-04-4",
    "/news-events",
    "/news-events/data-visualizations/data-spotlight/2025/08/false-alarm-real-scam-how-scammers-are-stealing-older-adults-life-savings",
    "/legal-library/browse/hsr-informal-interpretations",
    "/news-events/news/press-releases/2025/08/ftc-resolves-antitrust-concerns-arising-clean-truck-partnership"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.ftc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 116,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}