module.exports = {
  "site": "https://www.fmc.gov",
  "urls": [
    "/articles/alert-fmc-warns-public-about-fraudulent-e-mail-solicitations/",
    "/articles/fmc-examining-restrictive-port-practices-of-the-government-of-spain/",
    "/articles/fmc-publishes-final-rule-on-unreasonable-refusal-to-deal/",
    "/category/news-articles/press-releases/",
    "/licensing-and-certification/how-to-apply-for-a-pvo-certificate/",
    "/about/bureaus-offices/office-of-the-general-counsel-ogc/preparing-and-filing-ocean-common-carrier-and-marine-terminal-agreements/",
    "/oti-update/june-16-2025-ocean-transportation-intermediary-license-applicants/",
    "/articles/fmc-march-2025-activity-report/",
    "/complaints-and-assistance/international-move/",
    "/about/bureaus-offices/office-of-equal-employment-opportunity-oeeo/",
    "/oti-update/march-10-2025-ocean-transportation-intermediary-license-applicants/",
    "/oti-update/june-9-2025-ocean-transportation-intermediary-license-applicants/",
    "/articles/fmc-approves-2-million-settlement-agreement-with-hapag-lloyd/",
    "/articles/two-shipping-lines-pay-civil-penalties-totaling-2-65-million/",
    "/articles/fmc-adding-two-administrative-law-judges-on-temporary-basis/",
    "/about/strategies-budgets-and-performance/strategic-plans/",
    "/oti-update/april-28-2025-ocean-transportation-intermediary-license-applicants/",
    "/articles/page/2/",
    "/about/freedom-of-information-act-requests-reports/",
    "/articles/industry-advisory-interim-procedures-for-submitting-charge-complaints-under-46-u-s-c-%C2%A7-41310/",
    "/ftdo/",
    "/articles/fmc-conducting-network-maintenance-impacting-applications-on-saturday-april-6-2024/",
    "/articles/fmc-establishes-ocean-carriers-audit-program/",
    "/articles/industry-advisory-demurrage-detention-billing-practices/",
    "/about/bureaus-offices/bureau-of-enforcement-investigations-and-compliance-beic/office-of-compliance/",
    "/ftdo/statement-of-commissioner-louis-e-sola-on-the-investigation-concerning-spanish-ports/",
    "/articles/gemini-cooperation-agreement-to-take-effect/",
    "/articles/maximum-penalty-fees-adjusted-2/",
    "/open-government-at-the-fmc/",
    "/about/bureaus-offices/office-of-the-general-counsel-ogc/agreement-monitoring/",
    "/articles/industry-advisory-all-fmc-statutes-and-regulations-remain-in-full-effect-in-the-event-of-terminal-closures-related-to-possible-work-stoppage/",
    "/articles/louis-e-sola-designated-chairman-of-federal-maritime-commission/",
    "/fact-finding-28/",
    "/articles/industry-advisory-names-of-non-compliant-nvoccs-posted-to-fmc-website/",
    "/oti-update/june-23-2025-ocean-transportation-intermediary-license-applicants/",
    "/oti-update/may-27-2025-ocean-transportation-intermediary-license-applicants/",
    "/about/bureaus-offices/consumer-affairs-dispute-resolution-services/moving-dos-and-donts/",
    "/category/news-articles/",
    "/about/bureaus-offices/inspector-general/oig-audits-and-reviews/",
    "/licensing-and-certification/archived-oti-license-revocations-and-surrenders/",
    "/about/strategies-budgets-and-performance/congressional-budget-reports/",
    "/articles/industry-advisory-requirement-to-file-timely-and-accurate-service-contracts-2/",
    "/articles/maximum-penalty-fees-adjusted/",
    "/ftdo/statement-of-chairman-louis-e-sola-registries-must-close-rolls-to-shadow-fleet-vessels/",
    "/ftdo/commissioners-maffei-and-vekich-visit-philadelphia-maritime-infrastructure-sites/",
    "/oti-update/december-23-2024-ocean-transportation-intermediary-license-applicants/",
    "/articles/fmc-monitoring-and-review-of-surcharges-and-fees/",
    "/fact-finding-29/",
    "/oti-update/april-29-2024-ocean-transportation-intermediary-license-applications/",
    "/articles/fmc-updates-controlled-carrier-list/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.fmc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}