module.exports = {
  "site": "https://www.tsp.gov",
  "urls": [
    "/",
    "/login/",
    "/mobile/",
    "/share-price-history/",
    "/access-your-account/",
    "/index.html",
    "/tsp/",
    "/fund-performance/",
    "/taking-money-from-your-account/",
    "/contact/",
    "/exit/",
    "/withdrawals-in-retirement/",
    "/calculators/",
    "/funds-individual/",
    "/tsp-loans/",
    "/forms/",
    "/funds-lifecycle/",
    "/mobile/404.html",
    "/calculators/tsp-annuity-calculator/",
    "/making-contributions/contribution-limits/",
    "/making-contributions/",
    "/tsp-basics/",
    "/search/",
    "/access-your-account/troubleshoot-account-access/",
    "/making-contributions/traditional-and-roth-contributions/",
    "/investment-options/",
    "/funds-individual/c-fund/",
    "/tsp-mobile-app/",
    "/online-learning/",
    "/tsp-basics/move-money-into-tsp/",
    "/funds-lifecycle/l-income/",
    "/making-contributions/how-much-can-i-contribute/",
    "/funds-lifecycle/l-2030/",
    "/making-contributions/contribution-types/",
    "/investing-strategies/",
    "/funds-individual/g-fund/",
    "/funds-individual/i-fund/",
    "/funds-individual/s-fund/",
    "/making-contributions/contribution-limits/",
    "/for-beneficiaries/",
    "/changes-in-your-career/leaving-the-federal-government/",
    "/in-service-withdrawal-basics/",
    "/mobile/access-your-account/troubleshoot-account-access/",
    "/funds-lifecycle/l-2075/",
    "/mutual-fund-window/",
    "/tsp-basics/grow-with-the-tsp/",
    "/funds-lifecycle/l-2040/",
    "/funds-individual/f-fund/",
    "/funds-lifecycle/l-2035/",
    "/tsp-basics/expenses-and-fees/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.tsp.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}