module.exports = {
  "site": "https://fdic.gov",
  "urls": [
    "/bank-examinations/trust-examination-manual",
    "/consumer-resource-center/2021-12/overdraft-and-account-fees",
    "/bank-financial-reports/ffiec-reports-condition-and-income-instructions-ffiec-031-and-041-report-0",
    "/quarterly-banking-profile/fdic-statistics-glance",
    "/help/advanced-search",
    "/formsdocuments",
    "/federal-deposit-insurance-act",
    "/resources/resolutions/bank-failures/in-brief/2024",
    "/banker-resource-center/monthly-list-banks-examined-cra-compliance-september-2025",
    "/bank-data-guide/data-downloads",
    "/consumer-resource-center/2025-06/bank-impersonation-scams-and-fake-banks",
    "/news/press-releases/2025",
    "/banker-resource-center/12-cfr-part-370-recordkeeping-timely-deposit-insurance-determination",
    "/banker-resource-center/community-reinvestment-act-cra",
    "/strategic-plans",
    "/asset-sales",
    "/news/speeches/2025/fdic-quarterly-banking-profile-first-quarter-2025",
    "/resources/deposit-insurance/deposit-insurance-fund",
    "/news/financial-institution-letters/2025/fdic-clarifies-process-banks-engage-crypto-related",
    "/asset-sales/loan-sales",
    "/news/financial-institution-letters/2025/revisions-consolidated-reports-condition-income-call",
    "/minority-depository-institutions-program/minority-depository-institutions-list",
    "/publications",
    "/news/press-releases/2025/federal-reserve-and-fdic-release-public-sections-resolution-plans-several",
    "/banker-resource-center/monthly-list-banks-examined-cra-compliance-52",
    "/consumer-resource-center/money-smart-news-kids",
    "/consumer-resource-center/money-smart-older-adults",
    "/news/press-releases/2025/agencies-issue-joint-statement-risk-management-considerations-crypto-asset",
    "/bank-examinations/consumer-compliance-supervisory-highlights",
    "/financial-institution-employees-guide-deposit-insurance/pass-through-deposit-insurance-coverage",
    "/resources/resolutions/bank-failures/failed-bank-list/first-republic.html",
    "/bank-examinations/bank-applications",
    "/news/press-releases/2025/fdic-proposes-regulatory-threshold-adjustments-and-indexing-reflect",
    "/accounting/current-expected-credit-losses-cecl",
    "/federal-register-publications/comments-rin-3064-ag15-july-28-2025",
    "/center-financial-research/working-papers",
    "/careers/impactful-careers-join-fdic-bank-examiner-program",
    "/news/financial-institution-letters/2025/customer-identification-program-rule-exemption-collecting",
    "/news/financial-institution-letters/2025/summary-deposits-survey-and-filing-june-30-2025",
    "/resolutions",
    "/about/website-policies",
    "/banker-resource-center/brokered-deposits",
    "/bank-failures/failed-bank-list/santa-anna-national-bank",
    "/quarterly-banking-profile/past-quarterly-banking-profiles",
    "/resources/resolutions/bank-failures/failed-bank-list/silicon-valley.html",
    "/espanol/glosario-de-terminos-financieros",
    "/history",
    "/forms-and-documents/bank-supervision-reports-notices",
    "/corporate-governance-and-auditing-programs/part-363-summary-filing-requirements",
    "/consumer-resource-center/2023-06/understanding-appraisals-and-why-they-matter"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://fdic.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}