module.exports = {
  "site": "https://www.fhfa.gov",
  "urls": [
    "/faqs/fannie-mae-and-freddie-mac-assistance-options-families-impacted-covid-19",
    "/data/dashboard/borrower-assistance-map",
    "/data/national-survey-mortgage-originations-nsmo-public-use-file/dataset",
    "/reports/annual-report-to-congress/2024",
    "/reports/house-price-index",
    "/regulation/federal-register/proposed-rulemaking/enterprise-regulatory-capital-framework",
    "/supervision/federal-home-loan-bank-system/districts",
    "/about/fhfa-policies/equal-employment-opportunity-no-fear-act",
    "/programs/affordable-housing/enterprise-housing-goals",
    "/public-input/enterprises-single-family-mortgage-pricing-framework",
    "/supervision/legal-documents",
    "/reports/stress-tests-report/2023",
    "/media",
    "/news/fact-sheet/2025-multifamily-loan-purchase-caps-for-fannie-mae-and-freddie-mac",
    "/policy/mortgage-servicing",
    "/reports/stress-tests-report/2024",
    "/data/hpi/focus-pieces",
    "/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2024",
    "/data/uad-appraisal-level-public-use-file-puf",
    "/news/news-release/fhfa-announces-release-of-historical-vantagescore-4.0-credit-scores-by-the-enterprises",
    "/news/news-release/fhfa-releases-data-visualization-dashboard-for-nmdb-outstanding-residential-mortgage-statistics",
    "/data/dashboard/enterprise-single-family-public-use-database",
    "/supervision/legal-documents/litigation",
    "/homeowners-and-homebuyers/mortgage-assistance/fraud-prevention-tips-and-resources",
    "/research/papers/wp2403",
    "/regulation/rulemaking",
    "/policy/non-performing-npl-and-re-performing-loan-rpl-sales",
    "/mortgage-translations/document/form-3044-texas-deed-of-trust",
    "/regulation/federal-register/final-rule/enterprise-regulatory-capital-framework-final-rule",
    "/about/foia-reading-room",
    "/reports/stress-tests-report/2025",
    "/supervision/legal-documents/opinions",
    "/reports/annual-report-to-congress",
    "/policy/credit-risk-transfer",
    "/programs/fhlbank-system-100",
    "/reports/foreclosure-prevention-refinance-and-fpm/2025/Q1",
    "/data/enterprise-housing-goals",
    "/supervision/fannie-mae-and-freddie-mac/capital-requirements",
    "/news/news-release/fhfa-announces-new-standard-short-sale-guidelines-for-fannie-mae-and-freddie-mac",
    "/mortgage-translations/document/form-3005-california-deed-of-trust",
    "/about/ombudsman",
    "/data/dashboard/uad-aggregate-statistics-dashboard-portal",
    "/about/foia-privacy",
    "/supervision/examiner-resources",
    "/news/news-release/fhfa-and-u.s.-treasury-announce-amendments-to-the-preferred-stock-purchase-agreements-pspas",
    "/mortgage-translations/document/form-3010-florida-mortgage",
    "/data/dashboard/enterprise-aus-quarterly-national-accept-rate-ratio",
    "/research/papers/wp1901",
    "/data/duty-to-serve/performance-data",
    "/sitemap"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.fhfa.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}