module.exports = {
  "site": "https://www.fhfa.gov",
  "urls": [
    "/programs/fhlbank-system-100/report-implementation",
    "/regulation/suspended-counterparty-program",
    "/",
    "/data/hpi/datasets",
    "/data/national-mortgage-database-aggregate-statistics",
    "/data/hpi",
    "/data/hpi/datasets",
    "/news/news-release/us-federal-housing-allows-fannie-freddie-approve-rocket-mr-cooper-acquisition",
    "/data/conforming-loan-limit",
    "/news/news-release",
    "/data/mirs",
    "/about/fannie-mae-freddie-mac",
    "/search/node",
    "/about/leadership/william-j-pulte",
    "/news",
    "/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2025",
    "/news/news-release/consistent-with-the-one-big-beautiful-bill-u.s.-federal-housing-expands-americas-affordable-housing-supply-in-rural-and-underserved-communities",
    "/data/dashboard/conforming-loan-limit-values-map",
    "/reports",
    "/policy/credit-scores",
    "/about",
    "/news/news-release/fhfa-house-price-indexr-down-0.2-percent-in-may-up-2.8-percent-from-last-year",
    "/news/news-release/u.s.-house-prices-rise-2.9-percent-year-over-year-unchanged-quarter-over-quarter",
    "/advisory-bulletin",
    "/data/dashboard/fhfa-hpi-top-100-metro-area-rankings",
    "/reports",
    "/regulation/federal-register",
    "/data/pudb",
    "/data/dashboard/nmdb-outstanding-residential-mortgage-statistics",
    "/data/datasets",
    "/data",
    "/data/dashboard",
    "/contact",
    "/about/careers",
    "/programs/national-mortgage-database-program",
    "/programs/fraud-prevention",
    "/data/market-data",
    "/supervision/federal-home-loan-bank-system",
    "/reports/foreclosure-prevention-refinance-and-fpm/2025/5",
    "/conservatorship/senior-preferred-stock-purchase-agreements",
    "/blog",
    "/supervision/dodd-frank-act-stress-tests",
    "/supervision/legal-documents/fhfa-orders",
    "/data/dashboard/fhfa-hpi-zip5-map",
    "/supervision/fannie-mae-and-freddie-mac",
    "/research",
    "/data/fair-lending-data",
    "/news/statement",
    "/programs/affordable-housing/affordable-housing-home-loan-banks",
    "/conservatorship"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.fhfa.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}