module.exports = {
  "site": "https://fdic.gov",
  "urls": [
    "/household-survey",
    "/bank-financial-reports/ffiec-reports-condition-and-income-instructions-ffiec-031-and-041-report-2",
    "/quarterly-banking-profile/quarterly-banking-profile-q1-2025",
    "/news/press-releases/2025/fdic-publishes-july-enforcement-actions",
    "/consumer-resource-center/five-things-know-about-safe-deposit-boxes-home-safes-and-your-valuables",
    "/news/press-releases/2025/statement-acting-chairman-travis-hill-executive-order-titled-guaranteeing",
    "/about/organization-directory-headquarters",
    "/asset-sales/bargain-properties",
    "/financial-institution-employees-guide-deposit-insurance/trust-accounts",
    "/about/organization-directory-regional-offices",
    "/laws-and-regulations/fdic-and-interagency-statements",
    "/federal-register-publications",
    "/about/board-directors-senior-executives",
    "/laws-and-regulations",
    "/consumer-resource-center/2025-08/preparing-your-finances-unanticipated-disaster",
    "/getbanked",
    "/news/speeches/2025/fdic-quarterly-banking-profile-second-quarter-2025",
    "/consumers/consumer/news/august2019.html",
    "/news/press-releases/2025/coleman-county-state-bank-coleman-tx-acquires-insured-deposits-santa-anna",
    "/bank-financial-reports",
    "/resolutions/fdic-and-financial-regulatory-reform-title-i-and-idi-resolution-planning",
    "/bank-examinations",
    "/news/financial-institution-letters/2023/fil23029.html",
    "/consumer-resource-center/2023-05/need-loan-your-new-small-business",
    "/banker-resource-center/fdic-examinations-scheduled-fourth-quarter-2025-all-regions",
    "/resources/deposit-insurance/financial-products-not-insured",
    "/consumer-resource-center/2020-10/beware-its-scam",
    "/careers/compensation",
    "/news/board-matters/2025/board-meeting-2025-07-15-1open",
    "/consumer-resource-center/2023-10/scammers-and-fake-banks",
    "/banker-resource-center/anti-money-laundering-countering-financing-terrorism-amlcft",
    "/deposit-insurance/questions-and-answers-related-fdics-part-328-final-rule",
    "/news/board-matters",
    "/bank-financial-reports/ffiec-reports-condition-and-income-instructions-ffiec-051-report-form-0",
    "/fdic-quarterly",
    "/bank-data-guide/banks",
    "/financial-institution-employees-guide-deposit-insurance/joint-accounts",
    "/consumer-compliance/unfair-deceptive-or-abusive-acts-or-practices",
    "/national-rates-and-rate-caps/national-rates-and-rate-caps-previous-rates",
    "/banker-resource-center/bank-secrecy-act-anti-money-laundering-bsaaml",
    "/regulations/applications/actions.html",
    "/bank-failures",
    "/resources/resolutions/bank-failures/in-brief/2025",
    "/news/press-releases/2021",
    "/consumer-resource-center/learn-money-smart",
    "/espanol",
    "/regulations/applications/rmsbankapp/result.html",
    "/consumer-resource-center/teach-money-smart",
    "/resources/resolutions/bank-failures/in-brief/index",
    "/consumer-resource-center/2021-10/avoiding-scams-and-scammers"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://fdic.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}