module.exports = {
  "site": "https://fdic.gov",
  "urls": [
    "/",
    "/bank-failures/failed-bank-list",
    "/news/press-releases",
    "/resources/deposit-insurance",
    "/fdic-search",
    "/resources/deposit-insurance/understanding-deposit-insurance",
    "/risk-management-manual-examination-policies",
    "/resources",
    "/news/financial-institution-letters",
    "/espanol/deposito",
    "/about",
    "/resources/deposit-insurance/financial-products-insured",
    "/national-rates-and-rate-caps",
    "/news",
    "/about/contact-fdic",
    "/news/board-matters/2025/board-meeting-2025-08-19-3notation",
    "/quarterly-banking-profile",
    "/consumer-resource-center/money-smart",
    "/resources/deposit-insurance/faq",
    "/bank-financial-reports/current-quarter-call-report-forms-instructions-and-related-materials",
    "/resources/data-tools",
    "/consumer-resource-center/money-smart-young-people",
    "/asset-sales/real-estate-and-property-sales",
    "/consumer-compliance-examination-manual",
    "/resources/deposit-insurance/brochures/insured-deposits",
    "/consumer-resource-center",
    "/news/financial-institution-letters/2025/update-fdics-consumer-compliance-examination-manual",
    "/analysis/bank-data-statistics",
    "/careers",
    "/resources/deposit-insurance/brochures/deposits-at-a-glance",
    "/news/financial-institution-letters/2025/fdic-supervisory-approach-regarding-use-pre-populated",
    "/banker-resource-center",
    "/analysis",
    "/laws-and-regulations/fdic-law-regulations-related-acts",
    "/bank-failures/obtaining-lien-release",
    "/consumer-resource-center/money-smart-adults",
    "/about/what-we-do",
    "/banker-resource-center/cra-examination-schedule-125",
    "/bank-failures/unclaimed-property-information-state",
    "/laws-and-regulations/2000-rules-and-regulations",
    "/bank-financial-reports/summary-deposits",
    "/quarterly-banking-profile/quarterly-banking-profile-q2-2025",
    "/deposit/deposits/prepaid.html",
    "/news/press-releases/2025/fdic-insured-institutions-reported-return-assets-113-percent-and-net",
    "/news/press-releases/2025/fdic-board-approves-proposal-amend-official-signs-and-advertising",
    "/consumer-resource-center/2020-12/how-find-long-lost-bank-account-or-safe-deposit-box",
    "/consumer-resource-center/consumer-complaint-process",
    "/news/financial-institution-letters/2025/notice-proposed-rulemaking-fdic-official-signs",
    "/news/speeches",
    "/consumer-resource-center/money-smart-young-adults"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://fdic.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}