module.exports = {
  "site": "https://www.tsp.gov",
  "urls": [
    "/funds-lifecycle/l-2050/",
    "/in-service-withdrawal-basics/financial-hardship/",
    "/tsp-basics/designating-beneficiaries/",
    "/tsp-basics/grow-with-the-tsp/",
    "/about-the-thrift-savings-plan-tsp/",
    "/access-your-account/protect-your-tsp-account/",
    "/tsp-basics/how-tsp-fits/",
    "/funds-individual/c-fund/",
    "/mobile/funds-individual/",
    "/planning-for-life-events/",
    "/mobile/making-contributions/contribution-limits/",
    "/withdrawals-in-retirement/historical-annuity-rates/",
    "/in-service-withdrawal-basics/in-service-withdrawal-types-and-terms/",
    "/mobile/access-your-account/",
    "/tsp-basics/update-your-mailing-address/",
    "/funds-lifecycle/l-2045/",
    "/changes-in-your-career/",
    "/funds-lifecycle/l-2055/",
    "/funds-lifecycle/l-income/",
    "/funds-individual/g-fund/",
    "/mobile/login/",
    "/signin/forgot-password/",
    "/planning-for-life-events/divorce-annulment-and-legal-separation/",
    "/funds-lifecycle/l-2030/",
    "/funds-lifecycle/l-2065/",
    "/funds-lifecycle/l-2060/",
    "/funds-individual/i-fund/",
    "/login/",
    "/mobile/making-contributions/contribution-limits/",
    "/investing-strategies/how-to-change-your-tsp-investments/",
    "/share-price-calculation/",
    "/funds-lifecycle/l-2070/",
    "/planning-for-life-events/buying-a-house/",
    "/funds-individual/s-fund/",
    "/in-service-withdrawal-basics/making-an-in-service-withdrawal/",
    "/mobile/news-and-resources/",
    "/planning-for-life-events/retirement-benefits-court-order/",
    "/mobile/tsp-loans/",
    "/contact-privacy/",
    "/bulletins/15-1/",
    "/funds-lifecycle/l-2040/",
    "/for-beneficiaries/beneficiary-distributions/",
    "/mobile/funds-lifecycle/",
    "/funds-lifecycle/l-2050/",
    "/mobile/contact/",
    "/news-and-resources/",
    "/agency-service-reps/tsp-educational-resources/",
    "/funds-individual/f-fund/",
    "/news-and-resources/secure-2-0-and-the-tsp/",
    "/funds-lifecycle/l-2035/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.tsp.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}