module.exports = {
  "site": "https://fmshrc.gov",
  "urls": [
    "/",
    "/decisions/alj",
    "/decisions/commission",
    "/rules/procedural-rules-29-cfr-part-2700",
    "/decisions",
    "/filter/tips",
    "/about",
    "/decisions/bluebook",
    "/about/news",
    "/guides/guide-commission-proceedings",
    "/content/federal-mine-safety-and-health-act-1977",
    "/content/frequently-asked-questions",
    "/about/commissioners",
    "/meetings-arguments/meetings",
    "/content/administrative-law-judges",
    "/meetings-arguments/arguments",
    "/sp",
    "/equal-access-justice-act",
    "/content/mine-act-procedural-rules",
    "/content/cases-currently-review-commission-2",
    "/content/chairman-and-commissioner-tenure",
    "/content/section-105c3-complaints",
    "/guides",
    "/rules/privacy-act",
    "/content/commission-decisions-appeal-0",
    "/guides/how-case-proceeds-commission",
    "/guides/instructions-electronic-filing",
    "/content/cases-review",
    "/content/tty-based-telecommunications-relay-services-trs",
    "/content/contact-us",
    "/meetings-arguments",
    "/eeo-policies",
    "/rules/foia",
    "/content/freedom-information-act-foia",
    "/reports-budget-submissions/performance-accountability-reports",
    "/plans/strategic-plans",
    "/content/fmshrc-privacy-policy",
    "/rules/part-2701-government-sunshine-act-regulations",
    "/content/requests-reopen",
    "/resources",
    "/reports-budget-submissions/perf-reports",
    "/documents/motions-approve-settlement",
    "/documents/contingency-plan",
    "/guides/foia-guide",
    "/content/accessibility",
    "/content/reports-budget-submissions",
    "/rules/non-discrimination",
    "/documents/supplemental-standards-ethical-conduct-employees-commission",
    "/reports-budget-submissions/Reports%20to%20Congress",
    "/content/vulnerability-disclosure-policy"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://fmshrc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}