module.exports = {
  "site": "https://fmshrc.gov",
  "urls": [
    "/about/news/greenbrier-minerals-llc",
    "/decisions/alj/02272025/secretary-labor-v-gentry-mountain-mining-llc",
    "/decisions/alj/07082025/secretary-labor-v-peabody-southeast-mining-llc",
    "/node",
    "/decisions/alj/05302025/secretary-labor-obo-brek-pinkerton-v-rmc-mining-development-llc-et-al",
    "/arguments/argument_2019-11-21",
    "/reports/performance-and-accountability-report-fiscal-year-2024",
    "/decisions/commission/08112025/secretary-labor-v-drake-cement-llc",
    "/decisions/alj/07312025/secretary-labor-v-warrior-met-coal-mining-llc",
    "/node/5513203",
    "/bios/commissioner/mary-lu-jordan",
    "/decisions/alj/05212025/secretary-labor-obo-guillermo-ortiz-v-kilauea-crushers",
    "/arguments/argument_2025-07-31",
    "/decisions/alj/06182025/wanda-palo-v-united-states-steel-corporation",
    "/decisions/alj/03202025/american-tripoli-v-secretary-labor-and-secretary-labor-v-american-tripoli",
    "/about/news/fy-2025-lapse-appropriations-contingency-plan",
    "/plans/fy2026-justification",
    "/about/news/geneva-rock-products",
    "/meetings/meeting_2024-05-14",
    "/meetings/meeting_2025-07-09",
    "/meetings/meeting_2025-07-24",
    "/plans/fy2017-justification",
    "/plans/fy2023-justification",
    "/reports/performance-and-accountability-report-fiscal-year-2014",
    "/reports/performance-and-accountability-report-fiscal-year-2018",
    "/reports/performance-and-accountability-report-fiscal-year-2023",
    "/decisions/commission/07012025/secretary-labor-v-mdi-mining",
    "/decisions/alj/06262025/secretary-labor-v-peabody-southeast-mining-llc-0",
    "/decisions/alj/06262025/secretary-labor-v-rain-rent",
    "/about/news/commission-extends-comment-period-revised-procedural-rules",
    "/reports/buy-american-report-2005",
    "/plans/fy2025-justification",
    "/mines/0503515",
    "/reports/performance-and-accountability-report-fiscal-year-2013",
    "/reports/performance-and-accountability-report-fiscal-year-2015",
    "/reports/performance-and-accountability-report-fiscal-year-2016",
    "/reports/performance-and-accountability-report-fiscal-year-2017",
    "/reports/performance-and-accountability-report-fiscal-year-2019",
    "/reports/performance-and-accountability-report-fiscal-year-2020",
    "/reports/performance-and-accountability-report-fiscal-year-2022",
    "/meetings/meeting_2025-06-24-0",
    "/decisions/commission/08112025/secretary-labor-v-sg-excavating-inc",
    "/arguments/argument_2019-07-16",
    "/decisions/commission/06062025/secretary-labor-v-wayne-j-sand-gravel-inc",
    "/reports/buy-american-report-2007",
    "/reports/buy-american-report-2009",
    "/reports/buy-american-report-2011",
    "/plans/fy2018-justification",
    "/plans/fy2019-justification",
    "/plans/fy2020-justification"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://fmshrc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}