module.exports = {
  "site": "https://fmshrc.gov",
  "urls": [
    "/foia/reports",
    "/content/digital-analytics-program",
    "/content/foia-library",
    "/foia/foia-request-form",
    "/offices/satellite-office/pittsburgh-pa",
    "/content/reasonable-accommodation-procedures-individuals-disabilities",
    "/guides/request-view-official-file",
    "/documents/no-fear-act-notice",
    "/content/report-sbrefa-compliance-under-eo-13892",
    "/about/news/revised-procedural-rules",
    "/about/news/genesis-alkali-llc",
    "/content/language-translation-services",
    "/decisions/alj/08012025/secretary-labor-v-consol-mining-company-llc",
    "/decisions/commission/08122025/secretary-labor-v-ohio-county-coal-resources-inc",
    "/content/section-508",
    "/bios/commissioner/timothy-j-baker",
    "/guides/videoconference-hearings",
    "/content/foia-public-liaison",
    "/decisions/commission/07282025/secretary-labor-v-nelson-quarries-inc",
    "/about/news/wesley-mallery-v-el-segundo-coal-company-llc",
    "/foia/foia-references-0",
    "/content/proposed-foia-rules",
    "/decisions/alj/08202025/secretary-labor-v-iron-mountain-quarry-llc",
    "/about/news/bluestone-oil-corporation",
    "/about/buy-american",
    "/about/news/county-line-stone-co",
    "/reports-budget-submissions/Sustainability%20Report",
    "/arguments/argument_2019-06-04",
    "/arguments/argument_2024-09-19",
    "/meetings/meeting_2024-09-24",
    "/arguments/argument_2019-06-12",
    "/arguments/argument_2019-09-18",
    "/decisions/alj/03142025/secretary-labor-v-certified-crane-and-rigging-services-llc",
    "/meetings/meeting_2024-05-14-0",
    "/decisions/commission/07012025/secretary-labor-v-north-american-mining-company",
    "/decisions/alj/07152025/secretary-labor-obo-caesar-miranda-v-dixon-rock-and-materials-llc",
    "/decisions/commission/07312025/secretary-labor-v-argos-puerto-rico-corp",
    "/decisions/alj/04032025/secretary-labor-v-consol-mining-company-llc",
    "/decisions/alj/06262025/secretary-labor-v-peabody-southeast-mining-llc",
    "/offices/satellite-office/denver-co",
    "/bios/commissioner/moshe-z-marvit",
    "/decisions/alj/02252025/secretary-labor-obo-shaun-chapman-v-buchanan-minerals-llc",
    "/decisions/commission/09062024/secretary-labor-v-fci-sand-operations-llc",
    "/decisions/commission/08122025/secretary-labor-v-prospect-mining-development-company-llc",
    "/meetings-arguments/meetings/archive/2017",
    "/meetings-arguments/meetings/archive/2019",
    "/meetings/meeting_2025-07-31",
    "/decisions/alj/07302025/secretary-labor-v-morton-salt-inc-2",
    "/about/news/commission-publishes-revisions-its-procedural-rules",
    "/offices/headquarter/washington-dc"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://fmshrc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}