module.exports = {
  "site": "https://consumer.ftc.gov",
  "urls": [
    "/one-ring-cell-phone-scam-can-ding-your-wallet",
    "/one-ring-cell-phone-scam-can-ding-your-wallet",
    "/articles/free-credit-reports",
    "/features/how-avoid-imposter-scams",
    "/",
    "/articles/national-do-not-call-registry-faqs",
    "/consumer-alerts/2024/10/how-order-free-covid-test-kits-federal-government-avoid-scammers",
    "/identity-theft-and-online-security/identity-theft",
    "/scams",
    "/articles/what-do-if-you-were-scammed",
    "/features/how-stop-unwanted-calls",
    "/articles/credit-freeze-or-fraud-alert-whats-right-your-credit-report",
    "/consumer-alerts/2025/08/five-ways-help-you-cut-down-unwanted-calls",
    "/consumer-alerts/2024/10/how-order-free-covid-test-kits-federal-government-avoid-scammers",
    "/consumer-alerts/2022/10/how-recognize-fake-geek-squad-renewal-scam",
    "/how-block-unwanted-calls",
    "/consumer-alerts/2018/12/what-social-security-scam-sounds",
    "/articles/how-get-out-debt",
    "/consumer-alerts",
    "/how-block-unwanted-calls",
    "/articles/phone-scams",
    "/articles/how-recognize-report-spam-text-messages",
    "/consumer-alerts/2025/07/are-you-really-out-cloud-storage-or-message-scam",
    "/articles/how-recognize-report-spam-text-messages",
    "/consumer-alerts/2025/01/got-package-you-didnt-order-its-probably-scam",
    "/articles/how-recognize-avoid-phishing-scams",
    "/identity-theft-and-online-security/online-privacy-and-security",
    "/features/we-dont-serve-teens",
    "/sample-customer-complaint-letter",
    "/consumer-alerts/2025/08/social-media-trend-thats-actually-bank-fraud",
    "/how-stop-junk-mail",
    "/articles/how-recognize-avoid-phishing-scams",
    "/consumer-alerts/2016/05/scammers-can-fake-caller-id-info",
    "/articles/how-protect-your-phone-hackers",
    "/sample-customer-complaint-letter",
    "/how-stop-junk-mail",
    "/consumer-alerts/2024/08/home-title-lock-insurance-not-lock-all",
    "/consumer-alerts/2015/03/its-irs-callingor-it",
    "/articles/how-spot-avoid-report-fake-check-scams",
    "/consumer-alerts/2024/08/hang-unwanted-calls-about-loans",
    "/features/used-cars",
    "/debt-collection-faqs",
    "/articles/prescreened-credit-insurance-offers",
    "/articles/what-know-about-romance-scams",
    "/search/site-cfg",
    "/articles/what-know-about-cryptocurrency-scams",
    "/debt-collection-faqs",
    "/consumer-alerts/2025/07/scammy-texts-offering-refunds-amazon-purchases",
    "/articles/how-get-less-spam-your-email",
    "/consumer-alerts/2024/11/random-text-offering-you-job-its-probably-scam",
    "/articles/job-scams",
    "/articles/what-know-about-cryptocurrency-scams",
    "/articles/multi-level-marketing-businesses-pyramid-schemes",
    "/articles/what-know-about-identity-theft",
    "/how-recover-your-hacked-email-or-social-media-account",
    "/articles/reverse-mortgages",
    "/consumer-alerts/2025/08/business-and-government-impersonators-go-after-older-adults-life-savings",
    "/consumer-alerts/2025/07/text-about-overdue-traffic-ticket-probably-scam",
    "/disputing-errors-your-credit-reports",
    "/unwanted-calls-emails-texts",
    "/home-equity-loans-home-equity-lines-credit",
    "/avoiding-reporting-gift-card-scams",
    "/disputing-errors-your-credit-reports",
    "/articles/using-credit-cards-and-disputing-charges",
    "/consumer-alerts/2020/02/text-message-about-your-fedex-package-really-scam",
    "/consumer-alerts/2025/08/social-media-ad-super-low-prices-well-known-brands-could-be-scam",
    "/consumer-alerts/2025/08/la-fitness-made-it-difficult-people-cancel-gym-memberships-ftc-says",
    "/how-recover-your-hacked-email-or-social-media-account",
    "/avoiding-reporting-gift-card-scams",
    "/identity-theft-online-security",
    "/consumer-alerts/2017/08/phantom-debt-collectors-impersonate-law-firms",
    "/consumer-alerts/2025/08/when-investment-fraud-happens-familiar-places",
    "/consumer-alerts/2025/08/how-spot-avoid-task-scams",
    "/nonconsensual-distribution-intimate-images-what-know"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://consumer.ftc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 148,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}