module.exports = {
  "site": "https://www.fhfa.gov",
  "urls": [
    "/data/hpi/summary-tables",
    "/data/hpi/summary-tables",
    "/programs/duty-to-serve",
    "/faqs/hpi",
    "/data/dashboard/fhfa-hpi-four-quarter-appreciations",
    "/data/duty-to-serve/eligibility-data",
    "/programs/loss-mitigation",
    "/policy",
    "/programs/affordable-housing",
    "/public-input/tenant-protections",
    "/mortgage-translations",
    "/data/dashboard/fhfa-hpi-county-map",
    "/supervision/legal-documents/fhfa-orders/stress-testing-orders",
    "/conservatorship/history",
    "/data/dashboard/nmdb-new-residential-mortgage-statistics",
    "/news/news-release/william-j.-pulte-sworn-in-as-5th-director-of-u.s.-federal-housing-fhfa",
    "/data/fhlb-membership",
    "/blog/insights/who-lives-in-rural-america",
    "/data/dashboard/nmdb-residential-mortgage-performance-statistics",
    "/contact/general",
    "/policy/guarantee-fees",
    "/news/speech",
    "/supervision/federal-home-loan-bank-system/about",
    "/reports/house-price-index/2025/2",
    "/about/careers/student-and-recent-graduates",
    "/news/news-release/fhfa-eliminates-adverse-market-refinance-fee",
    "/reports/house-price-index/2025/7",
    "/news/fact-sheet",
    "/data/underserved-areas-data",
    "/news/news-release/fannie-mae-fires-over-100-employees-for-unethical-conduct-including-the-facilitation-of-fraud",
    "/faqs/hpi",
    "/data/national-survey-mortgage-originations-nsmo-public-use-file",
    "/supervision/legal-documents/regulatory-interpretations",
    "/data/dashboard/enterprise-aus-quarterly-national-accept-rate",
    "/advisory-bulletin/rescinded",
    "/policy/fannie-mae-freddie-mac-affordable-housing-allocations",
    "/public-input",
    "/regulation/federal-register/proposed-rulemaking/repeal-of-fair-lending-fair-housing-and-equitable-housing-finance-plans-regulation-proposed-rule",
    "/news/testimony",
    "/about/fhfa-policies",
    "/mortgage-translations/search",
    "/policy/executive-compensation",
    "/reports/house-price-index/2025/Q1",
    "/news/news-release/fhfa-finalizes-2025-2027-housing-goals-for-fannie-mae-and-freddie-mac",
    "/data/uniform-appraisal-dataset-aggregate-statistics",
    "/regulation/federal-register/proposed-rulemaking/members-of-federal-home-loan-banks",
    "/about/budget-finances-and-performance",
    "/news/news-release/u.s.-house-prices-rise-4.0-percent-over-the-prior-year-up-0.7-percent-from-the-fourth-quarter-of-2024",
    "/news/news-release/fhfa-announces-conforming-loan-limit-values-for-2023",
    "/programs/modified-underserved-markets-plans"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.fhfa.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}