module.exports = {
  "site": "https://www.fmc.gov",
  "urls": [
    "/",
    "/licensing-and-certification/",
    "/databases-and-publications/",
    "/about/",
    "/proceedings/",
    "/complaints-and-assistance/",
    "/licensing-and-certification/ocean-transportation-intermediary-license-status-changes/",
    "/licensing-and-certification/apply-for-a-license-or-request-a-foreign-registration/",
    "/complaints-and-assistance/forms-and-applications/",
    "/news-and-advisories/",
    "/articles/",
    "/articles/fmc-publishes-final-rule-on-detention-and-demurrage-billing-practices/",
    "/articles/fmc-grants-chipolbroks-petition-for-an-exemption-under-46-u-s-c-%C2%A7-40703-subject-to-conditions/",
    "/about/bureaus-offices/bureau-of-enforcement-investigations-and-compliance-beic/office-of-compliance/ocean-transportation-intermediaries/",
    "/about/bureaus-offices/",
    "/complaints-and-assistance/summary-of-fees/",
    "/licensing-and-certification/non-compliant-nvoccs/",
    "/articles/federal-maritime-commission-begins-publishing-carrier-submitted-containerized-freight-statistics-data/",
    "/ocean-shipping-reform-act-of-2022-implementation/",
    "/licensing-and-certification/bond-program-information-for-otis/",
    "/complaints-and-assistance/cruise-service-issues/",
    "/complaints-and-assistance/filing-a-formal-complaint/",
    "/licensing-and-certification/foreign-oti-registration-status-changes/",
    "/articles/fmc-investigating-flagging-practices/",
    "/ocean-shipping-reform-act-of-2022-implementation/guidance-on-charge-complaint-interim-procedure/",
    "/databases-and-publications/containerized-freight-statistics/",
    "/about/strategies-budgets-and-performance/annual-reports/",
    "/about/bureaus-offices/consumer-affairs-dispute-resolution-services/",
    "/articles/testimony-of-commissioner-dye-before-congress-future-of-united-states-maritime-part-1-review-of-fiscal-year-2026-federal-maritime-commission-budget-request/",
    "/about/bureaus-offices/bureau-of-certification-and-licensing/",
    "/filing-a-small-claims-complaint/",
    "/licensing-and-certification/guidance-on-license-renewals/",
    "/about/organizational-chart/",
    "/about/commissioner-archive/louis-e-sola/",
    "/about/bureaus-offices/consumer-affairs-dispute-resolution-services/shipping-your-vehicle-overseas/",
    "/oti-update/august-11-2025-ocean-transportation-intermediary-license-applicants/",
    "/about/commissioner-archive/rebecca-f-dye/",
    "/about/commissioner-archive/daniel-b-maffei/",
    "/databases-and-publications/controlled-carrier-list/",
    "/oti-update/august-4-2025-ocean-transportation-intermediary-license-applicants/",
    "/licensing-and-certification/vessel-operating-common-carriers/",
    "/articles/fmc-launching-examination-of-global-maritime-chokepoints/",
    "/about/fmc-history/",
    "/complaints-and-assistance/how-to-file-service-contracts/",
    "/about/commissioner-archive/",
    "/oti-update/august-18-2025-ocean-transportation-intermediary-license-applicants/",
    "/about/bureaus-offices/bureau-of-enforcement-investigations-and-compliance-beic/",
    "/detention-and-demurrage/",
    "/marine-terminal-operators/",
    "/about/bureaus-offices/bureau-of-trade-analysis-bta/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.fmc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}