module.exports = {
  "site": "https://www.fmc.gov",
  "urls": [
    "/about/commissioner-archive/max-vekich/",
    "/complaints-and-assistance/filing-a-formal-complaint/instructions-for-drafting-a-shipping-act-complaint/",
    "/about/bureaus-offices/office-of-the-secretary/",
    "/oti-update/august-25-2025-ocean-transportation-intermediary-license-applicants/",
    "/complaints-and-assistance/filing-a-shipping-complaint/",
    "/about/bureaus-offices/office-of-the-managing-director/",
    "/articles/april-2025-activity-report/",
    "/articles/industry-advisory-requirements-for-doing-business-with-nvoccs-and-offs-2/",
    "/articles/premier-alliance-agreement-taking-effect/",
    "/articles/statement-of-chairman-louis-e-sola/",
    "/about/strategies-budgets-and-performance/performance-and-accountability-reports/",
    "/about/bureaus-offices/inspector-general/",
    "/articles/final-rule-on-demurrage-detention-cleared-to-take-full-effect-may-28/",
    "/ftdo/statement-of-chairman-louis-e-sola-to-the-senate-committee-on-commerce-science-and-transportation-fees-and-foreign-influence-examining-the-panama-canal-and-its-impact-on-u-s-trade-and-n/",
    "/complaints-and-assistance/fmc-proceedings-and-reports/",
    "/about/bureaus-offices/office-of-the-general-counsel-ogc/",
    "/oti-update/july-21-2025-ocean-transportation-intermediary-license-applicants/",
    "/databases-and-publications/maritime-transportation-data-initiative/",
    "/oti-update/july-28-2025-ocean-transportation-intermediary-license-applicants/",
    "/articles/fmc-awards-gold-medal-to-chairman-louis-e-sola-for-exceptional-leadership/",
    "/about/bureaus-offices/office-of-the-general-counsel-ogc/how-to-file-carrier-mto-agreements/",
    "/complaints-and-assistance/resources-for-attorneys-and-litigants/",
    "/about/national-shipper-advisory-committee-nsac/",
    "/articles/fmc-systems-notice/",
    "/articles/fmc-system-maintenance-scheduled-for-friday-april-25-2025/",
    "/oti-update/july-7-2025-ocean-transportation-intermediary-license-applicants/",
    "/articles/florida-nvocc-agrees-to-pay-civil-penalties-and-conduct-ongoing-self-financed-monitoring/",
    "/licensing-and-certification/passenger-vessel-operators/",
    "/articles/compromise-agreements-yield-over-2-3-million-in-penalties-changes-to-business-practices/",
    "/oti-update/june-30-2025-ocean-transportation-intermediary-license-applicants/",
    "/office-of-the-chairman/",
    "/about/meeting-schedule/",
    "/complaints-and-assistance/cargo-shipment-assistance/",
    "/news-and-advisories/news/",
    "/oti-update/july-14-2025-ocean-transportation-intermediary-license-applicants/",
    "/articles/federal-maritime-commission-publishes-update-of-its-official-case-law-reporter/",
    "/about/bureaus-offices/office-of-administrative-law-judges-alj/",
    "/ftdo/commissioner-vekich-addressed-the-national-defense-transportation-association/",
    "/articles/fmc-adds-prc-based-chipolbrok-to-controlled-carrier-list/",
    "/licensing-and-certification/guidance-on-foreign-based-registered-nvocc-renewals/",
    "/licensing-and-certification/information-for-truckers-on-claims-against-nvocc-bonds/",
    "/complaints-and-assistance/cruise-service-issues/how-to-obtain-a-refund-from-a-cruise-line/",
    "/oti-update/september-2-2025-ocean-transportation-intermediary-license-applicants/",
    "/about/bureaus-offices/office-of-equal-employment-opportunity-oeeo/equal-employment-opportunity-rights-statistics/",
    "/articles/fmc-february-2025-activity-report/",
    "/articles/fmc-moving-quickly-in-implementing-osra-2022/",
    "/proceedings/historical-federal-maritime-commission-reports/",
    "/articles/industry-advisory-requiring-no-cost-access-to-tariff-publication-systems/",
    "/ftdo/statement-of-chairman-louis-e-sola-on-the-imo-decarbonization/",
    "/about/strategies-budgets-and-performance/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.fmc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}