module.exports = {
  "site": "https://www.hud.gov",
  "urls": [
    "/",
    "/helping-americans/housing-choice-vouchers-tenants",
    "/contactus/public-housing-contacts",
    "/reac",
    "/helping-americans",
    "/helping-americans/homes-for-sale",
    "/hud-partners",
    "/hudclips/handbooks/housing",
    "/contactus",
    "/hud-partners/single-family-handbook-4000-1",
    "/helping-americans/public-housing",
    "/helping-americans/housing-choice-vouchers",
    "/helping-americans/housing-choice-vouchers-emergency",
    "/contactus/local",
    "/fha",
    "/states",
    "/hud-partners/limited-denial",
    "/reporthousingdiscrimination",
    "/hud-partners/single-family-lender-list",
    "/hud-partners/grants-info-funding-opps",
    "/helping-americans/buying-a-home",
    "/helping-americans/loans",
    "/helping-americans/housing-choice-vouchers-homeless-veterans",
    "/hudclips/forms",
    "/vawa",
    "/helping-americans/assistance-animals",
    "/helping-americans/good-neighbor",
    "/helping-americans/public-indian-housing-hcv-homeownership",
    "/opportunity-zones",
    "/researchers",
    "/states/florida",
    "/hudclips",
    "/states/california",
    "/helping-americans/fair-housing-act-overview",
    "/news",
    "/hud-partners/multifamily-programs",
    "/helping-americans/public-indian-housing",
    "/reac/nspire-standards",
    "/helping-americans/public-housing-programs",
    "/hud-partners/multifamily-grants-section811ptl",
    "/helping-americans/housing-choice-vouchers-project",
    "/hud-partners/multifamily-housing-for-seniors-and-persons-with-disabilities",
    "/reac/nspire",
    "/helping-americans/home-improvements",
    "/helping-americans/mf-properties-list",
    "/helping-americans/avoiding-foreclosure",
    "/hudclips/letters/mortgagee",
    "/aboutus",
    "/hud-partners/single-family-hecmhome",
    "/section184"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.hud.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}