module.exports = {
  "site": "https://www.hud.gov",
  "urls": [
    "/contactus/healthy-homes",
    "/states/texas",
    "/subscribe/mailinglist",
    "/findshelter",
    "/hud-partners/housing-national-agencies",
    "/helping-americans/housing-choice-vouchers-landlord",
    "/helping-americans/seniors",
    "/hud-partners/electronic-data-interchange",
    "/hud-partners/single-family-203k",
    "/hud-partners/single-family-fixing-home",
    "/hud-partners/single-family-mortgage-programs-203k",
    "/hudclips/handbooks/housing-4350-3",
    "/hudclips/notices/pih",
    "/reac/",
    "/states/ohio",
    "/hud-partners/single-family-title",
    "/hud-partners/multifamily-property-search",
    "/stat/sfh/housing-counseling",
    "/hud-partners/community-cdbg",
    "/hud-partners/single-family-fha-info",
    "/hud-partners/fair-housing-system-hems",
    "/states/north-carolina",
    "/hud-partners/community-coc",
    "/states/illinois",
    "/contactus/multifamily-housing-complaint",
    "/contactus/css",
    "/hudprograms",
    "/hudclips/sfhsuperseded",
    "/contactus/file-complaint-submitted",
    "/states/pennsylvania",
    "/hud-partners/single-family-finance-manuf",
    "/states/georgia",
    "/hud-partners/multifamily-regions",
    "/hud-partners/grants",
    "/hud-partners/single-family-fha-resource-center",
    "/helping-americans/public-indian-housing-mainstream-vouchers",
    "/hud-partners/manufactured-home-labels",
    "/states/new-jersey",
    "/states/new-york",
    "/hud-partners/single-family-national-service-center",
    "/siteindex",
    "/contactus/file-complaint",
    "/helping-americans/fha-loss-mitigation",
    "/states/tennessee",
    "/faqs",
    "/helping-americans/public-indian-housing-systems-pic",
    "/helping-americans/housing-choice-vouchers-landlord-forms",
    "/helping-americans/mortgage-servicing-contractors",
    "/states/michigan",
    "/aboutus/leadership/scott-turner"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.hud.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}