module.exports = {
  "site": "https://www.dfc.gov",
  "urls": [
    "/",
    "/who-we-are/our-people/board-directors",
    "/who-we-are/our-people/executive-staff",
    "/who-we-are/about-us",
    "/media/newsroom",
    "/what-we-do/active-projects",
    "/who-we-are/careers",
    "/what-we-do/our-work",
    "/search",
    "/media/reports/archived",
    "/who-we-are/conor-coleman",
    "/what-we-offer/our-products/debt-financing",
    "/media/press-releases/dfc-approves-new-investments-promote-us-foreign-policy-objectives",
    "/what-we-offer/work-with-us/eligibility-checklist",
    "/what-we-offer/our-products/equity-investments",
    "/what-we-offer/our-products/investment-funds",
    "/what-we-offer/work-with-us/where-we-work",
    "/our-work/infrastructure-and-critical-minerals",
    "/apply",
    "/who-we-are/dev-jagadesan",
    "/what-we-offer/our-products/project-development",
    "/what-we-offer/our-products/political-risk-insurance",
    "/our-impact/reports",
    "/our-impact/transaction-data",
    "/eligibility/where-we-work/places-dfc-unable-to-provide-support",
    "/who-we-are/contact",
    "/media/in-the-press",
    "/who-we-are/our-people/development-advisory-council",
    "/our-work/sub-saharan-africa",
    "/media/press-releases/dfc-announces-strategic-investment-stabilize-and-expand-food-security-africa",
    "/what-we-do/investment-stories",
    "/what-we-offer-our-products-debt-financing/financing-terms-and-processes",
    "/what-we-offer/our-products",
    "/who-we-are-our-people-board-directors/board-resolutions",
    "/what-we-offer-eligibility-our-investment-policies/environmental-and-social-impact-assessments",
    "/media/press-releases/dfc-announces-investments-supporting-development-along-lobito-corridor",
    "/media/newsroom/archive/2017-2021",
    "/oig",
    "/what-we-do/investment-stories",
    "/who-we-are/careers/students",
    "/our-work/small-business-and-financial-services",
    "/who-we-are/bethany-aquilina-brez",
    "/our-work/energy",
    "/our-impact/transparency",
    "/investment-story/strengthening-critical-mineral-supply-chains-countering-chinas-dominance",
    "/what-we-offer/work-with-us/investment-policies",
    "/our-work/food-security-and-agriculture",
    "/what-we-offer/work-with-us",
    "/our-impact/approach-to-impact",
    "/who-we-are/robert-stebbins"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.dfc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}