module.exports = {
  "site": "https://www.dfc.gov",
  "urls": [
    "/media/press-releases/dfc-commits-250-million-strengthen-food-security-ukraine",
    "/media/press-releases/dfcs-global-portfolio-surpasses-40-billion-across-more-100-countries",
    "/investment-story/expanding-natural-gas-processing-capacity-iraq",
    "/media/press-releases/ifc-ebrd-dfc-help-bolster-ukrainian-agribusiness-sector-strengthen-global-food",
    "/media/press-releases/ceo-nathan-underscores-dfc-commitment-financing-international-challenges",
    "/media/press-releases/dfc-announces-surge-financing-initiative-and-strategic-investments-bolster",
    "/media/press-releases/dfc-approves-23-transactions-totaling-more-722-million-across-priority-sectors",
    "/media/press-releases/dfc-ceo-dominican-republic-announces-200-million-loan-intention-open-new",
    "/media/press-releases/dfc-and-idb-invest-partner-tembici-scale-urban-electric-bike-sharing-services",
    "/media/press-releases/dfc-and-shell-foundation-sign-mou-expansion-support-distributed-renewable",
    "/media/press-releases/ceo-nathan-ukraine-recovery-conference-announces-several-new-initiatives",
    "/media/press-releases/dfc-advances-collaboration-private-sector-and-government-partners-during-world",
    "/who-we-are/careers/environmental-economic-social-impact",
    "/media/press-releases/dfc-commits-50-million-expand-financing-iraqi-entrepreneurs",
    "/media/press-releases/dfc-reaffirms-commitment-scaling-investment-african-infrastructure-and",
    "/media/press-releases/dfc-underscores-commitment-catalyze-private-sector-investment-clean-energy-and",
    "/media/press-releases/dfc-and-brazilian-development-bank-bndes-sign-framework-co-invest-critical",
    "/media/press-releases/dfc-announces-50-million-financing-acba-bank-provide-support-small-businesses",
    "/media/press-releases/larry-sacks-named-dfcs-new-chief-development-officer",
    "/media/press-releases/readout-dfc-ceo-and-head-delegation-nathans-engagement-us-africa-business",
    "/media/press-releases/dfc-announces-support-energy-and-health-projects-india",
    "/media/press-releases/dfc-delivers-us-climate-finance-commitments-cop28-announces-more-37-billion",
    "/media/press-releases/dfc-provides-610-million-political-risk-insurance-innovative-debt-conversion",
    "/oig/hotline",
    "/media/press-releases/dceo-biswal-underscores-us-commitment-supporting-democracy-and-economic",
    "/media/press-releases/dfc-ceo-nathan-meets-president-angola-joao-lourenco-discuss-opportunities",
    "/media/press-releases/dfc-ceo-travels-ghana-strengthen-global-infrastructure-and-grow-economic",
    "/media/press-releases/dfc-and-idb-invest-establish-americas-partnership-platform",
    "/media/press-releases/dfc-and-vikram-solar-sign-ceremonial-retainer-letter-200-million-funding-cop28",
    "/investment-story/helping-american-it-business-expand-sub-saharan-africa",
    "/media/press-releases/dfc-announces-initiatives-expand-us-investment-and-development-morocco",
    "/media/press-releases/dfc-announces-more-25-billion-investments-un-general-assembly",
    "/media/press-releases/dfc-ceo-nathan-leads-presidential-delegation-drc",
    "/media/press-releases/dfc-ceo-scott-nathan-travels-jamaica-deepen-economic-relationship",
    "/equal-employment-opportunity",
    "/who-we-are/naga-jujjavarapu",
    "/media/press-releases/european-development-finance-institutions-sign-landmark-separate-affiliate",
    "/media/press-releases/advancing-indo-pacific-economic-cooperation-dfc-jbic-and-korea-eximbank-sign",
    "/media/press-releases/dfc-accelerates-engagement-caribbean-appeal-new-and-existing-partners",
    "/media/press-releases/dfc-announces-42-million-guaranty-dominican-republics-banreservas-plans-open",
    "/media/press-releases/dfc-ceo-scott-nathan-travels-moldova-expand-economic-partnership",
    "/media/press-releases/dfc-invests-more-1-billion-global-food-security-announces-intent-double-its",
    "/media/press-releases/dfc-renews-cooperation-jbic-drive-sustainable-economic-growth-indo-pacific-and",
    "/investment-story/strengthening-pharmaceutical-supply-chains-pakistan",
    "/media/press-releases/dfc-ceo-nathan-travels-ecuador-dfcs-largest-market-western-hemisphere",
    "/media/press-releases/quad-dfis-meet-advance-financing-health-energy-and-infrastructure-indo-pacific",
    "/who-we-are/amanda-m-burke",
    "/media/press-releases/ceo-nathan-brazil-open-latin-america-regional-office-and-bolster-investments",
    "/who-we-are/careers/current-former-federal-employees"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.dfc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}