module.exports = {
  "site": "https://www.dfc.gov",
  "urls": [
    "/media/press-releases/dfc-announces-nearly-4-billion-new-climate-finance-commitments-cop29",
    "/who-we-are/irving-w-bailey-ii",
    "/investment-story/strengthening-global-supply-chains-and-countering-chinas-influence-modernized-port",
    "/who-we-are/development-accountability-council-dac/rob-mosbacher-jr",
    "/media/press-releases/dfc-announces-new-us-financing-africas-lobito-corridor",
    "/media/press-releases/dfc-celebrates-nearly-4-billion-new-investments-approved-start-fiscal-year",
    "/investment-story/improving-farm-productivity-india-digital-solutions",
    "/media/press-releases/dfc-opens-office-dominican-republic",
    "/media/press-releases/dfcs-approval-300-million-financing-sustainable-infrastructure-projects",
    "/investment-story/supporting-resilient-telecommunications-infrastructure-south-pacific",
    "/media/press-releases/dfc-announces-70-million-new-investments-india-advance-shared-priorities",
    "/who-we-are/careers/faqs",
    "/media/press-releases/dfc-commits-half-billion-dollars-port-infrastructure-colombo-sri-lanka",
    "/media/press-releases/dfc-commits-125-million-modernize-elefsina-shipyard-greece-establish-critical",
    "/media/press-releases/dfc-deputy-ceo-sierra-leone-participates-groundbreaking-power-generation",
    "/media/press-releases/united-states-announces-new-126-million-commitment-ambitious-indonesian",
    "/media/press-releases/dfc-opens-office-cote-divoire",
    "/our-impact-transparency/information-quality-guidelines",
    "/media/press-releases/us-international-development-finance-corporation-begins-operations",
    "/media/press-releases/dfc-announces-more-18-billion-investments-and-new-initiatives-un-general",
    "/who-we-are/careers/general-public",
    "/media/press-releases/dfc-opens-first-office-latin-america-commits-nearly-470-million-grow-brazilian",
    "/foia",
    "/media/press-releases/us-kenya-advance-shared-priorities-surpassing-1-billion-dfc-exposure-intent",
    "/media/press-releases/dfc-taiwan-collaboration-advancing-private-sector-investment-opportunities",
    "/who-we-are/jamesa-m-hunter",
    "/investment-story/modernizing-greek-shipyard-critical-us-strategic-interests",
    "/media/press-releases/dfc-approves-17-transactions-totaling-more-33-billion-q1-fy2024",
    "/media/press-releases/dfc-commits-50-million-new-political-risk-insurance-expand-war-insurance",
    "/media/press-releases/dfc-approves-more-3-billion-across-priority-sectors-third-quarter-fy23",
    "/media/press-releases/dfc-ifc-and-raiffeisen-bank-ukraine-join-forces-support-ukrainian-businesses",
    "/media/press-releases/dfc-boosts-mexicos-ecosystem-regeneration-4m-investment",
    "/media/press-releases/dfc-ceo-marks-us-500-million-loan-strategic-supply-chain-diversification",
    "/media/press-releases/dfc-ifc-proparco-and-deg-support-aspen-strengthen-africas-pharmaceutical",
    "/media/press-releases/dfc-announces-its-largest-wind-energy-investment",
    "/media/press-releases/dfc-jbic-and-korea-eximbank-expand-partnership-india-through-new-framework",
    "/media/press-releases/eight-international-organizations-and-development-finance-institutions-join",
    "/oig/reports/other",
    "/whistleblower-protection",
    "/media/press-releases/dfc-sign-letter-interest-investment-kodaks-expansion-pharmaceuticals",
    "/media/press-releases/dfc-invest-24-million-miro-expand-sustainable-forestry-and-create-new-jobs",
    "/investment-story/fostering-regional-stability-guatemala",
    "/media/press-releases/dfc-announces-31-million-grant-weza-power-expand-electricity-access-and",
    "/media/press-releases/dfc-celebrates-nearly-50-billion-invested-over-five-years-advance-development",
    "/media/press-releases/world-bank-meetings-dfc-advances-infrastructure-partnerships-and-commits-198",
    "/media/press-releases/dfc-ceo-returns-vietnam-advance-strategic-relations-key-regional-partner",
    "/media/press-releases/dfc-statement-ifc-bridge-international-academies-case",
    "/media/press-releases/dfc-and-idb-invest-expand-americas-partnership-platform-creating-new-co",
    "/investment-story/financing-critical-infrastructure-development-africa",
    "/media/press-releases/nisha-desai-biswal-named-dfcs-first-deputy-ceo"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.dfc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}