module.exports = {
  "site": "https://www.dfc.gov",
  "urls": [
    "/media/press-releases/worlds-largest-debt-conversion-conservation-river-and-its-watershed-completed",
    "/who-we-are/mateo-goldman",
    "/media/press-releases/dfc-commits-more-12-billion-fiscal-year-2024-address-foreign-policy-and",
    "/media/press-releases/dfc-announces-call-applications-distributed-renewable-energy-projects",
    "/media/press-releases/dfc-head-investments-attends-ukraine-recovery-conference-advance-us-foreign",
    "/who-we-are/benjamin-friedmann",
    "/who-we-are/danielle-montgomery",
    "/media/press-releases/treasury-announces-agreement-establish-united-states-ukraine-reconstruction",
    "/investment-story/sourcing-cobalt-and-other-critical-minerals-countering-chinas-rare-earth-dominance",
    "/media/press-releases/dfc-head-investments-attends-17th-annual-us-africa-business-summit",
    "/our-impact/transparency/independent-accountability-mechanism",
    "/who-we-are/erica-ehst",
    "/our-work/health",
    "/investment-story/helping-gabon-grow-exports-and-diversify-its-economy",
    "/media/press-releases/dfc-approves-22-transactions-totaling-nearly-3-billion-q1-fy2025",
    "/media/press-releases/fact-sheet-president-donald-j-trump-secures-agreement-establish-united-states",
    "/investment-story/supporting-development-rare-earth-processing-facility-angola",
    "/investment-story/strengthening-strategic-competition-through-investments-africas-digital-economy",
    "/who-we-are-our-people-board-directors/public-hearings",
    "/media/press-releases/financial-close-reached-largest-debt-conversion-marine-conservation-protect",
    "/who-we-are/board-member/christopher-p-vincze",
    "/media/press-releases/dfc-approves-42-transactions-totaling-more-51-billion-across-priority-sectors",
    "/media/press-releases/dfc-makes-more-91-billion-financial-commitments-fiscal-year-2023",
    "/who-we-are/jesse-corradi",
    "/our-work/western-hemisphere",
    "/who-we-are/mildred-callear",
    "/media/press-releases/dfc-expands-global-impact-record-breaking-investments-fiscal-year-2024",
    "/our-work/indo-pacific",
    "/who-we-are/goldie-shturman",
    "/who-we-are/james-c-polan",
    "/who-we-are/deven-parekh",
    "/our-work/europe-and-central-asia",
    "/media/press-releases/nant-project-receives-its-first-disbursement-sierra-leone",
    "/who-we-are/senior-officials/keron-white",
    "/who-we-are/mehrdad-nazari",
    "/investment-story/financing-sierra-leones-first-major-utility-scale-power-plant",
    "/who-we-are/shreena-patel",
    "/who-we-are/scott-bessent",
    "/media/press-releases/cassava-technologies-receives-90-million-equity-investment-expanding-digital",
    "/media/press-releases/dfc-announces-1-billion-political-risk-insurance-ecuadors-first-debt",
    "/who-we-are/frank-esquivel",
    "/our-work/middle-east-and-north-africa",
    "/privacy",
    "/who-we-are/careers/finance-equity-investment-management",
    "/media/press-releases/dfc-head-investments-travels-libreville-strengthening-bilateral-ties",
    "/media/press-releases/dfc-sierra-leone-promote-access-reliable-energy-412-million-additional",
    "/media/press-releases/dfc-political-risk-insurance-support-blue-bond-providing-500-million-ocean",
    "/investment-story/improving-access-quality-healthcare-across-africa",
    "/media/press-releases/dfc-and-citi-announce-new-loan-tanzanias-crdb-bank-designed-support-more-4500",
    "/media/press-releases/dfc-announces-357-million-new-political-risk-insurance-ukraine-russias"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.dfc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}