module.exports = {
  "site": "https://justice.gov",
  "urls": [
    "/",
    "/archives/videos-archive",
    "/news",
    "/usao/pressreleases",
    "/archives/press-releases-archive",
    "/doj/webform/your-message-department-justice",
    "/atr/antitrust-case-filings",
    "/eoir/immigration-court-information",
    "/opa/pr/attorney-general-pamela-bondi-directs-prosecutors-seek-death-penalty-luigi-mangione",
    "/eoir",
    "/usao-edny/pr/pornhub-parent-company-admits-receiving-proceeds-sex-trafficking-and-agrees-three-year",
    "/pardon/clemency-recipients",
    "/psn/news",
    "/eoir/ecas",
    "/eoir/eoir-case-information",
    "/eoir/immigration-court-operational-status",
    "/news/press-releases",
    "/opa/pr/attorney-general-pamela-bondi-releases-first-phase-declassified-epstein-files",
    "/contact-us",
    "/psc/press-room",
    "/opa/pr/attorney-general-pamela-bondi-hosts-first-task-force-meeting-eradicate-anti-christian-bias",
    "/opioidawareness/news",
    "/ag",
    "/opa/pr/albuquerque-man-charged-connection-arson-attacks-tesla-dealership-and-republican-party-new",
    "/usao-sdtx/pr/former-federal-officer-sentenced-smuggling-aliens-and-receiving-bribes-cartel",
    "/usao-sdil/pr/dark-web-child-porn-leads-12-year-sentence-randolph-county-man",
    "/usao-ndca/pr",
    "/eoir/list-pro-bono-legal-service-providers",
    "/eoir/office-of-the-chief-immigration-judge",
    "/archives/jm/criminal-resource-manual-11-hostage-taking-18-usc-1203",
    "/opa/pr/attorney-general-pamela-bondi-statement-regarding-creation-2nd-amendment-task-force",
    "/tribal/tribal-justice-and-safety-press-room",
    "/coronavirus/news",
    "/usao-ma/pr/massachusetts-state-representative-arrested-and-charged-alleged-fraud-and-cover-scheme",
    "/usao-sdca/pr/man-sentenced-12-years-sex-trafficking-15-year-old-girl",
    "/usao-nh/pr/eight-defendants-indicted-international-conspiracy-bill-10-million-fraudulent-market",
    "/action-center/locate-prison-inmate-or-sex-offender",
    "/eoir/list-of-currently-disciplined-practitioners",
    "/forms",
    "/opa/pr/kansas-city-resident-arrested-and-charged-connection-tesla-arson",
    "/ag/staff-profile/meet-attorney-general",
    "/usao-sdtx/pr/16-charged-sweeping-houston-based-multimillion-dollar-illegal-gambling-and-money",
    "/legal-careers/vacancies",
    "/usao-sdca/pr/man-sentenced-10-years-sex-trafficking-16-year-old-girl",
    "/archives/doj-archive",
    "/jm/jm-1-9000-personal-use-of-social-media",
    "/doj/privacy-policy",
    "/ust/list-credit-counseling-agencies-approved-pursuant-11-usc-111",
    "/opa/pr/walgreens-agrees-pay-350m-illegally-filling-unlawful-opioid-prescriptions-and-submitting",
    "/usao",
    "/usao-sdtx/pr/cantina-owner-admits-forcing-young-girl-engage-commercial-sex",
    "/crt/fcs/titlevi",
    "/usao-ndga/pr/dozens-charged-atlanta-based-money-laundering-operation-funneled-30-million-proceeds",
    "/legal-careers/attorneys-vacancies",
    "/opa/pr/pennsylvania-man-charged-making-threats-assault-and-murder-president-donald-j-trump-other-us",
    "/usao-ma/pr/registered-sex-offender-lexington-sentenced-15-years-prison-attempting-purchase-sex",
    "/our-work"
  ],
  "scanner": {
    "crawler": false,
    "sitemap": false,
    "robotsTxt": false
  },
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-dev-shm-usage"
    ]
  }
}