module.exports = {
  "site": "https://www.mspb.gov",
  "urls": [
    "/e-appeal/support/index.htm",
    "/ppp/1ppp.htm",
    "/e-appeal/e-filingregulations.htm",
    "/msp/msp2.htm",
    "/studies/featured.htm",
    "/ppp/6ppp.htm",
    "/publicaffairs/publicaffairs.htm",
    "/studies/adverse_action_report/6_legalsources.htm",
    "/about/recentmembers.htm",
    "/studies/viewallstudies.htm",
    "/msp/msp5.htm",
    "/foia/surveydata.htm",
    "/msp/msp4.htm",
    "/e-appeal/infosheets.htm",
    "/studies/adverse_action_report/9_labelsnotrequired.htm",
    "/foia/efoia-caseinfo.htm",
    "/msp/msp9.htm",
    "/msp/msp8.htm",
    "/msp/msp3.htm",
    "/ppp/4ppp.htm",
    "/privacy/compliance.htm",
    "/ppp/3ppp.htm",
    "/ppp/2ppp.htm",
    "/foia/e-foiareadingroom.htm",
    "/appeals/infosheets.htm",
    "/ppp/13ppp.htm",
    "/ppp/10ppp.htm",
    "/publicaffairs/jobs.htm",
    "/studies/adverse_action_report/17_howhearing.htm",
    "/e-appeal/deadlines.htm",
    "/ppp/11ppp.htm",
    "/studies/adverse_action_report/7_decision-maker.htm",
    "/publicaffairs/ig.htm",
    "/appeals/training.htm",
    "/publicaffairs/accessibility.htm",
    "/studies/adverse_action_report/18_implementingorchallenging.htm",
    "/privacy/index.htm",
    "/msp/msp6.htm",
    "/studies/adverse_action_report/index.htm",
    "/e-appeal/information_for_pending_appeals.htm",
    "/studies/publications.htm",
    "/studies/adverse_action_report/15_limitedpowers.htm",
    "/studies/newsletters.htm",
    "/e-appeal/policies.htm",
    "/studies/index.htm",
    "/studies/searchstudies.htm",
    "/studies/surveys.htm",
    "/publicaffairs/federalreg.htm",
    "/e-appeal/help/agencies/",
    "/msp/msp7.htm"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.mspb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}