module.exports = {
  "site": "https://www.mspb.gov",
  "urls": [
    "/",
    "/appeals/appeals.htm",
    "/ppp/ppp.htm",
    "/about/contact.htm",
    "/decisions/casereports.htm",
    "/about/about.htm",
    "/decisions/precdec.htm",
    "/msp/meritsystemsprinciples.htm",
    "/decisions/nonprecdec.htm",
    "/index.htm",
    "/updatelinks.htm",
    "/e-appeal/index.htm",
    "/studies/adverse_action_report/4_performance-based%20actions.htm",
    "/decisions/precedentialdecsearch.html",
    "/appeals/appellantqanda.htm",
    "/e-appeal/support/",
    "/studies/adverse_action_report/5_differenttypes.htm",
    "/appeals/forms.htm",
    "/e-appeal/",
    "/decisions/nonprecedentialdecsearch.html",
    "/appeals/whistleblower.htm",
    "/about/search.htm",
    "/publicaffairs/regulations.htm",
    "/studies/adverse_action_report/10_determiningthepenalty.htm",
    "/publicaffairs/techsupport.htm",
    "/appeals/resources.htm",
    "/about/members.htm",
    "/e-appeal/e-appealfaq.htm",
    "/ppp/7ppp.htm",
    "/studies/adverse_action_report/3_adverseactionprocess_flowchart.htm",
    "/appeals/mediationappeals.htm",
    "/msp/msp1.htm",
    "/e-appeal/help/appellants/",
    "/appeals/jurisdiction.htm",
    "/studies/adverse_action_report/14_identifyingprobationers.htm",
    "/e-appeal/userguides.htm",
    "/appeals/training/introtomspbvideo.htm",
    "/appeals/training/introtoappeals.htm",
    "/probono/index.htm",
    "/msp/faq.htm",
    "/studies/adverse_action_report/8_connectingthejob.htm",
    "/ppp/8ppp.htm",
    "/ppp/9ppp.htm",
    "/studies/adverse_action_report/13_agencyofficials.htm",
    "/about/eeo.htm",
    "/ppp/12ppp.htm",
    "/foia/request.htm",
    "/appeals/hearingsites.htm",
    "/about/organization.htm",
    "/about/annual.htm"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.mspb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}