module.exports = {
  "site": "https://www.mspb.gov",
  "urls": [
    "/appeals/review.htm",
    "/updatelinks.htm",
    "/e-appeal/information_for_agency_users.htm",
    "/studies/adverse_action_report/11_howemployeesbecome.htm",
    "/open/index.htm",
    "/ppp/14ppp.htm",
    "/ppp/5ppp.htm",
    "/contact/contact.htm",
    "/informationqualitystandards/index.htm",
    "/publicaffairs/hpsd12.htm",
    "/privacy/submitrequest.htm",
    "/regulatoryreview/index.htm",
    "/appeals/uscode.htm",
    "/publicaffairs/contracting.htm",
    "/publicaffairs/paperwork-reduction-act.htm",
    "/foia/efoia-doc-resources.htm",
    "/about/surveys.htm",
    "/foia/efoia-operational.htm",
    "/foia/foiareports.htm",
    "/appeals/mediationappeals_styles.htm",
    "/foia/efoia-frn.htm",
    "/studies/adverse_action_report/2_secondhandnews.htm",
    "/about/annualreport_archive.htm",
    "/data/ai_inventory/",
    "/data/",
    "/studies/adverse_action_report/12_avoidfacilitating.htm",
    "/studies/adverse_action_report/16_whyfederalemployees.htm",
    "/appeals/training/probonotraining.htm",
    "/appeals/mediationappeals_medadj.htm",
    "/studies/adverse_action_report/19_additionalresources.htm",
    "/appeals/mediationappeals_parties.htm",
    "/privacy/website_privacy_policy.htm",
    "/studies/",
    "/appeals/training/pppminimovie.htm",
    "/vulnerability-disclosure-policy/",
    "/foia/e-foiareadingroom-old6162025.htm",
    "/studies/mps2016.htm",
    "/privacy/policyandreports.htm",
    "/foia/foialogs.htm",
    "/appeals/training/madatedefile.htm",
    "/about/budget.htm",
    "/furloughappeals/index.htm",
    "/cj/",
    "/informationqualitystandards/",
    "/sunshinemeeting/index.htm",
    "/appeals/mediationappeals_uptou.htm",
    "/appeals/training/blowingthewhistle.htm",
    "/data/index.htm",
    "/significantcases/abernathy.htm",
    "/e-appeal/e-appealfaq_august42023.htm"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.mspb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}