module.exports = {
  "site": "https://www.mcc.gov",
  "urls": [
    "/resources/doc/guidance-accommodation-welfare-staff-and-labor/",
    "/resources/doc/policy-counter-trafficking-in-persons/",
    "/about/profile/bio-bowen-martha/",
    "/resources/story/section-bf-ccr-rural-land-project/",
    "/where-we-work/program/sri-lanka-compact/",
    "/news-and-events/release/release-121924-mcc-board-selection/",
    "/resources/doc/guide-to-the-indicators-fy-2025/",
    "/blog/entry/blog-011725-kiribati-students-boost-their-skills-in-seattle/",
    "/resources/doc/policy-fraud-and-corruption/",
    "/resources/doc/water-sector-cost-benefit-guidance/",
    "/about/profile/bio-petrie-dan/",
    "/our-impact/lesson-learned/lesson-mn-c-2-projects-are-more-likely-to-be-successful-when-fea/",
    "/resources/doc/report-selection-criteria-methodology-fy25/",
    "/resources/doc/guidelines-for-financial-audits-contracted-by-accountable-entities/",
    "/resources/doc/010124-ae-program-procurement-policy-guidelines/",
    "/our-impact/constraints-analysis/",
    "/where-we-work/program/mauritania-threshold-program/",
    "/resources/doc/report-fy2025-eligible-country/",
    "/where-we-work/country/togo/",
    "/where-we-work/country/belize/",
    "/where-we-work/country/mongolia/",
    "/resources/no-fear-act/",
    "/about/profile/bio-cairncross-sean/",
    "/about/values/",
    "/resources/docs/compact-implementation-guidance/",
    "/resources/foia/",
    "/work-with-us/partnerships/aligned-investment/",
    "/where-we-work/program/kiribati-threshold-program/",
    "/how-we-work/program/regional-compact/",
    "/where-we-work/country/senegal/",
    "/where-we-work/country/gambia/",
    "/where-we-work/program/liberia-compact/",
    "/initiatives/initiative/power-africa/",
    "/where-we-work/country/guatemala/",
    "/where-we-work/country/benin/",
    "/resources/doc/cost-benefit-analysis-guidelines/",
    "/where-we-work/country/malawi/",
    "/resources/doc/procurement-performance-report-template/",
    "/where-we-work/program/albania-proposed-compact/",
    "/initiatives/initiative/domestic-resource-mobilization/",
    "/sectors/sector/energy/",
    "/where-we-work/program/ghana-compact/",
    "/who-we-select/mcc-effect/",
    "/where-we-work/country/morocco/",
    "/sectors/sector/transportation-infrastructure/",
    "/news-and-events/podcasts/",
    "/where-we-work/program/burkina-faso-compact-ii/",
    "/resources/story/section-moz-ccr-wash-project/",
    "/where-we-work/program/kenya-urban-mobility-and-growth-threshold-program/",
    "/about/profile/bio-nguyen-caroline/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.mcc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}