module.exports = {
  "site": "https://www.mcc.gov",
  "urls": [
    "/",
    "/news-and-events/release/release-082225-board-affirms-foreign-assistance/",
    "/news-and-events/",
    "/about/",
    "/news-and-events/event/outreach-082125-board-meeting/",
    "/where-we-work/",
    "/resources/",
    "/who-we-select/",
    "/careers/",
    "/who-we-select/scorecards/",
    "/where-we-work/program/nepal-compact/",
    "/about/leadership/",
    "/our-impact/",
    "/resources/story/section-writing-guide-good-grammar/",
    "/about/org-unit/board-of-directors/",
    "/work-with-us/",
    "/resources/doc/policy-on-program-closure/",
    "/news-and-events/releases/",
    "/news-and-events/release/mcc-foreign-assistance-review/",
    "/sectors/",
    "/where-we-work/program/kosovo-compact/",
    "/resources/doc/report-fy2025-eligible-country-fiji-tonga/",
    "/blog/",
    "/resources/doc/report-candidate-country-report-fy2026/",
    "/resources/doc/guidance-on-the-indicator-tracking-table/",
    "/contact-us/",
    "/about/org-chart/",
    "/work-with-us/partner-country/",
    "/resources/docs/program-procurement-guidelines/",
    "/resources/doc/agriculture-sector-cost-benefit-analysis-guidance/",
    "/news-and-events/events/",
    "/careers/internships/",
    "/publications-sections/story-cdg-chapter-7-guidelines-for-developing-concept-notes/",
    "/resources/doc/millennium-challenge-act-of-2003-amended/",
    "/where-we-work/program/sierra-leone-compact/",
    "/who-we-select/indicators/",
    "/resources/story/section-phl-ccr-kalahi-cidss-project/",
    "/who-we-select/indicator/government-effectiveness-indicator/",
    "/about/org-unit/advisory-council/",
    "/who-we-select/selection-process/",
    "/initiatives/",
    "/work-with-us/mcc-partner-countries/",
    "/who-we-select/reports/",
    "/initiatives/initiative/prosper-africa/",
    "/how-we-work/program/compact/",
    "/where-we-work/country/kosovo/",
    "/where-we-work/program/mongolia-water-compact/",
    "/where-we-work/program/belize-compact/",
    "/our-impact/evaluation-briefs/",
    "/where-we-work/program/benin-regional-transport-compact/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.mcc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}