module.exports = {
  "site": "https://www.mcc.gov",
  "urls": [
    "/where-we-work/program/zambia-farm-to-market-compact/",
    "/resources/doc/policy-121724-ae-procurement-guidelines-2025/",
    "/where-we-work/program/indonesia-infrastructure-and-finance-compact/",
    "/where-we-work/program/cote-divoire-compact/",
    "/resources/doc/paper-inclusive-growth-concepts-in-the-context-of-mcc/",
    "/where-we-work/program/cote-divoire-regional-compact/",
    "/where-we-work/program/lesotho-health-and-horticulture-compact/",
    "/links/link-mida-millennium-development-authority-ghana/",
    "/where-we-work/country/nepal/",
    "/our-impact/err/",
    "/where-we-work/country/sierra-leone/",
    "/where-we-work/country/liberia/",
    "/work-with-us/mcc-business/",
    "/where-we-work/program/malawi-transport-land-compact/",
    "/blog/entry/blog-010725-paving-prosperity-zambia-roads-project/",
    "/about/profile/bio-albright-alice/",
    "/where-we-work/country/indonesia/",
    "/resources/doc/education-sector-cost-benefit-analysis-guidance/",
    "/resources/doc/cbj-fy2026/",
    "/resources/doc/report-candidate-country-fy2025/",
    "/resources/doc/project-concept-paper-template-and-guidance/",
    "/where-we-work/program/senegal-power-compact/",
    "/where-we-work/region/africa/",
    "/who-we-select/suspension-or-termination/",
    "/about/org-unit/economic-advisory-council/",
    "/news-and-events/feature/liberia-closeout/",
    "/resources/doc/policy-for-monitoring-and-evaluation/",
    "/where-we-work/program/gambia-threshold-program/",
    "/where-we-work/program/timor-leste-compact/",
    "/careers/compensation/",
    "/where-we-work/country/zambia/",
    "/about/profile/ander-crenshaw/",
    "/who-we-select/indicator/control-of-corruption-indicator/",
    "/news-and-events/speeches/",
    "/news-and-events/release/release-010825-albania-selected-for-partnership/",
    "/where-we-work/country/mozambique/",
    "/work-with-us/partnerships/cooperative-agreements/",
    "/blog/entry/blog-011725-transforming-belizes-future-mccs-investment-in-education/",
    "/resources/doc/report-fy2024-chief-foia-officer/",
    "/resources/doc/annex-of-general-provisions/",
    "/where-we-work/country/cote-divoire/",
    "/where-we-work/country/lesotho/",
    "/where-we-work/program/mozambique-connectivity-and-coastal-resilience-compact/",
    "/how-we-work/program/threshold-program/",
    "/resources/doc/guidance-health-sector-cost-benefit-analysis/",
    "/where-we-work/program/liberia-proposed-compact/",
    "/where-we-work/program/the-gambia-proposed-compact/",
    "/news-and-events/event/outreach-121824-board-meeting/",
    "/blog/entry/blog-121224-investing-in-indonesia/",
    "/where-we-work/program/benin-power-compact/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.mcc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}