module.exports = {
  "site": "https://www.ncd.gov",
  "urls": [
    "/2020/07/02/ncd-chairman-statement-on-death-of-michael-hickson/",
    "/reports/index.html",
    "/report/organ-transplant-discrimination-against-people-with-disabilities/",
    "/report/voting-fact-sheet/",
    "/report/americans-with-disabilities-act-watch-year-one-a-report-to-the-president-and-the-congress-on-progress-in-implementing-the-americans-with-disabilities-act/",
    "/report/furthering-the-goals-of-the-americans-with-disabilities-act-through-disability-policy-research-in-the-1990s-summary-of-proceeding/",
    "/fact%20sheets/2005/09/02/hurricane-katrina-affected-areas/",
    "/report/mental-health-on-college-campuses-investments-accommodations-needed-to-address-student-needs/",
    "/accountability/ncd-strategic-plan/",
    "/report/national-disability-policy-a-progress-report-july-1996/",
    "/reports/2024/",
    "/policy-areas/emergency-management/",
    "/policy-areas/housing/",
    "/letters/2025-06-25-ncd-letter-to-potus-regarding-drug-pricing/",
    "/2024/12/04/ncd-recommendations-key-to-ending-14-c-subminimum-wage-discrimination/",
    "/meetings/index.html",
    "/council-members/sascha-bittner/",
    "/report/tennessee-v-lane-the-legal-issues-and-the-implications-for-people-with-disabilities/",
    "/report/the-impact-of-exemplary-technology-support-programs-on-students-with-disabilities/",
    "/policy-areas/employment/index.html",
    "/accountability/financial-audit-reports/",
    "/2024/05/01/ncd-applauds-hhs-final-rule-updating-section-504/",
    "/2024/12/09/dol-requests-public-comment-on-proposed-rule-ending-14-c/",
    "/foia/reference-guide/",
    "/council-members/hoskie-benally-jr/",
    "/2025/05/09/ncd-offers-undergraduate-summer-intern-opportunity/",
    "/2024/10/31/ncd-releases-annual-report-of-policy-progress-impacting-americans-with-disabilities/",
    "/2017/10/26/highlighting-disability-poverty-connection-ncd-urges-congress-to-alter-federal-policies-that-disadvantage-people-with-disabilities/",
    "/letters/2025-05-01-ncd-letter-to-illinois-general-assembly-regarding-assisted-suicide-legislation/",
    "/report/sharing-the-risk-and-ensuring-independence-a-disability-perspective-on-access-to-health-insurance-and-health-related-services/",
    "/policy-areas/youth-perspectives/",
    "/reports/2020/",
    "/reports/2025/",
    "/2019/11/20/federal-study-finds-rampant-bias-in-medical-futile-care-decisions/",
    "/meeting/2025-03-06-march-6-7-2025-council-meeting/",
    "/letters/2024-04-01-ncd-letter-to-sasc-and-hasc-regarding-abilityone/",
    "/newsroom/funding-opportunities/",
    "/accountability/no-fear-act/",
    "/testimonies/2025-07-09-statement-to-house-ways-and-means-subcommittee-on-health-regarding-technology-accessibility-standards/",
    "/newsroom/2025/",
    "/report/briefing-paper-reauthorization-of-the-higher-education-act-hea-the-implications-for-increasing-the-employment-of-people-with-disabilities/",
    "/accountability/buy-american-act-reports/",
    "/policy-areas/crpd/",
    "/2024/06/05/federal-report-examines-prenatal-interventions-through-lens-of-people-with-disabilities-whose-lives-are-directly-affected/",
    "/2025/07/09/ncd-advises-house-ways-and-means-subcommittee-on-accessible-digital-healthcare-technologies/",
    "/2025/06/04/ncd-quarterly-meeting-focuses-on-employment-nursing-home-placement-of-youth-with-disabilities/",
    "/council-members/index.html",
    "/report/serving-the-nations-students-with-disabilities-progress-and-prospects/",
    "/policy-areas/technology/",
    "/reports/2021/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.ncd.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}