module.exports = {
  "site": "https://archives.gov",
  "urls": [
    "/veterans/military-service-records",
    "/",
    "/founding-docs/declaration-transcript",
    "/veterans",
    "/founding-docs/constitution-transcript",
    "/personnel-records-center/dd-214",
    "/founding-docs/bill-of-rights-transcript",
    "/veterans/military-service-records/standard-form-180",
    "/founding-docs",
    "/founding-docs/constitution",
    "/founding-docs/bill-of-rights/what-does-it-say",
    "/personnel-records-center/military-personnel",
    "/citizen-archivist/missions",
    "/milestone-documents/brown-v-board-of-education",
    "/veterans/military-service-records/medical-records.html",
    "/milestone-documents/14th-amendment",
    "/citizen-archivist",
    "/milestone-documents/civil-rights-act",
    "/milestone-documents/19th-amendment",
    "/founding-docs/declaration",
    "/personnel-records-center/address-list",
    "/exhibits/featured-documents/emancipation-proclamation",
    "/milestone-documents/list",
    "/personnel-records-center/forms",
    "/personnel-records-center/ompf-background",
    "/founding-docs/bill-of-rights",
    "/founding-docs/amendments-11-27",
    "/cui/registry/category-list",
    "/news/topics/9-11-anniversary",
    "/education/lessons/japanese-relocation",
    "/milestone-documents/13th-amendment",
    "/milestone-documents/voting-rights-act",
    "/personnel-records-center",
    "/electoral-college/allocation",
    "/veterans/military-service-records/about-service-records",
    "/citizen-archivist/register-and-get-started",
    "/presidential-libraries",
    "/locations",
    "/education/lessons/woman-suffrage",
    "/milestone-documents/articles-of-confederation",
    "/milestone-documents/general-eisenhowers-order-of-the-day",
    "/contact",
    "/st-louis/military-personnel-archival",
    "/citizen-archivist/missions/revolutionary-war-pension-files",
    "/personnel-records-center/ompf-access-public",
    "/milestone-documents/dred-scott-v-sandford",
    "/veterans/replace-medals.html",
    "/personnel-records-center/military-personnel/ompf-archival-requests",
    "/publications/prologue/2005/winter/von-trapps-html",
    "/founding-docs/signers-factsheet",
    "/electoral-college/about",
    "/dc",
    "/citizen-archivist/get-started-transcribing",
    "/milestone-documents/plessy-v-ferguson",
    "/milestone-documents/chinese-exclusion-act",
    "/veterans/replace-medals"
  ],
  "scanner": {
    "crawler": false,
    "sitemap": false,
    "robotsTxt": false
  },
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-dev-shm-usage"
    ]
  }
}