module.exports = {
  "site": "https://www.arts.gov",
  "urls": [
    "/news/press-releases/2025/creative-forces-supports-community-arts-engagement-projects-military-connected-people",
    "/impact/arts-education",
    "/stories/blog/2020/hispanic-heritage-flashback-friday-sandra-cisneros-recognizing-ourselves",
    "/stories/magazine/2013/4/inspiration-quotient-different-kind-iq/sherman-alexie",
    "/impact/arts-and-artifacts-indemnity-program",
    "/impact/native-arts-and-culture",
    "/about/kennedy-transcript",
    "/initiatives/nea-big-read/our-town",
    "/stories",
    "/stories/magazine/2011/4/what-innovation/sam-gilliam",
    "/impact/arts-and-artifacts-indemnity-program/international-indemnity",
    "/stories/blog/2015/our-top-ten-ray-bradbury-quotes",
    "/stories/blog/2025/arts-and-healing-creative-forces-joint-base-elmendorf-richardson-hospital",
    "/initiatives/shakespeare-american-communities",
    "/stories/blog/2017/poems-about-poetry",
    "/honors/medals/cyd-charisse",
    "/news",
    "/impact/research/publications/snapshots-arts-education-childhood-and-adolescence",
    "/stories/blog/2021/wisdom-artists-collection-quotes-bipoc-artists",
    "/news/press-releases/2025/updates-national-endowment-arts-fy-2026-grant-opportunities",
    "/news/press-releases/2025/national-endowment-arts-supports-arts-nearly-368-million-funding-nationwide",
    "/stories/podcast/revisiting-lin-manuel-miranda",
    "/initiatives/nea-big-read/grantees",
    "/initiatives/musical-theater-songwriting-challenge",
    "/stories/blog/2022/ten-things-you-might-not-know-about-angels-america",
    "/initiatives/nea-big-read/best-we-could-do-illustrated-memoir",
    "/initiatives/nea-big-read/heart-sea",
    "/stories/blog/2014/jazz-poetry-langston-hughes",
    "/impact/research/arts-data-profile-series/37",
    "/form/sign-up-for-american-artscape-magazine",
    "/initiatives/nea-big-read/nothing-see-here",
    "/stories/magazine/2018/2/community-art-look-public-art-america",
    "/news/press-releases/2024/arts-cultural-sector-hit-all-time-high-2022-value-added-us-economy",
    "/impact/research/publications/arts-participation-2022-technical-summary-report",
    "/about/open-government",
    "/initiatives/nea-big-read/great-gatsby",
    "/initiatives/nea-research-labs",
    "/impact/creative-placemaking/exploring-our-town/chattanooga-tn-main-terrain-art-park",
    "/stories/blog/2022/intoxicating-power-language-conversation-jason-reynolds",
    "/initiatives/creative-forces/creative-forces-community-engagement-program",
    "/honors/heritage/zakir-hussain",
    "/initiatives/creative-forces/creative-forces-research",
    "/stories/blog/2025/five-facts-you-didnt-know-about-presidential-portraits",
    "/initiatives/nea-big-read/when-emperor-was-divine",
    "/impact/research/publications/arts-participation-patterns-2022-highlights-survey-public-participation-arts",
    "/impact/arts-and-artifacts-indemnity-program/domestic-indemnity",
    "/stories/magazine/2016/1/telling-all-our-stories-arts-and-diversity/sandra-cisneros",
    "/honors/medals/selena-quintanilla",
    "/stories/magazine/2014/4/art-failure-importance-risk-and-experimentation/toni-morrison",
    "/grants/manage-your-award/project-budget-instructions-and-form"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.arts.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}