module.exports = {
  "site": "https://www.nlrb.gov",
  "urls": [
    "/what-we-do/investigate-charges/10j-injunctions",
    "/news-outreach/news-story/gc-25-05-rescission-of-certain-general-counsel-memoranda",
    "/about-nlrb/who-we-are/regional-offices/region-19-seattle",
    "/news-outreach/news-story/nlrb-acting-general-counsel-issues-memo-on-surreptitious-recording-of",
    "/cases-decisions/decisions/weekly-summaries-decisions",
    "/news-outreach/fact-sheets/nlra-and-right-strike",
    "/about-nlrb/who-we-are/regional-offices/region-04-philadelphia",
    "/about-nlrb/who-we-are/regional-offices/region-20-san-francisco",
    "/news-outreach/news-story/board-revises-standard-on-employers-duty-to-bargain-before-changing-terms",
    "/news-outreach/news-story/board-adopts-new-standard-for-assessing-lawfulness-of-work-rules",
    "/about-nlrb/who-we-are/regional-offices/region-18-minneapolis",
    "/case/10-rc-350817",
    "/reports/agency-performance-report/election-reports/election-reports-fy-2025",
    "/about-nlrb/who-we-are/regional-offices/region-21-los-angeles",
    "/about-nlrb/who-we-are/regional-offices/region-14-st-louis",
    "/about-nlrb/rights-we-protect/the-law/employees/are-you-covered",
    "/about-nlrb/who-we-are/regional-offices/region-06-pittsburgh",
    "/about-nlrb/who-we-are/regional-offices/region-32-oakland",
    "/about-nlrb/rights-we-protect/the-law/interfering-with-or-dominating-a-union-section-8a2",
    "/about-nlrb/rights-we-protect/the-law/coercion-of-employees-section-8b1a",
    "/reports",
    "/about-nlrb/who-we-are/regional-offices/region-12-tampa",
    "/case/36-rd-001741",
    "/about-nlrb/who-we-are/regional-offices/region-16-fort-worth",
    "/search/case/rivian",
    "/about-nlrb/who-we-are/inspector-general",
    "/reports/agency-performance-reports/performance-and-accountability/graphs-data",
    "/about-nlrb/who-we-are/regional-offices/region-09-cincinnati",
    "/about-nlrb/who-we-are/regional-offices/region-31-los-angeles",
    "/news-outreach/news-story/board-issues-decision-announcing-new-framework-for-union-representation",
    "/espanol",
    "/news-outreach/news-story/information-for-the-public-on-nlrb-office-of-the-general-counsel-authority",
    "/reports/nlrb-case-activity-reports/representation-cases",
    "/resources/related-agencies",
    "/about-nlrb/who-we-are/regional-offices/region-15-new-orleans",
    "/case/12-rd-367855",
    "/case/31-cb-349256",
    "/news-publications/publications/fact-sheets",
    "/about-nlrb/who-we-are/board/board-members-1935",
    "/cases-decisions/weekly-summaries-decisions/summary-of-nlrb-decisions-for-week-of-august-4-8-2025",
    "/guidance/key-reference-materials/gc-collective-bargaining-resources",
    "/case/27-ca-110765",
    "/about-nlrb/who-we-are/inspector-general/office-of-inspector-general-investigations",
    "/search/case/amazon",
    "/about-nlrb/who-we-are/regional-offices/region-08-cleveland",
    "/news-outreach/news-story/board-returns-to-clear-and-unmistakable-waiver-standard",
    "/about-nlrb/who-we-are/regional-offices/region-25-indianapolis",
    "/about-nlrb/who-we-are/regional-offices/region-05-baltimore",
    "/es/acerca-de-la-nlrb/derechos-que-protegemos/sus-derechos/derechos-y-obligaciones-del-empleador-y-de",
    "/about-nlrb/who-we-are/division-of-judges"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nlrb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}