module.exports = {
  "site": "https://www.archives.gov",
  "urls": [
    "/research/jfk/release-2017-2018",
    "/founding-docs/declaration-transcript",
    "/veterans/military-service-records",
    "/founding-docs/constitution-transcript",
    "/",
    "/veterans",
    "/research",
    "/research/jfk/release-2022",
    "/founding-docs/bill-of-rights-transcript",
    "/founding-docs/constitution",
    "/founding-docs",
    "/founding-docs/bill-of-rights/what-does-it-say",
    "/personnel-records-center/dd-214",
    "/veterans/military-service-records/standard-form-180",
    "/research/military",
    "/milestone-documents/articles-of-confederation",
    "/research/census/online-resources",
    "/founding-docs/declaration",
    "/veterans/military-service-records/medical-records.html",
    "/research/jfk/release-2025",
    "/founding-docs/bill-of-rights",
    "/founding-docs/amendments-11-27",
    "/personnel-records-center/military-personnel",
    "/research/genealogy",
    "/research/military/ww2",
    "/personnel-records-center/address-list",
    "/citizen-archivist/missions",
    "/personnel-records-center/forms",
    "/locations",
    "/citizen-archivist",
    "/milestone-documents/19th-amendment",
    "/milestone-documents/list",
    "/research/native-americans/dawes",
    "/records-mgmt/rcs/schedules/index.html",
    "/electoral-college/allocation",
    "/research/military/army",
    "/personnel-records-center/ompf-background",
    "/research/military/veterans/online",
    "/research/immigration/naturalization",
    "/publications/prologue/2006/spring/interview.html",
    "/veterans/military-service-records/about-service-records",
    "/milestone-documents/14th-amendment",
    "/research/jfk",
    "/cui/registry/category-list",
    "/founding-docs/signers-factsheet",
    "/research/census",
    "/founding-docs/declaration/what-does-it-say",
    "/research/order",
    "/research/jfk/release-2023",
    "/milestone-documents/brown-v-board-of-education",
    "/personnel-records-center",
    "/research/military/army/post-ww1",
    "/research/start/online-tools",
    "/research/genealogy/start-research",
    "/contact",
    "/founding-docs/founding-fathers",
    "/research/immigration/passenger-arrival.html",
    "/education/lessons/worksheets",
    "/personnel-records-center/ompf-access-public",
    "/news/topics/9-11-anniversary",
    "/citizen-archivist/register-and-get-started",
    "/milestone-documents/13th-amendment"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.archives.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 124,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}