module.exports = {
  "site": "https://www.nsf.gov",
  "urls": [
    "/",
    "/funding/opportunities",
    "/funding/opportunities/grfp-nsf-graduate-research-fellowship-program",
    "/policies/pappg/24-1/ch-2-proposal-preparation",
    "/awardsearch/",
    "/funding/opportunities",
    "/funding/initiatives/reu/search",
    "/funding/opportunities/nsf-ttp-national-science-foundation-translation-practice",
    "/news/nsf-announces-100-million-investment-national-artificial",
    "/updates-on-priorities",
    "/funding/initiatives/reu/search",
    "/policies/pappg/24-1",
    "/funding/opportunities/future-core-computer-information-science-engineering-future-computing/nsf25-543/solicitation",
    "/funding/opportunities/nsf-ttp-national-science-foundation-translation-practice/nsf25-540/solicitation",
    "/policies/pappg",
    "/funding/senior-personnel-documents",
    "/funding/opportunities/career-faculty-early-career-development-program",
    "/funding/opportunities/career-faculty-early-career-development-program/nsf22-586/solicitation",
    "/funding/initiatives/reu",
    "/funding/opportunities/grfp-nsf-graduate-research-fellowship-program/nsf24-591/solicitation",
    "/news",
    "/funding/opportunities/future-core-computer-information-science-engineering-future-computing",
    "/funding",
    "/executive-orders",
    "/funding/opportunities/sch-smart-health-biomedical-research-era-artificial-intelligence/nsf25-542/solicitation",
    "/funding/opportunities/egfp-nsf-epscor-graduate-fellowship-program/updates/120063",
    "/news/nsf-invests-over-74-million-6-mathematical-sciences-research",
    "/notices/important/important-notice-no-149-updates-nsf-research-security/in149",
    "/funding/preparing-proposal",
    "/news/releases",
    "/funding/opportunities/vines-verticals-enabling-intelligent-network-systems/nsf25-539/solicitation",
    "/funding/opportunities/vines-verticals-enabling-intelligent-network-systems",
    "/careers",
    "/policies/pappg/23-1/ch-2-proposal-preparation",
    "/funding/opportunities/reu-research-experiences-undergraduates",
    "/funding/graduate-students",
    "/funding/opportunities/sch-smart-health-biomedical-research-era-artificial-intelligence",
    "/bfa/dias/policy/nspm-33-implementation-guidance",
    "/tip/latest",
    "/honorary-awards/paemst",
    "/funding/initiatives/i-corps",
    "/news/statement-nsf-chief-staff-brian-stone-performing-duties-nsf",
    "/research-security/training",
    "/news/nsf-invests-292-million-epscor-research-infrastructure",
    "/news/interstellar-comet-3iatlas-observed-nsf-funded-gemini-north",
    "/about/contact-us",
    "/funding/early-career-researchers",
    "/funding/opportunities/reu-research-experiences-undergraduates/nsf23-601/solicitation",
    "/awards/terms-conditions",
    "/funding/initiatives/reu/students",
    "/news/nsf-invest-new-national-network-ai-programmable-cloud",
    "/funding/postdocs",
    "/about",
    "/funding/award-search",
    "/funding/opportunities/pcl-test-bed-test-bed-toward-network-programmable-cloud-laboratories/nsf25-541/solicitation",
    "/funding/opportunities/cps-cyber-physical-systems",
    "/funding/submitting-proposal",
    "/funding/opportunities/sbirsttr-phase-i-nsf-small-business-innovation-research-small-business/nsf24-579/solicitation",
    "/funding/undergraduates",
    "/news/new-ai-model-could-revolutionize-us-manufacturing",
    "/funding/opportunities/pcl-test-bed-test-bed-toward-network-programmable-cloud-laboratories",
    "/news/new-axolotl-study-gives-researchers-leg-work-towards-limb",
    "/policies/pappg/24-1/ch-1-pre-submission",
    "/funding/opportunities/iuse-edu-improving-undergraduate-stem-education-directorate-stem",
    "/funding/opportunities/ate-advanced-technological-education",
    "/funding/opportunities/satc-20-security-privacy-trust-cyberspace",
    "/careers/job-types",
    "/funding/opportunities/s-stem-nsf-scholarships-science-technology-engineering-mathematics",
    "/science-matters/nsf-was-there-start-experimental-quantum-chip-may-yield-more",
    "/funding/getting-started",
    "/policies/pappg/24-1/ch-7-award-administration",
    "/policies/document/indirect-cost-rate",
    "/news/nsf-invests-nearly-32m-accelerate-novel-ai-driven-approaches",
    "/funding/opportunities/us-national-science-foundation-research-traineeship-program",
    "/science-matters/1970s-psychology-experiment-behind-star-wars-special-effects",
    "/news/nsf-advances-29-semifinalists-second-nsf-regional-innovation",
    "/cise",
    "/about/directorates-offices",
    "/oise/international-collaborations",
    "/research-security",
    "/awards/terms-conditions/research",
    "/science-matters/horses-part-indigenous-cultures-longer-western",
    "/focus-areas",
    "/funding/opportunities/iuse-edu-improving-undergraduate-stem-education-directorate-stem/nsf23-510/solicitation",
    "/news/nsf-zeus-becomes-most-powerful-laser-us",
    "/about/budget/fy2026",
    "/funding/opportunities/mri-major-research-instrumentation-program",
    "/funding/opportunities/ritel-research-innovative-technologies-enhanced-learning",
    "/funding/opportunities/sbirsttr-phase-i-nsf-small-business-innovation-research-small-business",
    "/funding/data-management-plan",
    "/science-matters/5-black-hole-facts-blow-your-mind",
    "/awards/report-your-outcomes",
    "/funding/opportunities/drk-12-discovery-research-prek-12",
    "/funding/learn/broader-impacts",
    "/funding/opportunities/ecrcore-edu-core-research",
    "/eng/programs",
    "/news/nsf-invests-ai-ready-test-beds-accelerate-us-leadership",
    "/funding/opportunities/aisl-advancing-informal-stem-learning",
    "/funding/opportunities/eri-engineering-research-initiation",
    "/bio"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nsf.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 200,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}