module.exports = {
  "site": "https://www.nsf.gov",
  "urls": [
    "/",
    "/funding/opportunities/grfp-nsf-graduate-research-fellowship-program",
    "/funding/opportunities",
    "/funding/opportunities",
    "/awardsearch/",
    "/funding/initiatives/reu/search",
    "/policies/pappg/24-1/ch-2-proposal-preparation",
    "/funding/initiatives/reu/search",
    "/funding/opportunities/future-core-computer-information-science-engineering-future-computing/nsf25-543/solicitation",
    "/funding/opportunities/grfp-nsf-graduate-research-fellowship-program/nsf24-591/solicitation",
    "/policies/pappg",
    "/updates-on-priorities",
    "/funding/opportunities/nsf-ttp-national-science-foundation-translation-practice/nsf25-540/solicitation",
    "/policies/pappg/24-1",
    "/funding/initiatives/reu",
    "/funding/senior-personnel-documents",
    "/funding/opportunities/nsf-ttp-national-science-foundation-translation-practice",
    "/news",
    "/funding/opportunities/future-core-computer-information-science-engineering-future-computing",
    "/news/nsf-announces-new-funding-opportunities-advance-ai-education",
    "/funding/opportunities/stem-k-12-nsf-stem-k-12/nsf25-545/solicitation",
    "/funding",
    "/funding/opportunities/sch-smart-health-biomedical-research-era-artificial-intelligence/nsf25-542/solicitation",
    "/funding/preparing-proposal",
    "/executive-orders",
    "/news/releases",
    "/funding/opportunities/vines-verticals-enabling-intelligent-network-systems/nsf25-539/solicitation",
    "/news/nsf-nvidia-partnership-enables-ai2-develop-fully-open-ai",
    "/funding/opportunities/pcl-test-bed-test-bed-toward-network-programmable-cloud-laboratories/nsf25-541/solicitation",
    "/funding/opportunities/stem-k-12-nsf-stem-k-12",
    "/funding/opportunities/sch-smart-health-biomedical-research-era-artificial-intelligence",
    "/news/nsf-invests-292-million-epscor-research-infrastructure",
    "/funding/graduate-students",
    "/bfa/dias/policy/nspm-33-implementation-guidance",
    "/funding/opportunities/vines-verticals-enabling-intelligent-network-systems",
    "/notices/important/important-notice-no-149-updates-nsf-research-security/in149",
    "/careers",
    "/funding/opportunities/career-faculty-early-career-development-program",
    "/funding/initiatives/reu/students",
    "/research-security/training",
    "/funding/opportunities/reu-research-experiences-undergraduates",
    "/tip/latest",
    "/policies/pappg/23-1/ch-2-proposal-preparation",
    "/funding/initiatives/i-corps",
    "/funding/early-career-researchers",
    "/funding/opportunities/pcl-test-bed-test-bed-toward-network-programmable-cloud-laboratories",
    "/awards/terms-conditions",
    "/funding/award-search",
    "/about/contact-us",
    "/funding/postdocs"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nsf.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}