module.exports = {
  "site": "https://www.weather.gov",
  "urls": [
    "/",
    "/wrh/timeseries",
    "/ajk/suicidebasin",
    "/wrh/climate",
    "/forecastmaps/",
    "/mpx/",
    "/tsa/",
    "/erh/ghwo",
    "/lot/",
    "/fwd/",
    "/mkx/",
    "/wrh/hazards",
    "/oun/",
    "/sju/",
    "/phi/",
    "/dmx/",
    "/ewx/",
    "/box/",
    "/eax/",
    "/lsx/",
    "/oax/",
    "/psr/",
    "/okx/",
    "/lwx/",
    "/sgf/",
    "/arx/",
    "/hgx/",
    "/dvn/",
    "/dlh/",
    "/bou/",
    "/fsd/",
    "/srh/tropical",
    "/sew/",
    "/ffc/",
    "/fgf/",
    "/bis/",
    "/ind/",
    "/pqr/",
    "/idp/ridge2landing",
    "/cle/",
    "/dtx/",
    "/grr/",
    "/jax/",
    "/alerts",
    "/iln/",
    "/sgx/",
    "/akq/",
    "/wrh/textproduct",
    "/gyx/",
    "/abrfc/pikespeak",
    "/buf/",
    "/abrfc/ratonpass",
    "/abrfc/granite",
    "/abrfc/lavetapass",
    "/abrfc/monarchpass",
    "/abrfc/fremontpass",
    "/tbw/",
    "/mhx/",
    "/ict/",
    "/ilx/",
    "/mfl/",
    "/mpx/weatherstory"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.weather.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 124,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}