module.exports = {
  "site": "https://www.neh.gov",
  "urls": [
    "/search",
    "/grants/listing",
    "/",
    "/program/humanities-research-centers-artificial-intelligence",
    "/grants",
    "/article/red-map-blue-map",
    "/grants/public/public-humanities-projects",
    "/news/neh-announces-reorganization-its-grantmaking-offices-programs-and-personnel",
    "/humanities/2014/marchapril/feature/the-first-americans",
    "/grants/research/fellowships",
    "/humanities/2017/winter/statement/the-rise-and-fall-and-rise-roy-orbison",
    "/article/1921-tulsa-massacre",
    "/news/neh-announces-3479-million-97-humanities-projects",
    "/about/awards/jefferson-lecture/arthur-miller-biography",
    "/grants/research/collaborative-research-grants",
    "/program/media-projects",
    "/article/story-1947-partition-told-people-who-were-there",
    "/program/rediscovering-our-revolutionary-tradition",
    "/article/caravaggio-was-other-michelangelo-renaissance",
    "/about",
    "/humanities/2015/novemberdecember/feature/the-talented-mr-huxley",
    "/article/trails-tears-plural-what-we-dont-know-about-indian-removal",
    "/program/celebrate-america",
    "/grants/research/public-scholar-program",
    "/humanities/2017/summer/feature/world-war-i-changed-america-and-transformed-its-role-in-international-relations",
    "/humanities/2015/marchapril/feature/how-the-grimm-brothers-saved-the-fairy-tale",
    "/article/irena-sendler-and-girls-kansas",
    "/AI",
    "/article/john-dewey-portrait-progressive-thinker",
    "/grants/preservation/preservation-assistance-grants-smaller-institutions",
    "/program/national-garden-american-heroes-statues",
    "/grants/preservation/national-digital-newspaper-program",
    "/grants/research/scholarly-editions-and-translations-grants",
    "/article/vast-early-america",
    "/article/all-history-revisionist-history",
    "/divisions/fedstate/resource/the-humanities-belong-everyone",
    "/grants/professional-development",
    "/article/atlas-drowned-towns",
    "/article/complicated-role-modern-public-library",
    "/about/awards/national-humanities-medals/virginia-driving-hawk-sneve",
    "/humanities/2018/winter/feature/texting-in-ancient-mayan-hieroglyphs",
    "/humanities/2018/spring/feature/rajneeshpuram-was-more-utopia-desert-it-was-mirror",
    "/article/how-america-became-city-upon-hill",
    "/article/jane-addams-hero-our-time",
    "/humanities/2014/marchapril/feature/the-trial-hannah-arendt",
    "/grants/preservation/sustaining-cultural-heritage-collections",
    "/article/martin-seligman-and-rise-positive-psychology",
    "/article/la-malinche-hernan-cortess-translator-and-so-much-more",
    "/article/records-salem-witch-trials",
    "/article/code-talkers-were-americas-secret-weapon-world-war-ii"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.neh.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}