module.exports = {
  "site": "https://www.ncpc.gov",
  "urls": [
    "//initiatives/moncore/",
    "//topics/transportation/",
    "/error/404.html",
    "/review/archive/2025/index/",
    "//maps/federal-facilities/",
    "//topics/security/",
    "//participate/events/",
    "//ar2024/",
    "//plans/framework/",
    "//topics/commemoration/",
    "//review/temporary_antenna/",
    "//plans/legacy/",
    "//policies/opengov/",
    "//subscribe/",
    "//about/faqs/",
    "//initiatives/treereplacement/",
    "//review/meeting101/",
    "//news/item/52/1/",
    "//plans/capitalspace/",
    "//news/item/53/",
    "//projects/8617/",
    "//news/item/251/3/",
    "//news/item/250/1/",
    "//news/1/",
    "//news/item/52/2/",
    "/error/404.html",
    "//about/authorities/hoba/",
    "//maps/pennsylvania-avenue/",
    "//ar2021/staff/",
    "//ar2022/pstats/",
    "//initiatives/antennas/",
    "//about/awards/",
    "//review/submit/",
    "//antenna/",
    "//projects/8351/",
    "//subscribe/tai/",
    "//ar2021/",
    "//ar2022/",
    "//projects/6694/",
    "//initiatives/workplace/",
    "//initiatives/penn/",
    "//policies/strategic/",
    "//ar2021/budget/",
    "//ar2022/budget/",
    "//news/item/53/4/",
    "//videos/",
    "//news/item/252/3/",
    "//initiatives/publicspace/",
    "//ar2021/commission/",
    "//ar2022/commission/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.ncpc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}