module.exports = {
  "site": "https://www.nps.gov",
  "urls": [
    "/blri/planyourvisit/conditions.htm",
    "/seki/planyourvisit/conditions.htm",
    "/acad/planyourvisit/conditions.htm",
    "/zion/planyourvisit/maps.htm",
    "/acad/planyourvisit/camping.htm",
    "/glac/planyourvisit/lodgingrestaurantsservices.htm",
    "/shen/planyourvisit/campgrounds.htm",
    "/lavo/index.htm",
    "/acad/planyourvisit/index.htm",
    "/perl/uss-arizona-memorial-programs.htm",
    "/dena/planyourvisit/conditions.htm",
    "/yell/planyourvisit/operating-dates.htm",
    "/whsa/index.htm",
    "/shen/planyourvisit/fees.htm",
    "/subjects/digital/nps-apps.htm",
    "/media/photo/view.htm",
    "/hosp/index.htm",
    "/crla/learn/photosmultimedia/webcams.htm",
    "/acad/planyourvisit/basicinfo.htm",
    "/drto/index.htm",
    "/seki/planyourvisit/campgrounds.htm",
    "/mora/planyourvisit/weather.htm",
    "/glac/planyourvisit/camping.htm",
    "/yose/planyourvisit/basicinfo.htm",
    "/wica/index.htm",
    "/deva/index.htm",
    "/inde/planyourvisit/independencehall.htm",
    "/seki/planyourvisit/index.htm",
    "/articles/000/hiking.htm",
    "/wica/planyourvisit/guidedtours.htm",
    "/planyourvisit/senior-pass-changes.htm",
    "/nama/learn/news/pike.htm",
    "/grsm/planyourvisit/index.htm",
    "/shen/planyourvisit/maps.htm",
    "/hale/planyourvisit/fees.htm",
    "/crla/planyourvisit/fees.htm",
    "/crla/planyourvisit/boat-and-trolley-tours.htm",
    "/meve/planyourvisit/cliff_dwelling_tours.htm",
    "/grca/planyourvisit/key-messages.htm",
    "/isro/index.htm",
    "/thro/index.htm",
    "/chis/index.htm",
    "/muwo/planyourvisit/know-before-you-go.htm",
    "/glac/planyourvisit/trailstatusreports.htm",
    "/grfa/index.htm",
    "/yell/planyourvisit/exploreoldfaithful.htm",
    "/grte/planyourvisit/maps.htm",
    "/asis/planyourvisit/conditions.htm",
    "/olym/planyourvisit/visiting-the-hoh.htm",
    "/features/ard/webcams/webcam2.html"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nps.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}