module.exports = {
  "site": "https://www.ncd.gov",
  "urls": [
    "/2024/04/09/ncd-announces-new-chair-claudia-l-gordon/",
    "/policy-areas/health-care/",
    "/report/beyond-guardianship-toward-alternatives-that-promote-greater-self-determination-for-people-with-disabilities/",
    "/report/improving-the-implementation-of-idea-making-schools-work-for-all-of-americas-children/",
    "/report/inclusionary-education-for-students-with-disabilities-keeping-the-promise/",
    "/accountability/",
    "/report/the-implicit-and-explicit-exclusion-of-people-with-disabilities-in-clinical-trials/",
    "/2015/05/05/forty-years-after-the-willowbrook-consent-decree-ncd-celebrates-how-far-we-ve-come/",
    "/report/assisted-suicide-a-disability-perspective-position-paper/",
    "/report/enforcing-the-civil-rights-of-air-travelers-with-disabilities-recommendations-for-the-department-of-transportation-and-congress/",
    "/report/youth-with-disabilities-in-the-foster-care-system-barriers-to-success-and-proposed-policy-solutions/",
    "/2023/09/26/ncd-celebrates-50-year-anniversary-of-rehabilitation-act-of-1973/",
    "/fact-sheets/",
    "/report/olmstead-reclaiming-institutionalized-lives/",
    "/report/the-impact-of-hurricanes-katrina-and-rita-on-people-with-disabilities-a-look-back-and-remaining-challenges/",
    "/accountability/government-performance-and-results-act-reports/",
    "/policy-areas/education/",
    "/report/disabled-parenting-toolkit/",
    "/report/from-fetal-surgery-to-gene-editing-the-current-and-potential-impact-of-prenatal-interventions-on-people-with-disabilities/",
    "/council-members/neil-romano/",
    "/report/incentivizing-oral-healthcare-providers-to-treat-patients-with-intellectual-and-developmental-disabilities/",
    "/2025/07/16/ncd-celebrates-ada-anniversary-with-policy-briefing-series/",
    "/accountability/congressional-budget-justification-reports/",
    "/resources/faq/",
    "/frameworks/",
    "/report/preserving-our-freedom-ending-institutionalization-of-people-with-disabilities-during-and-after-disasters/",
    "/report/improving-the-implementation-of-the-idea-making-schools-work-for-all-of-americas-children-supplement/",
    "/report/national-disability-policy-a-progress-report-january-1988/",
    "/report/transportation-update-where-weve-gone-and-what-weve-learned/",
    "/about/authorizing-statute/",
    "/report/understanding-disabilities-in-american-indian-alaska-native-communities-toolkit-guide/",
    "/meeting/2025-07-30-ada35-series-ground-transportation-for-people-with-mobility-disabilities-part-2/",
    "/council-members/shawn-kennemer/",
    "/feedback/",
    "/testimony/",
    "/report/individuals-with-disabilities-education-act-report-series-5-report-briefs/",
    "/letters/2025-04-07-letter-to-secretary-kennedy-regarding-maha-commission/",
    "/report/the-americans-with-disabilities-act-ensuring-equal-access-to-the-american-dream/",
    "/report/meeting-the-unique-needs-of-minorities-with-disabilities-a-report-to-the-president-and-the-congress/",
    "/report/tax-misclassification-lost-employment-benefits-for-disabled-workers/",
    "/2025/03/07/federal-report-reveals-tax-misclassification-of-workers-with-disabilities-depriving-employees-of-important-benefits-and-protections/",
    "/2019/10/09/federal-study-finds-nations-assisted-suicide-laws-rife-with-dangers-to-people-with-disabilities/",
    "/letters/2025-06-11-ncd-letter-to-doe-regarding-dfr-on-construction-requirements/",
    "/report/2020-progress-report-on-national-disability-policy-increasing-disability-employment/",
    "/report/medicaid-oral-health-coverage-for-adults-with-intellectual-developmental-disabilities-a-fiscal-analysis/",
    "/accountability/ncd-bylaws/",
    "/publications/",
    "/subscribe/",
    "/2024/12/19/national-council-on-disability-celebrates-10-years-of-able/",
    "/policy-areas/cultural-diversity/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.ncd.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}