module.exports = {
  "site": "https://www.ncpc.gov",
  "urls": [
    "//about/authorities/cca/",
    "//projects/7745/",
    "/error/404.html",
    "//projects/8449/",
    "//newsletters/may2025/",
    "//ar2020/",
    "/review/archive/2024/index/",
    "//projects/7610/",
    "//policies/vdp/",
    "//review/archive/2025/07-10/",
    "//policies/survey/",
    "//videos/586/12m33s",
    "//videos/570/",
    "/review/archive/2025/04-03/",
    "//maps/monumental-core-streetscape/",
    "//news/item/234/",
    "//news/item/254/1/",
    "//news/item/245/2/",
    "//news/item/132/",
    "//news/item/10/3/",
    "//review/guides/nepa/",
    "//ar2018/",
    "//participate/newsletters/",
    "//news/item/211/7/",
    "//maps/modernist-landscapes/",
    "//projects/7585/",
    "//news/item/11/3/",
    "//event/480/",
    "//notice/105/",
    "//maps/reimagining-downtown/",
    "//review/rguide/",
    "//maps/streetscape-boundary/",
    "//maps/consortium/",
    "//review/archive/2025/09-04/",
    "//about/authorities/nhpa/",
    "//news/item/21/3/",
    "//review/guidelines/exceptions/",
    "//maps/the-reserve/",
    "//about/authorities/fma/",
    "//about/authorities/review/",
    "//news/item/234/3/",
    "//news/item/223/1/",
    "//news/item/237/3/",
    "//news/item/235/3/",
    "//news/item/241/2/",
    "//news/item/209/1/",
    "//news/item/240/2/",
    "//news/item/243/2/",
    "//review/guides/memorials/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.ncpc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}