module.exports = {
  "site": "https://ncua.gov",
  "urls": [
    "/",
    "/regulation-supervision/letters-credit-unions-other-guidance",
    "/news/press-releases",
    "/news/enforcement-actions/administrative-orders",
    "/support-services/conservatorships-liquidations/unclaimed-deposits",
    "/search",
    "/support-services/conservatorships-liquidations/unclaimed-deposits/unclaimed-deposits-listing",
    "/analysis/credit-union-corporate-call-report-data",
    "/analysis/credit-union-corporate-call-report-data/quarterly-data",
    "/regulation-supervision/regulatory-compliance-resources/credit-union-artificial-intelligence-ai-resources",
    "/consumers/share-insurance-coverage",
    "/support-services/credit-union-resources-expansion/credit-union-merger-resources/comments-proposed-credit-union-mergers",
    "/subscribe",
    "/analysis",
    "/analysis/credit-union-corporate-call-report-data/financial-performance-reports",
    "/regulation-supervision",
    "/regulation-supervision/legal-opinions",
    "/regulation-supervision/rules-regulations",
    "/regulation-supervision/regulatory-reporting/cuonline",
    "/analysis/credit-union-corporate-call-report-data/quarterly-data-summary-reports",
    "/contact-us",
    "/consumers",
    "/support-services/conservatorships-liquidations",
    "/analysis/credit-union-corporate-call-report-data/call-report-forms-instructions-archive",
    "/about",
    "/support-services/share-insurance-fund",
    "/regulation-supervision/manuals-guides/examiners-guide",
    "/news/publications-reports",
    "/about/careers",
    "/about/leadership",
    "/newsroom/press-release/2025/ncua-disparate-impact-references-fair-lending-guide-and-other-materials",
    "/regulation-supervision/manuals-guides",
    "/newsroom/press-release/2025/ncua-seeks-credit-union-input-town-hall-september-9",
    "/regulation-supervision/examination-program/tips-starting-exam-efficiently",
    "/regulation-supervision/manuals-guides/federal-consumer-financial-protection-guide/compliance-management/unfair-deceptive-or-abusive-acts-or-practices-udaap",
    "/newsroom/press-release/2025/ncua-issues-two-prohibition-orders-and-one-consent-based-prohibition",
    "/consumers/share-insurance-coverage/frequently-asked-questions-about-share-insurance",
    "/news",
    "/newsroom/press-release/2025/members-first-maryland-federal-credit-union-closes-aberdeen-proving-ground-federal-credit-union",
    "/regulation-supervision/manuals-guides/federal-consumer-financial-protection-guide/compliance-management/lending-regulations/truth-lending-act-regulation-z",
    "/regulation-supervision/manuals-guides/federal-consumer-financial-protection-guide/compliance-management/deposit-regulations/expedited-funds-availability-act-regulation-cc",
    "/support-services",
    "/regulation-supervision/manuals-guides/federal-consumer-financial-protection-guide/deposit-related-regulations-and-statutes/electronic-fund-transfer-act-regulation-e",
    "/newsroom/press-release/2025/ncua-charters-african-diaspora-federal-credit-union",
    "/support-services/credit-union-resources-expansion/starting-new-federal-credit-union",
    "/about/historical-timeline",
    "/analysis/chartering-mergers/merger-activity-insurance-report",
    "/regulation-supervision/examination-program/credit-union-policy-reviews",
    "/news/events/2025/ncua-seeks-credit-union-input-town-hall-september-9",
    "/newsroom/press-release/2025/keith-morton-retires-ncua"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://ncua.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}