module.exports = {
  "site": "https://www.ncpc.gov",
  "urls": [
    "//news/",
    "//",
    "//news/item/249/3/",
    "//review/agenda/",
    "//maps/national-capital-region/",
    "//about/commission/",
    "//live/",
    "//search/go/",
    "//about/",
    "//review/meeting/",
    "//about/staff/",
    "//about/history/",
    "//projects/8543/",
    "//topics/nationalmall/",
    "//topics/embassies/",
    "//",
    "//participate/hybrid/",
    "//projects/8113/",
    "//topics/heights/",
    "//initiatives/pennave/",
    "//news/item/252/1/",
    "//review/archive/",
    "//review/guidelines/",
    "//participate/guidelines/",
    "//plans/compplan/",
    "//review/deadlines/",
    "//about/opportunities/",
    "//plans/memorials/",
    "//about/authorities/",
    "//news/item/250/3/",
    "//about/atoz/",
    "//topics/flooding/",
    "//news/item/54/7/",
    "//participate/notices/",
    "//review/calendar/",
    "//news/item/249/1/",
    "//review/overview/",
    "//plans/fcip/",
    "//news/item/249/",
    "//projects/8243/",
    "//initiatives/openspace/",
    "//participate/guide/",
    "//news/item/251/1/",
    "//initiatives/transportation/",
    "//projects/8450/",
    "//maps/historic-districts/",
    "//review/search/",
    "//projects/7746/",
    "//plans/swecodistrict/",
    "//review/guides/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.ncpc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}