module.exports = {
  "site": "https://ncua.gov",
  "urls": [
    "/newsroom/press-release/2025/ncua-issues-two-consent-based-prohibition-orders",
    "/regulation-supervision/letters-credit-unions-other-guidance/removal-disparate-impact",
    "/regulation-supervision/manuals-guides/other-supervisory-committee-audit-minimum-procedures-guide",
    "/regulation-supervision/manuals-guides/federal-consumer-financial-protection-guide/compliance-management/lending-regulations/military-lending-act-mla",
    "/analysis/credit-union-corporate-call-report-data/financial-trends-federally-insured-credit-unions",
    "/regulation-supervision/regulatory-compliance-resources",
    "/analysis/cuso-economic-data/credit-union-bank-rates",
    "/support-services/credit-union-resources-expansion",
    "/regulation-supervision/letters-credit-unions-other-guidance/loan-charge-guidance",
    "/regulation-supervision/letters-credit-unions-other-guidance/cyber-incident-notification-requirements",
    "/regulation-supervision/regulatory-compliance-resources/cecl-resources/simplified-cecl-tool",
    "/regulation-supervision/rulemakings-proposals-comment",
    "/regulation-supervision/regulatory-compliance-resources/cybersecurity-resources/acet-and-other-assessment-tools",
    "/support-services/credit-union-resources-expansion/credit-union-merger-resources",
    "/regulation-supervision/examination-modernization-initiatives/enterprise-solution-modernization-program/ncua-connect-merit/ncua-connect-faq",
    "/regulation-supervision/letters-credit-unions-other-guidance/ncuas-2025-supervisory-priorities",
    "/regulation-supervision/regulatory-compliance-resources/cybersecurity-resources",
    "/support-services/credit-union-resources-expansion/learning",
    "/news/events",
    "/analysis/credit-union-corporate-call-report-data/aggregate-financial-performance-reports",
    "/regulation-supervision/letters-credit-unions-other-guidance/evaluating-third-party-relationships-0",
    "/regulation-supervision/manuals-guides/federal-consumer-financial-protection-guide/compliance-management/lending-regulations/fair-credit-reporting-act-regulation-v",
    "/newsroom/press-release/2025/ncua-releases-second-quarter-2025-credit-union-system-performance-data",
    "/newsroom/press-release/2025/reminder-ncua-host-strategic-plan-town-hall-september-9",
    "/regulation-supervision/regulatory-reporting",
    "/about/careers/pay-benefits",
    "/regulation-supervision/letters-credit-unions-other-guidance/camels-rating-system",
    "/regulation-supervision/manuals-guides/federal-consumer-financial-protection-guide/compliance-management/deposit-regulations/electronic-signatures-global-and-national-commerce-act-e-sign-act",
    "/newsroom/press-release/2025/ncua-board-briefed-artificial-intelligence-post-exam-survey-results-and-central-liquidity-fund",
    "/news/downloadable-graphics",
    "/about/inspector-general",
    "/regulation-supervision/letters-credit-unions-other-guidance/consumer-harm-stemming-certain-overdraft-and-non-sufficient-funds-fee-practices",
    "/regulation-supervision/regulatory-compliance-resources/cecl-resources",
    "/about/mission-values",
    "/regulation-supervision/regulatory-compliance-resources/cybersecurity-resources/ncuas-regulations-and-guidance",
    "/news/board-meetings-agendas-results",
    "/regulation-supervision/regulatory-reporting/cuso-registry",
    "/analysis/credit-union-corporate-call-report-data/ncua-quarterly-us-map-review",
    "/news/enforcement-actions/administrative-orders/2025/administrative-order-matter-brian-socha",
    "/analysis/chartering-mergers",
    "/news",
    "/regulation-supervision/letters-credit-unions-other-guidance/concentration-risk",
    "/regulation-supervision/manuals-guides/federal-consumer-financial-protection-guide/compliance-management/lending-regulations/real-estate-settlement-procedures-act-regulation-x",
    "/regulation-supervision/regulatory-compliance-resources/cybersecurity-resources/ncuas-information-security-examination-and-cybersecurity-assessment",
    "/regulation-supervision/regulatory-compliance-resources/fraud-prevention-resources",
    "/news/speeches-testimonies",
    "/news/enforcement-actions/administrative-orders/2025/administrative-order-matter-shana-m-ware",
    "/analysis/cuso-economic-data/credit-union-bank-rates/credit-union-and-bank-rates-2025-q1",
    "/support-services/credit-union-resources-expansion/field-membership-expansion/low-income-credit-union-designation",
    "/news/enforcement-actions"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://ncua.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}