module.exports = {
  "site": "https://www.nsf.gov",
  "urls": [
    "/news/releases",
    "/funding/opportunities/satc-20-security-privacy-trust-cyberspace",
    "/funding/opportunities/sbirsttr-phase-i-nsf-small-business-innovation-research-small-business/nsf24-579/solicitation",
    "/funding/submitting-proposal",
    "/about",
    "/funding/opportunities/dcl-expanding-k-12-resources-ai-education",
    "/funding/opportunities/cps-cyber-physical-system-foundations-connected-communities",
    "/funding/undergraduates",
    "/tip/updates/nsf-halo-pilot",
    "/news/nsf-invests-nearly-32m-accelerate-novel-ai-driven-approaches",
    "/funding/opportunities/ritel-research-innovative-technologies-enhanced-learning",
    "/funding/opportunities/ecrcore-edu-core-research",
    "/news/nsf-announces-100-million-investment-national-artificial",
    "/funding/opportunities/iuse-edu-improving-undergraduate-stem-education-directorate-stem",
    "/funding/opportunities/reu-research-experiences-undergraduates/nsf23-601/solicitation",
    "/honorary-awards/paemst",
    "/funding/opportunities/ate-advanced-technological-education",
    "/policies/pappg/24-1/ch-1-pre-submission",
    "/news/nsf-national-quantum-virtual-laboratory-speeds-design-phase",
    "/funding/opportunities/s-stem-nsf-scholarships-science-technology-engineering-mathematics",
    "/funding/opportunities/eri-engineering-research-initiation",
    "/funding/opportunities/satc-20-security-privacy-trust-cyberspace/nsf25-515/solicitation",
    "/cise",
    "/funding/getting-started",
    "/news/nsf-invest-new-national-network-ai-programmable-cloud",
    "/policies/document/indirect-cost-rate",
    "/science-matters/horses-part-indigenous-cultures-longer-western",
    "/news/nsf-expanding-national-ai-infrastructure-new-data-systems",
    "/policies/pappg/24-1/ch-7-award-administration",
    "/careers/job-types",
    "/news/nsf-announces-funding-establish-national-ai-research",
    "/funding/opportunities/us-national-science-foundation-research-traineeship-program",
    "/edu",
    "/focus-areas/ai",
    "/policies/responsible-research-conduct",
    "/focus-areas",
    "/about/directorates-offices",
    "/funding/opportunities/ecrcore-edu-core-research/nsf21-588/solicitation",
    "/funding/opportunities/eri-engineering-research-initiation/nsf24-590/solicitation",
    "/funding/opportunities/sbirsttr-phase-i-nsf-small-business-innovation-research-small-business",
    "/news/nsf-invests-over-74-million-6-mathematical-sciences-research",
    "/funding/opportunities/cdse-computational-data-enabled-science-engineering",
    "/funding/opportunities/fire-fire-science-innovations-through-research-education",
    "/eng/programs",
    "/funding/opportunities/ate-advanced-technological-education/nsf24-584/solicitation",
    "/funding/opportunities/ritel-research-innovative-technologies-enhanced-learning/nsf23-624/solicitation",
    "/awards/report-your-outcomes",
    "/funding/learn/broader-impacts",
    "/focus-areas/ai/nairr",
    "/funding/opportunities/career-faculty-early-career-development-program/nsf22-586/solicitation"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nsf.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}