module.exports = {
  "site": "https://www.nps.gov",
  "urls": [
    "/yose/planyourvisit/conditions.htm",
    "/yose/planyourvisit/fees.htm",
    "/shen/index.htm",
    "/wamo/planyourvisit/fees.htm",
    "/civilwar/search-battle-units.htm",
    "/stli/planyourvisit/fees.htm",
    "/aboutus/entrance-fee-prices.htm",
    "/zion/planyourvisit/conditions.htm",
    "/features/ard/webcams/webcam1.html",
    "/stli/index.htm",
    "/yell/planyourvisit/conditions.htm",
    "/zion/planyourvisit/zion-canyon-shuttle-system.htm",
    "/glac/planyourvisit/fees.htm",
    "/grte/index.htm",
    "/olym/index.htm",
    "/zion/planyourvisit/angels-landing-hiking-permits.htm",
    "/yose/planyourvisit/maps.htm",
    "/acad/planyourvisit/maps.htm",
    "/glac/planyourvisit/mg-construction-2025.htm",
    "/media/article-search.htm",
    "/havo/learn/photosmultimedia/webcams.htm",
    "/grsm/planyourvisit/fees.htm",
    "/yose/planyourvisit/camping.htm",
    "/planyourvisit/maps.htm",
    "/havo/index.htm",
    "/crla/planyourvisit/conditions.htm",
    "/glac/planyourvisit/conditions.htm",
    "/common/utilities/sendmail/sendemail.cfm",
    "/asis/index.htm",
    "/redw/index.htm",
    "/glac/planyourvisit/maps.htm",
    "/grsm/planyourvisit/temproadclose.htm",
    "/media/photo/collection-item.htm",
    "/alca/planyourvisit/fees.htm",
    "/yell/learn/nature/hydrothermal-features.htm",
    "/arch/index.htm",
    "/muwo/index.htm",
    "/moru/index.htm",
    "/planyourvisit/index.htm",
    "/grsm/planyourvisit/maps.htm",
    "/yose/learn/photosmultimedia/webcams.htm",
    "/yose/planyourvisit/lodging.htm",
    "/romo/planyourvisit/maps.htm",
    "/grca/planyourvisit/fees.htm",
    "/aboutus/workwithus.htm",
    "/subjects/accessibility/interagency-access-pass.htm",
    "/grca/learn/photosmultimedia/webcams.htm",
    "/slbe/index.htm",
    "/havo/planyourvisit/eruption-viewing.htm",
    "/indu/index.htm"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nps.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}