module.exports = {
  "site": "https://www.neh.gov",
  "urls": [
    "/article/george-orwell-outdoorsman",
    "/humanities/2013/januaryfebruary/feature/faces-the-renaissance",
    "/impact",
    "/article/beatrix-potters-quiet-rebellion",
    "/humanities/2014/julyaugust/feature/how-did-cool-become-such-big-deal-0",
    "/grants/education/institutes-k-12-educators",
    "/humanities/2014/marchapril/feature/the-quiet-greatness-eudora-welty",
    "/about/national-council-on-the-humanities",
    "/about/foia/freedom-information-act-sample-grant-application-narratives",
    "/about/history",
    "/humanities/2015/mayjune/feature/virginia-woolf-was-more-just-womens-writer",
    "/executive-orders",
    "/article/ornament-world-and-jews-spain",
    "/project/transatlantic-slave-trade-database",
    "/news/summertime-favorites",
    "/grants/education/landmarks/k-12-educators",
    "/grants/research/fellowships-advanced-social-science-research-japan",
    "/article/frenemies-john-muir-and-gifford-pinchot",
    "/humanities/2014/mayjune/feature/the-face-science",
    "/humanities/2009/septemberoctober/feature/what-samuel-johnson-really-did",
    "/article/people-and-places-black-bottom-detroit",
    "/grants/workshops-resources-tools",
    "/humanities/2012/novemberdecember/feature/remarkable-radical-thaddeus-stevens",
    "/article/choctaw-confederates",
    "/initiatives",
    "/divisions/preservation/featured-project/encyclopedia-virginia",
    "/grants/preservation/preservation-and-access-education-and-training",
    "/about/contact",
    "/grants/manage",
    "/article/ursula-k-le-guin-was-creator-worlds",
    "/divisions-offices",
    "/humanities/2015/novemberdecember/statement/how-the-once-banned-spoon-river-anthology-made-comeback-i",
    "/news/reconstruction-vs-redemption",
    "/blog/history-aztecs-their-terms-qa-neh-public-scholar-camilla-townsend",
    "/humanities/2017/summer/statement/helvetia-traditional-swiss-village-in-the-hills-west-virginia",
    "/article/colonial-dames",
    "/article/how-civil-rights-movement-rewrote-freedom-press",
    "/blog/neh-public-humanities-projects-grants-which-level-funding-right-your-project",
    "/updates-neh-priorities",
    "/article/discovering-childhood",
    "/humanities/2018/winter/feature/the-thinker-who-believed-in-doing-0",
    "/about/human-resources/career-opportunities",
    "/humanities/2017/summer/curio/searching-the-true-origins-the-louvres-winged-victory",
    "/humanities/2017/summer/feature/historians-disagree-about-everything-or-so-it-seems",
    "/humanities/2018/summer/statement/thousands-years-ago-artists-painted-other-worldly-beings-canyon-rock-walls",
    "/news/neh-awards-272-million-create-ai-research-centers",
    "/humanities/2010/marchapril/feature/whaling-the-old-way",
    "/humanities/2017/spring/feature/louis-kahn-visionary-0",
    "/divisions/research",
    "/about/awards/national-humanities-medals/elie-wiesel"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.neh.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}