module.exports = {
  "site": "https://www.neh.gov",
  "urls": [
    "/article/rise-rapture-horror-culture",
    "/250",
    "/about/history/national-foundation-arts-and-humanities-act-1965-pl-89-209",
    "/about/neh-staff",
    "/article/dead-sea-scrolls",
    "/article/why-spinoza-was-excommunicated",
    "/humanities/2014/januaryfebruary/feature/culture-war",
    "/explore/the-papers-abraham-lincoln",
    "/grants/education/institutes-higher-education-faculty",
    "/humanities/2015/januaryfebruary/feature/what-music",
    "/news/voyages-the-transatlantic-slave-trade-database",
    "/article/mother-cabrini-first-american-saint-catholic-church",
    "/explore/chronicling-america-historic-american-newspapers",
    "/humanities/2018/spring/feature/georgia-okeeffe-paints-hawaii-0",
    "/program/humanities-initiatives-colleges-and-universities",
    "/humanities/2016/spring/statement/the-secret-lives-jean-seberg",
    "/humanities/2015/januaryfebruary/feature/what-sets-italian-americans-other-immigrants",
    "/program/save-americas-treasures",
    "/humanities/2009/novemberdecember/feature/ben-hur-the-book-shook-the-world",
    "/humanities/2018/summer/feature/the-messy-genius-w-h-auden",
    "/about/chair",
    "/humanities/2015/julyaugust/feature/treasure-island-author-robert-louis-stevenson-was-sickly-man-robu",
    "/article/wilmington-1898-unsupressed-history-massacre",
    "/news/students-decipher-2000-year-old-herculaneum-scrolls",
    "/humanities/2012/julyaugust/feature/lessons-demigod",
    "/article/rivers-held-spiritual-place-lives-cherokee",
    "/initiatives/international-opportunities",
    "/grants/application-process",
    "/article/fake-news-orson-welles-war-worlds-80",
    "/news/neh-announces-celebrate-america-grant-program-support-projects-commemorating-americas-250th",
    "/humanities/2015/septemberoctober/feature/king-tut-classic-blockbuster-museum-exhibition-began-diplom",
    "/news/update-neh-funding-priorities-and-agencys-recent-implementation-trump-administration-executive",
    "/humanities/2017/winter/feature/lot-what-known-about-pirates-not-true-and-lot-what-true-not-known",
    "/humanities/2015/novemberdecember/feature/who-were-the-pilgrims-who-celebrated-the-first-thanksgiving",
    "/article/lovers-and-soldiers",
    "/humanities/2014/marchapril/feature/hannah-andrew-jacksons-slave",
    "/humanities/2013/mayjune/feature/the-blue-humanities",
    "/news",
    "/grants/preservation/research-and-development",
    "/grants/preservation/humanities-collections-and-reference-resources",
    "/about/awards/jefferson-lecture/wendell-e-berry-biography",
    "/article/storming-bastille-led-democracy-not-long",
    "/article/strong-museum-explores-history-play",
    "/humanities/2017/summer/feature/tru-life",
    "/divisions/preservation/featured-project/tune-in-tuesdays-fox-movietone-news-collection",
    "/about/awards/national-humanities-medals/victor-davis-hanson",
    "/article/sweat-and-blood-fannie-lou-hamer",
    "/humanities/2009/marchapril/curio/the-white-pelican",
    "/humanities/2014/julyaugust/feature/reading-laura-ingalls-wilder-not-the-same-when-youre-parent",
    "/blog/plymouth-colony-and-beginnings-liberty-america-qa-neh-public-scholar-john-turner"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.neh.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}