module.exports = {
  "site": "https://www.nhc.noaa.gov",
  "urls": [
    "/",
    "/gtwo.php",
    "/graphics_at5.shtml",
    "/cyclones/",
    "/satellite.php",
    "/refresh/graphics_at5+shtml/111444.shtml",
    "/refresh/graphics_at5+shtml/121447.shtml",
    "/refresh/graphics_at5+shtml/120843.shtml",
    "/refresh/graphics_at5+shtml/141435.shtml",
    "/refresh/graphics_at5+shtml/131434.shtml",
    "/refresh/graphics_at5+shtml/130842.shtml",
    "/graphics_at1.shtml",
    "/refresh/graphics_at5+shtml/140846.shtml",
    "/refresh/graphics_at5+shtml/122032.shtml",
    "/refresh/graphics_at5+shtml/112043.shtml",
    "/refresh/graphics_at5+shtml/132034.shtml",
    "/refresh/graphics_at5+shtml/161731.shtml",
    "/refresh/graphics_at1+shtml/232043.shtml",
    "/refresh/graphics_at5+shtml/181152.shtml",
    "/refresh/graphics_at5+shtml/151446.shtml",
    "/refresh/graphics_at5+shtml/161520.shtml",
    "/refresh/graphics_at5+shtml/171150.shtml",
    "/refresh/graphics_at5+shtml/162348.shtml",
    "/refresh/graphics_at5+shtml/161152.shtml",
    "/refresh/graphics_at5+shtml/191156.shtml",
    "/archive/xgtwo/gtwo_archive.php",
    "/refresh/graphics_at5+shtml/181749.shtml",
    "/refresh/graphics_at5+shtml/180835.shtml",
    "/refresh/graphics_at5+shtml/172349.shtml",
    "/refresh/graphics_at5+shtml/151736.shtml",
    "/refresh/graphics_at5+shtml/182044.shtml",
    "/refresh/graphics_at5+shtml/172036.shtml",
    "/refresh/graphics_at5+shtml/191453.shtml",
    "/graphics_ep1.shtml",
    "/refresh/graphics_at5+shtml/151156.shtml",
    "/refresh/graphics_at5+shtml/162127.shtml",
    "/refresh/graphics_at5+shtml/191737.shtml",
    "/refresh/graphics_at5+shtml/190856.shtml",
    "/refresh/graphics_at5+shtml/142043.shtml",
    "/refresh/graphics_at5+shtml/201153.shtml",
    "/refresh/graphics_at5+shtml/152042.shtml",
    "/refresh/graphics_at5+shtml/171739.shtml",
    "/refresh/graphics_at5+shtml/171457.shtml",
    "/refresh/graphics_at5+shtml/170846.shtml",
    "/refresh/graphics_at5+shtml/181540.shtml",
    "/refresh/graphics_at5+shtml/192038.shtml",
    "/refresh/graphics_at5+shtml/150843.shtml",
    "/refresh/graphics_at5+shtml/142352.shtml",
    "/refresh/graphics_at5+shtml/182354.shtml",
    "/refresh/graphics_at5+shtml/201454.shtml",
    "/refresh/graphics_at5+shtml/152350.shtml",
    "/refresh/graphics_at5+shtml/201737.shtml",
    "/marine/",
    "/refresh/graphics_at5+shtml/200851.shtml",
    "/refresh/graphics_at5+shtml/160951.shtml",
    "/refresh/graphics_at5+shtml/202036.shtml",
    "/refresh/graphics_at5+shtml/192357.shtml",
    "/refresh/graphics_at5+shtml/130236.shtml",
    "/",
    "/refresh/graphics_at5+shtml/170258.shtml",
    "/analysis_tools.php",
    "/refresh/graphics_at5+shtml/120233.shtml",
    "/refresh/graphics_at5+shtml/140237.shtml",
    "/refresh/graphics_at5+shtml/211153.shtml",
    "/refresh/graphics_at5+shtml/180254.shtml",
    "/refresh/graphics_at5+shtml/202351.shtml",
    "/refresh/graphics_at5+shtml/210846.shtml",
    "/graphics_ep2.shtml",
    "/refresh/graphics_at5+shtml/138150.shtml",
    "/refresh/graphics_at5+shtml/190233.shtml",
    "/refresh/graphics_at5+shtml/150247.shtml",
    "/refresh/graphics_at5+shtml/220843.shtml",
    "/refresh/graphics_at5+shtml/161432.shtml",
    "/refresh/graphics_at5+shtml/160256.shtml",
    "/refresh/graphics_at5+shtml/211443.shtml",
    "/graphics_ep4.shtml"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nhc.noaa.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 152,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}