module.exports = {
  "site": "https://www.arts.gov",
  "urls": [
    "/news/press-releases",
    "/blue-star-museums-map",
    "/",
    "/stories/blog/list",
    "/stories/posts",
    "/grants/grants-for-arts-projects",
    "/search",
    "/grants",
    "/initiatives/blue-star-museums",
    "/stories/podcast/list",
    "/about/publications",
    "/stories/blog/2024/federal-data-reading-pleasure-all-signs-show-slump",
    "/impact/research/publications",
    "/grants/creative-writing-fellowships",
    "/initiatives/blue-star-museums/frequently-asked-questions",
    "/stories/blog/2023/ten-things-you-might-not-know-about-1964-tv-series-addams-family",
    "/stories/blog/2015/why-arts-matter",
    "/honors/medals/ray-bradbury",
    "/grants/manage-your-award",
    "/grants/first-time-applicant-guide-for-organizations",
    "/about/leadership-staff",
    "/grants/our-town",
    "/grants/recent-grants/literature-fellowships",
    "/grants/recent-grants",
    "/stories/blog/2025/men-women-split-reading-real-and-persists-amid-historical-rate-declines",
    "/grants/partnership-agreement-grants",
    "/stories/blog/2025/educating-ourselves-about-childhood-arts-experiences-and-why-they-matter",
    "/initiatives/nea-big-read",
    "/initiatives/creative-forces",
    "/grants/national-garden-of-heroes",
    "/stories/blog/2015/quilts-gees-bend-slideshow",
    "/about",
    "/news/press-releases/2025/arts-and-cultural-industries-grew-twice-rate-us-economy-adding-12-trillion",
    "/impact/literary-arts/creative-writing-fellows",
    "/grants/manage-your-award/awards-to-organizations-forms-and-guidance",
    "/grants/challenge-america",
    "/grants/manage-your-award/nea-logo",
    "/about/leadership-staff/national-council-arts",
    "/honors/jazz/list",
    "/grants/research-awards",
    "/initiatives/nea-big-read/things-they-carried",
    "/stories/blog/2020/ten-things-you-might-not-know-about-grapes-wrath",
    "/impact/research/publications/jumpstarting-artist-jobs-case-studies-us-employment-programs-creative-workers",
    "/grants/priorities",
    "/honors/heritage",
    "/about/what-is-the-nea",
    "/state-and-regional-arts-organizations",
    "/stories/blog/2024/ten-things-you-may-not-know-about-james-baldwin",
    "/initiatives/nea-big-read/homegoing",
    "/impact/research"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.arts.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}