module.exports = {
  "site": "https://www.ncd.gov",
  "urls": [
    "/",
    "/meeting/2025-08-28-aug-28-29-2025-council-meeting/",
    "/public-comment/",
    "/2025/06/13/ncd-advises-doe-on-rulemaking-impacting-people-with-disabilities/",
    "/resources/",
    "/newsroom/",
    "/report/ground-transportation-for-people-with-mobility-disabilities-2025-challenges-and-progress/",
    "/report/equality-of-opportunity-the-making-of-the-americans-with-disabilities-act/",
    "/about-us/",
    "/council-members/",
    "/fact%20sheets/2006/06/01/common-myths-about-diversity-and-cultural-competency/",
    "/2025/07/23/ncd-report-examines-ground-transportation-barriers-for-americans-with-disabilities/",
    "/report/students-with-disabilities-face-financial-aid-barriers/",
    "/2025/08/20/ncd-seeks-public-comment-during-may-29-council-meeting/",
    "/contact/",
    "/2025/08/14/ncd-seeks-applicants-for-part-time-pca-position/",
    "/staff/",
    "/report/2023-progress-report-toward-economic-security-the-impact-of-income-and-asset-limits-on-people-with-disabilities/",
    "/2015/04/23/ncd-response-to-controversial-peter-singer-interview-advocating-the-killing-of-disabled-infants-professor-do-your-homework/",
    "/meeting/2025-08-13-ada35-series-ground-transportation-for-people-with-mobility-disabilities-part-5/",
    "/meeting/2025-08-13-ada35-series-ground-transportation-for-people-with-mobility-disabilities-part-4/",
    "/report/framework-to-end-health-disparities-of-people-with-disabilities/",
    "/meeting/2025-08-06-ada35-series-ground-transportation-for-people-with-mobility-disabilities-part-3/",
    "/report/national-disability-policy-a-progress-report-february-1986/",
    "/2025/08/14/ncd-holds-next-council-meeting-aug-28-29-in-washington-dc/",
    "/newsroom/press-release/",
    "/report/rocking-the-cradle-ensuring-the-rights-of-parents-with-disabilities-and-their-children/",
    "/report/voices-of-freedom-america-speaks-out-on-the-americans-with-disabilities-act/",
    "/meeting/2025-08-27-ada35-series-ground-transportation-for-people-with-mobility-disabilities-part-6/",
    "/reports/",
    "/policy-areas/transportation/",
    "/meetings/",
    "/council-members/theo-w-braddy/",
    "/progress-reports/",
    "/meeting/2025-07-23-ada35-series-ground-transportation-for-people-with-mobility-disabilities-part-1/",
    "/2014/12/01/ncd-statement-on-the-passing-of-mary-ann-mobley-collins/",
    "/report/wilderness-accessibility-for-people-with-disabilities-a-report-to-the-president-and-the-congress-of-the-united-states-on-section-507-a-of-the-americans-with-disabilities-act/",
    "/report/the-education-of-students-with-disabilities-where-do-we-stand/",
    "/report/national-disability-policy-a-progress-report-2024/",
    "/accountability/eeo-policy-statement/",
    "/toolkits/",
    "/policy-areas/civil-rights/",
    "/report/study-on-the-financing-of-assistive-technology-devices-and-services-for-individuals-with-disabilities/",
    "/policy-areas/employment/",
    "/report/an-extra/",
    "/report/breaking-the-school-to-prison-pipeline-for-students-with-disabilities/",
    "/2015/11/24/ncd-statement-on-the-40th-anniversary-of-idea/",
    "/letters/",
    "/report/quality-adjusted-life-years-and-the-devaluation-of-life-with-a-disability/",
    "/report/the-danger-of-assisted-suicide-laws/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.ncd.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}