module.exports = {
  "site": "https://www.nlrb.gov",
  "urls": [
    "/search/case/collins%20aerospace",
    "/cases-decisions/decisions/unpublished-board-decisions",
    "/reports/graphs-data/recent-filings/date_filed/desc/100",
    "/about-nlrb/who-we-are/careers",
    "/guidance/memos-research/operations-management-memos",
    "/news-outreach/news-story/board-rules-that-employers-may-not-offer-severance-agreements-requiring",
    "/about-nlrb/rights-we-protect/the-law/secondary-boycotts-section-8b4",
    "/about-nlrb/rights-we-protect/our-enforcement-activity/protected-concerted-activity",
    "/guidance/memos-research/advice-memos",
    "/about-nlrb/rights-we-protect/the-law/employees/social-media-0",
    "/about-nlrb/rights-we-protect/the-law/collective-bargaining-section-8d-8b3",
    "/cases-decisions/decisions",
    "/about-nlrb/rights-we-protect/the-law/discriminating-against-employees-because-of-their-union",
    "/about-nlrb/rights-we-protect/the-law/employees/how-to-enforce-your-rights-0",
    "/about-nlrb/what-we-do/the-standard-for-determining-joint-employer-status-final-rule",
    "/resources/faq",
    "/about-nlrb/who-we-are/organization-chart",
    "/bio/general-counsel",
    "/case-related-map",
    "/cases-decisions/decisions/notable-board-decisions",
    "/about-nlrb/who-we-are/careers/job-descriptions-and-listings/student-volunteer-program",
    "/about-nlrb/rights-we-protect/the-law/employees/right-to-strike-and-picket",
    "/about-nlrb/who-we-are/regional-offices/region-02-new-york",
    "/bio/marvin-e-kaplan",
    "/cases-decisions/cases/research",
    "/about-nlrb/what-we-do/introduction-to-the-nlrb",
    "/news-outreach/news-story/board-rules-captive-audience-meetings-unlawful",
    "/contact-us/headquarters-directory",
    "/field-office-status",
    "/about-nlrb/rights-we-protect/your-rights/interference-with-employee-rights",
    "/about-nlrb/who-we-are/regional-offices/region-10-atlanta",
    "/about-nlrb/who-we-are/regional-offices/region-13-chicago",
    "/reports/agency-performance/election-reports",
    "/about-nlrb/who-we-are/regional-offices/region-01-boston",
    "/es",
    "/news-outreach/news-story/board-rules-workplace-policies-limiting-wearing-union-insignia-including",
    "/reports/nlrb-case-activity-reports/representation-cases/intake/decertification-petitions-rd",
    "/reports/nlrb-case-activity-reports/representation-cases/intake/representation-petitions-rc",
    "/about-nlrb/who-we-are/the-board/members-of-the-nlrb-since-1935",
    "/case/09-rc-358016",
    "/bio/gwynne-a-wilcox",
    "/search/all",
    "/about-nlrb",
    "/news-outreach/news-story/board-issues-decision-in-browning-ferris-industries",
    "/about-nlrb/who-we-are/our-history/1935-passage-of-the-wagner-act",
    "/bio/david-m-prouty",
    "/about-nlrb/who-we-are/careers/honors-program",
    "/reports/nlrb-case-activity-reports/unfair-labor-practice-cases",
    "/about-nlrb/who-we-are/regional-offices/region-28-phoenix",
    "/about-nlrb/who-we-are/regional-offices/region-07-detroit"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nlrb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}