module.exports = {
  "site": "https://www.nps.gov",
  "urls": [
    "/media/webcam/view.htm",
    "/index.htm",
    "/civilwar/search-soldiers.htm",
    "/planyourvisit/pickup-pass-locations.htm",
    "/features/ard/currentdatawidget/recent-dataw.html",
    "/findapark/index.htm",
    "/planyourvisit/passes.htm",
    "/aboutus/entrance-fee-prices.htm",
    "/media/photo/gallery.htm",
    "/yose/index.htm",
    "/dena/learn/photosmultimedia/webcams-pups.htm",
    "/yell/learn/photosmultimedia/webcams.htm",
    "/planyourvisit/pickup-pass-locations.htm",
    "/yell/index.htm",
    "/planyourvisit/event-details.htm",
    "/civilwar/search-soldiers.htm",
    "/romo/planyourvisit/timed-entry-permit-system.htm",
    "/yose/planyourvisit/reservations.htm",
    "/findapark/index.htm",
    "/glac/index.htm",
    "/acad/planyourvisit/fees.htm",
    "/romo/index.htm",
    "/glac/learn/photosmultimedia/webcams.htm",
    "/acad/index.htm",
    "/grsm/planyourvisit/conditions.htm",
    "/glac/planyourvisit/vehicle-reservations.htm",
    "/subjects/air/webcams.htm",
    "/maca/planyourvisit/cave-tours.htm",
    "/mora/learn/photosmultimedia/webcams.htm",
    "/yell/planyourvisit/geyser-activity.htm",
    "/grca/northrimstatus.htm",
    "/media/photo/gallery-item.htm",
    "/media/video/view.htm",
    "/grsm/index.htm",
    "/zion/index.htm",
    "/grca/index.htm",
    "/yell/planyourvisit/fees.htm",
    "/seki/index.htm",
    "/mora/planyourvisit/timed-entry-reservations.htm",
    "/media/multimedia-search.htm",
    "/blri/planyourvisit/roadclosures.htm",
    "/acad/planyourvisit/vehicle_reservations.htm",
    "/mora/index.htm",
    "/romo/planyourvisit/fees.htm",
    "/grca/planyourvisit/grand-canyon-national-park-public-health-update.htm",
    "/mora/planyourvisit/fees.htm",
    "/maca/index.htm",
    "/yell/planyourvisit/maps.htm",
    "/media/photo/collection.htm",
    "/crla/index.htm"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nps.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}