module.exports = {
  "site": "https://www.nlrb.gov",
  "urls": [
    "/about-nlrb/rights-we-protect/your-rights/your-rights-to-discuss-wages",
    "/about-nlrb/rights-we-protect/your-rights/employer-union-rights-and-obligations",
    "/about-nlrb/rights-we-protect/your-rights/weingarten-rights",
    "/guidance/fillable-forms",
    "/cases-decisions",
    "/about-nlrb/rights-we-protect/the-law/interfering-with-employee-rights-section-7-8a1",
    "/resources/faq/nlrb",
    "/strikes",
    "/guidance/key-reference-materials/manuals-and-guides",
    "/cases-decisions/decisions/administrative-law-judge-decisions",
    "/about-nlrb/rights-we-protect/the-law",
    "/about-nlrb/rights-we-protect/your-rights/employee-rights",
    "/about-nlrb/what-we-do/investigate-charges",
    "/about-nlrb/rights-we-protect/the-law/bargaining-in-good-faith-with-employees-union-representative",
    "/about-nlrb/who-we-are",
    "/about-nlrb/rights-we-protect/the-law/jurisdictional-standards",
    "/search/case/marriott",
    "/news-outreach/news-story/nlrb-acting-general-counsel-issues-guidance-for-deferring-unfair-labor",
    "/guidance/key-reference-materials/rules-regulations",
    "/search/case/ge%20aerospace",
    "/about-nlrb/rights-we-protect/the-law/employees/your-right-to-form-a-union",
    "/about-nlrb/rights-we-protect/the-law/employees/union-dues",
    "/about-nlrb/rights-we-protect/the-law/employees/your-rights-during-union-organizing",
    "/news-publications",
    "/cases-decisions/cases/cases-and-organizations-interest",
    "/news-outreach/news-story/acting-general-counsel-statement-on-potential-state-legislation-regulating",
    "/cases-decisions/filing",
    "/about-nlrb/who-we-are/the-board",
    "/about-nlrb/rights-we-protect/the-law/employees/concerted-activity",
    "/search/case/lc%20industries",
    "/about-nlrb/rights-we-protect/the-law/employees/decertification-election",
    "/about-nlrb/rights-we-protect/the-law/employees/collective-bargaining-rights",
    "/about-nlrb/what-we-do/conduct-elections",
    "/about-nlrb/what-we-do",
    "/resources/nlrb-process",
    "/guidance/freedom-of-information-act-foia",
    "/about-nlrb/rights-we-protect/the-law/employees/right-to-fair-representation",
    "/cases-decisions/cases",
    "/guidance/e-filing-service-desk",
    "/last-two-weeks-activity",
    "/about-nlrb/rights-we-protect/your-rights",
    "/about-nlrb/rights-we-protect/whats-law",
    "/about-nlrb/who-we-are/our-history/1947-taft-hartley-substantive-provisions",
    "/case/01-cb-369112",
    "/guidance/key-reference-materials/steps-for-filing-a-petition",
    "/es/search/case",
    "/cases-decisions/decisions/regional-election-decisions",
    "/search/case/starbucks",
    "/about-nlrb/rights-we-protect",
    "/news-publications/publications/employee-rights-notice-posting"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nlrb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}