module.exports = {
  "site": "https://www.arts.gov",
  "urls": [
    "/impact/creative-placemaking",
    "/honors/heritage/list",
    "/sign-up-for-updates",
    "/about/leadership-staff/senior-staff",
    "/impact/arts-and-health",
    "/grants/legal-requirements-and-assurance-of-compliance/frequently-asked-questions",
    "/about/leadership-staff/employment",
    "/initiatives/nea-big-read/house-mango-street",
    "/about/freedom-of-information-act-foia-guide",
    "/stories/blog/2023/explore-ekphrastic-poems-reading-list",
    "/grants/translation-project-fellowships",
    "/initiatives",
    "/grants/manage-your-award/how-to-access-your-award-in-reach",
    "/grants/grants-for-arts-projects/applicant-resources",
    "/stories/magazine/2016/1/telling-all-our-stories-arts-and-diversity/lin-manuel-miranda",
    "/form/volunteer-to-be-a-national-endowment-for-the-arts-panelist",
    "/initiatives/blue-star-museums/2025-registration",
    "/initiatives/nea-big-read/there-there",
    "/initiatives/poetry-out-loud",
    "/impact/state-profiles",
    "/grants/grant-review-process",
    "/initiatives/nea-big-read/their-eyes-were-watching-god",
    "/news/press-releases/2025/national-endowment-arts-announces-2025-nea-national-heritage-fellows",
    "/honors/medals/list",
    "/honors/medals",
    "/news/press-releases/2024/national-endowment-arts-announces-second-round-grants-fy-2024",
    "/honors/jazz/miles-davis",
    "/grants/legal-requirements-and-assurance-of-compliance",
    "/impact/research/publications/arts-education-us-public-schools-insights-november-2024-school-pulse-panel-survey",
    "/initiatives/nea-big-read/fahrenheit-451",
    "/impact/accessibility",
    "/honors/jazz",
    "/stories/video/nea-big-read-meet-ernest-gaines",
    "/grants/manage-your-award/awards-to-organizations-final-reporting",
    "/impact/literary-arts/translation-fellows",
    "/news/press-releases/2025/national-endowment-arts-statement-death-nea-jazz-master-sheila-jordan",
    "/grants/grants-for-arts-projects/frequently-asked-questions-0",
    "/stories/blog/2021/celebrate-native-american-heritage-month-poetry",
    "/about/civil-rights-office/applicants-recipients-of-federal-financial-assistance/section-504-self-evaluation-workbook",
    "/back-school-arts-education",
    "/honors/jazz/eddie-palmieri",
    "/impact",
    "/initiatives/nea-research-labs/all-nea-research-labs",
    "/stories/blog/2020/ten-things-know-about-charles-dickens-christmas-carol",
    "/stories/blog/2024/facts-you-may-not-know-about-martin-luther-king-jr-national-memorial",
    "/grants/manage-your-award/state-and-regional-partnership-agreement-awards",
    "/stories/magazine",
    "/stories/blog/2024/poems-gratitude",
    "/news/press-releases/2024/new-research-explores-arts-engagement-and-social-connectedness",
    "/initiatives/nea-big-read/time-butterflies"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.arts.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}