module.exports = {
  "site": "https://www.ncpc.gov",
  "urls": [
    "//participate/edrs/",
    "//review/archive/2025/index/",
    "//ar2022/staff/",
    "//maps/foreign-missions/",
    "//news/item/52/16/",
    "//review/project/8113/",
    "//videos/535",
    "//newsletters/july2025/",
    "//maps/lenfant-city/",
    "//participate/media/",
    "//policies/",
    "//policies/nofear/",
    "//projects/7819/",
    "//projects/7630/",
    "//policies/privacy/",
    "//maps/central-employment-area/",
    "//maps/floodplains/",
    "//maps/",
    "//initiatives/subnepa.html",
    "//ar2019/",
    "//maps/capper-cramton/",
    "/review/archive/2025/07-10/",
    "//projects/7682/",
    "//participate/schedule/",
    "//maps/shipstead-luce/",
    "//projects/7532/",
    "//videos/638/15m04s",
    "//news/item/52/3/",
    "//initiatives/swecodistrict/",
    "/error/404.html",
    "//news/2/",
    "//maps/memorials-museums/",
    "//projects/8282/",
    "//maps/historic-landmarks/",
    "//news/3/",
    "//news/item/8/3/",
    "//policies/accessibility/",
    "//policies/foia/",
    "//policies/performance/",
    "/review/archive/2025/06-05/",
    "//about/authorities/nepa/",
    "//news/item/246/1/",
    "//news/item/253/1/",
    "//maps/swecodistrict/",
    "//maps/central-core/",
    "//news/item/102/",
    "//search/go/common",
    "//sitemap/",
    "//videos/637/48m04s/",
    "/review/archive/2025/05-01/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.ncpc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}