module.exports = {
  "site": "https://www.nwtrb.gov",
  "urls": [
    "/",
    "/our-work/correspondence",
    "/about-us/members",
    "/meetings/upcoming-public-meetings",
    "/our-work/press-releases",
    "/meetings/past-meetings",
    "/our-work/reports",
    "/about-us/staff",
    "/meetings/upcoming-public-meetings/summer-2025-board-meeting---august-27--2025",
    "/scope/nuclear-repositories",
    "/news/2025/08/07/board-letter-to-roger-jarrell---august-7--2025",
    "/news/2025/07/25/press-release---summer-2025-board-meeting---august-29--2025",
    "/sign-up",
    "/our-work/testimony",
    "/about-us/plans",
    "/our-work/fact-sheets",
    "/search",
    "/about-us/members/peter-swift-ph-d",
    "/our-work/correspondence/board-letter-to-dr.-kathryn-huff---august-12-2021",
    "/job-openings",
    "/meetings/past-meetings/summer-2024-board-meeting---august-29--2024",
    "/about-us/mission",
    "/scope/u-s-radioactive-waste",
    "/our-work/correspondence/board-letter-to-roger-jarrell---august-7--2025",
    "/home/contact-us",
    "/news",
    "/meetings/past-meetings/3",
    "/nwtrb-foia-pa",
    "/scope/transportation",
    "/scope/geologic-disposal",
    "/scope/packaging-and-storage",
    "/home/contact-us/",
    "/meetings/past-meetings/spring-2021-board-virtual-meeting---may-12-13-2021",
    "/our-work/correspondence/board-letter-to-dr.-michael-goff-(june-9--2025)",
    "/our-work/correspondence/6",
    "/our-work/reports/evaluation-of-the-department-of-energy's-research-program-to-examine-the-performance-of-commercial-high-burnup-spent-nuclear-fuel-during-extended-storage-and-transportation-(july-2021)",
    "/our-work/reports/evaluation-of-the-u.s.-department-of-energy-research-and-development-activities-on-the-disposition-of-commercial-spent-nuclear-fuel-in-dual-purpose-canisters-(february-2024)",
    "/our-work/reports/proceedings-of-the-board's-2023-international-workshop-on-siting-of-radioactive-waste-facilities",
    "/our-work/reports/report-to-the-u.s.-congress-and-the-secretary-of-energy---board-activities-for-the-period-january-1-2019---december-31-2021-(november-2021)",
    "/our-work/press-releases/summer-2025-board-meeting---august-27--2024",
    "/our-work/reports/designing-a-process-for-selecting-a-site-for-a-deep-mined-geologic-repository-for-high-level-radioactive-waste-and-spent-nuclear-fuel-an-overview-and-summary-(2015)",
    "/privacy-policy",
    "/our-work/fact-sheets/spent-nuclear-fuel-and-high-level-radioactive-waste-in-the-united-states",
    "/our-work/reports/technical-evaluation-of-the-u.s.-department-of-energy-deep-borehole-disposal-research-and-development-program-(2016)",
    "/news/2025/06/09/board-letter-to-dr.-michael-goff-(june-9--2025)",
    "/our-work/correspondence/1",
    "/our-work/correspondence/letter-from-dr.-kathryn-huff-to-the-board---august-21-2023",
    "/our-work/correspondence/letter-from-dr.-kathryn-huff-to-the-board---july-5-2023",
    "/about-us",
    "/vulnerability-disclosure-policy"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nwtrb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}