module.exports = {
  "site": "https://www.nwtrb.gov",
  "urls": [
    "/our-work/correspondence/letter-from-dr.-kathryn-huff-to-the-board---june-8-2022",
    "/news/2024/09/09/new-feature---table-of-repository-programs",
    "/nwtrb-no-fear-act",
    "/our-work/reports/nuclear-waste-assessment-system-for-technical-evaluation-(nuwaste)-status-and-initial-results-(2011)",
    "/meetings/past-meetings/1",
    "/our-work/reports/report-to-the-u.s.-congress-and-the-secretary-of-energy---board-activities-for-the-period-january-1-2013---december-31-2015---december-2016",
    "/meetings/past-meetings/spring-2019-workshop-april-24-25-2019",
    "/meetings/past-meetings/summer-2018-board-meeting---june-13-2018",
    "/meetings/past-meetings/summer-2023-workshop---august-29-2023",
    "/our-work/reports/technical-advancements-and-issues-associated-with-the-permanent-disposal-of-high-activity-wastes-lessons-learned-from-yucca-mountain-and-other-programs-(2011)",
    "/our-work/press-releases/u.s.-nwtrb-releases-report-on-commercial-high-burnup-spent-nuclear-fuel-performance-during-extended-storage-and-transportation",
    "/our-work/press-releases/u.s.-nwtrb-to-hold-international-workshop-on-siting-of-radioactive-waste-facilities",
    "/meetings/past-meetings/winter-2016-board-meeting---february-17-2016",
    "/meetings/past-meetings/2013-board-technical-workshop",
    "/home/2025/05/22/board-letter-to-dr.-michael-goff-(may-22--2025)",
    "/news/2025/05/22/board-letter-to-dr.-michael-goff-(may-22--2025)",
    "/our-work/press-releases/board-release-report-updating-its-survey-of-national-programs-for-managing-hlw-and-snf",
    "/our-work/correspondence/board-letter-to-dr.-peter-lyons---may-28-2013",
    "/our-work/fact-sheets/calcined-high-level-radioactive-waste",
    "/our-work/fact-sheets/chloride-induced-stress-corrosion",
    "/our-work/fact-sheets/commercial-spent-nuclear-fuel",
    "/our-work/correspondence/3",
    "/our-work/press-releases/doe-efforts-related-to-removing-spent-nuclear-fuel-from-commercial-nuclear-power-plant-sites-are-focus-of-u.s.-nwtrb-meeting---february-23-2023",
    "/our-work/press-releases/doe-r-d-on-clay-bearing-host-rocks-and-clay-based-engineered-barriers-is-focus-of-u.s.-nwtrb-meeting-in-arlington-va",
    "/our-work/press-releases/doe's-r-d-on-crystalline-host-rocks-and-on-corrosion-of-commercial-spent-nuclear-fuel-after-disposal-are-focus-of-u.s.-nwtrb-meeting-(april-16-2024)",
    "/our-work/fact-sheets/doe-managed-spent-nuclear-fuel-at-idaho-national-laboratory",
    "/our-work/fact-sheets/doe-managed-spent-nuclear-fuel-at-the-hanford-site",
    "/our-work/press-releases/daniel-ogg-named-executive-director-of-u.s.-nuclear-waste-technical-review-board",
    "/meetings/past-meetings/fall-2018-board-meeting---october-24-2018",
    "/meetings/past-meetings/fall-2020-board-virtual-meeting----december-2-3-2020",
    "/meetings/past-meetings/fall-2021-virtual-board-meeting---november-3-4-2021",
    "/our-work/reports/filling-the-gaps-the-critical-role-of-underground-research-laboratories-in-the-u.s.-department-of-energy-geologic-disposal-research-and-development-program-(january-2020)",
    "/our-work/press-releases/nwtrb-publishes-two-new-products-regarding-the-siting-of-radioactive-waste-facilities",
    "/meetings/past-meetings/4",
    "/our-work/press-releases/president-biden-appoints-six-new-members-and-designates-new-chair-to-the-u.s.-nuclear-waste-technical-review-board",
    "/our-work/press-releases/president-biden-appoints-six-new-members-to-u.s.-nuclear-waste-technical-review-board",
    "/our-work/press-releases/doe's-management-and-plans-for-disposal-of-doe-spent-nuclear-fuel-are-focus-of-u.s.-nwtrb-meeting-(july-22--2024)",
    "/our-work/press-releases/1",
    "/our-work/reports/1",
    "/meetings/past-meetings/summer-2014-board-meeting",
    "/meetings/past-meetings/summer-2021-virtual-board-meeting---august-24-2021",
    "/meetings/past-meetings/summer-2022-board-meeting---september-13-14-2022",
    "/our-work/press-releases/u.s.-nwtrb-august-public-meeting-to-focus-on-u.s.-doe-consent-based-siting-efforts-and-spent-nuclear-fuel-and-high-level-radioactive-waste-management-research-and-development",
    "/our-work/press-releases/u.s.-nwtrb-releases-report-summarizing-activities-from-january-1-2016-through-december-31-2018-(august-31-2021)",
    "/our-work/press-releases/u.s.-nwtrb-releases-report-summarizing-activities-from-january-1-2019-through-december-31-2021-(november-28-2022)",
    "/our-work/press-releases/u.s.-nwtrb-releases-report-on-canisters-containing-spent-nuclear-fuel-from-commercial-nuclear-reactors-nuclear-reactors-(february-29-2024)",
    "/our-work/press-releases/u.s.-nwtrb-releases-report-on-commercial-high-burnup-spent-nuclear-fuel-performance-during-extended-storage-and-transportation-(august-2-2021)",
    "/our-work/press-releases/u.s.-nwtrb-to-hold-public-meeting-on-u.s.-doe-r-d-activities-related-to-the-geologic-disposal-safety-assessment-framework",
    "/our-work/press-releases/u.s.-nwtrb-to-hold-public-meeting-on-u.s.-doe-spent-fuel-and-waste-disposition-r-d-activities-and-consent-based-siting-process",
    "/Sitefinity/Login?ReturnUrl=https%3a%2f%2fwww.nwtrb.gov%2fsitefinity%2ftemplate%2fbab59048-abad-6706-9638-ff00003d5b4b%2fpreview"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nwtrb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}