module.exports = {
  "site": "https://www.nwtrb.gov",
  "urls": [
    "/our-work/correspondence/board-letter-to-dr.-michael-goff-(may-22--2025)",
    "/our-work/correspondence/board-letter-to-u.s.-congress-and-secretary-to-energy---observations-on-deep-geological-repository-program---march-18--2025",
    "/our-work/correspondence/letter-from-dr.-michael-goff-to-the-board---september-9--2024",
    "/meetings/past-meetings/spring-2018-board-meeting---march-28-2018",
    "/meetings/past-meetings/spring-2024-board-meeting---may-2024",
    "/news/2025/03/18/board-letter-to-u.s.-congress-and-secretary-to-energy---observations-on-deep-geological-repository-program-(march-18--2025)",
    "/our-work/correspondence/board-letter-to-kathryn-huff---december-14-2022",
    "/our-work/correspondence/board-letter-to-dr.-kathryn-huff---june-7-2022",
    "/our-work/correspondence/board-letter-to-dr.-michael-goff-(may-28-2024)",
    "/our-work/correspondence/2",
    "/our-work/reports/preparing-for-nuclear-waste-transportation-(september-2019)",
    "/our-work/fact-sheets/radiation-source-term",
    "/meetings/past-meetings/summer-2023-board-meeting---august-30-2023",
    "/our-work/reports/survey-of-national-programs-for-managing-high-level-radioactive-waste-and-spent-nuclear-fuel-update-(2016)",
    "/our-work/correspondence/board-letter-to-dr.-kathryn-huff---april-24-2024",
    "/our-work/correspondence/board-letter-to-dr.-kathryn-huff---december-30-2021",
    "/our-work/correspondence/board-letter-to-dr.-kathryn-huff---july-6-2022",
    "/our-work/correspondence/board-letter-to-mr.-william-(ike)-white---october-14-2021",
    "/our-work/correspondence/4",
    "/our-work/fact-sheets/doe-managed-spent-nuclear-fuel-at-fort-st.-vrain",
    "/data",
    "/meetings/past-meetings/fall-board-meeting---november-8-9-2005",
    "/scope/international-experience",
    "/our-work/correspondence/letter-from-dr.-michael-goff-to-the-board---september-18--2024",
    "/meetings/past-meetings/2",
    "/personal-assistance-services-(pas)",
    "/our-work/reports/report-to-the-u.s.-congress-and-the-secretary-of-energy---board-activities-for-the-period-january-1-2016---december-31-2018-(august-2021)",
    "/our-work/reports/review-of-u.s.-department-of-energy-activities-to-preserve-records-created-by-the-yucca-mountain-repository-project-(2013)",
    "/meetings/past-meetings/summer-2017-board-meeting---june-21-2017",
    "/our-work/fact-sheets/vitrified-high-level-radioactive-waste",
    "/our-work/correspondence/board-letter-to-dr.-kathryn-huff---august-24-2023",
    "/our-work/correspondence/board-letter-to-dr.-kathryn-huff---january-7-2022",
    "/our-work/correspondence/5",
    "/our-work/reports/evaluation-of-technical-issues-associated-with-the-development-of-a-separate-repository-for-u.s.-department-of-energy-managed-high-level-radioactive-waste-and-spent-nuclear-fuel-(2015)",
    "/meetings/past-meetings/fall-2019-board-meeting---november-19-2019",
    "/our-work/correspondence/letter-from-dr.-kathrn-huff-to-the-board---september-28-2022",
    "/our-work/reports/management-and-disposal-of-u.s.-department-of-energy-spent-nuclear-fuel-(december-2017)",
    "/about-us/members/memb-speeches",
    "/our-work",
    "/our-work/reports/six-overarching-recommendations-for-how-to-move-the-nation-s-nuclear-waste-management-program-forward-(april-2020)",
    "/meetings/past-meetings/spring-2008-board-meeting---may-29-2008",
    "/meetings/past-meetings/winter-2022-board-meeting---march-28-2023",
    "/meetings/past-meetings/summer-2016-board-meeting---august-24-2016",
    "/meetings/past-meetings/summer-2020-board-meeting",
    "/our-work/reports/survey-of-national-programs-for-managing-high-level-radioactive-waste-and-spent-nuclear-fuel-2022-update",
    "/meetings/past-meetings/winter-2022-board-virtual-meeting---march-1-2-2022",
    "/our-work/fact-sheets/cesium-and-strontium-capsules",
    "/our-work/fact-sheets/doe-managed-spent-nuclear-fuel",
    "/our-work/fact-sheets/doe-managed-spent-nuclear-fuel-at-the-savannah-river-site",
    "/our-work/reports/geologic-repositories-performance-monitoring-and-retrievability-of-emplaced-high-level-radioactive-waste-and-spent-nuclear-fuel"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.nwtrb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}