module.exports = {
  "site": "https://www.opm.gov",
  "urls": [
    "/policy-data-oversight/pay-leave/salaries-wages/2025/general-schedule/",
    "/",
    "/policy-data-oversight/pay-leave/federal-holidays/",
    "/policy-data-oversight/pay-leave/salaries-wages/",
    "/search",
    "/retirement-center/",
    "/retirement-center/calculators/fegli-calculator/fegli-iframe/",
    "/policy-data-oversight/pay-leave/salaries-wages/2025/law-enforcement-officer/",
    "/chcoc/historical-memos/",
    "/healthcare-insurance/healthcare/plan-information/compare-plans/",
    "/healthcare-insurance/healthcare/plan-information/compare-plans/?zipcode=99999&rateCoverage=Self&validate=True",
    "/opm_maintenance.html",
    "/policy-data-oversight/pay-leave/pay-systems/general-schedule/",
    "/policy-data-oversight/data-analysis-documentation/personnel-documentation/",
    "/healthcare-insurance/",
    "/policy-data-oversight/classification-qualifications/general-schedule-qualification-standards/",
    "/chcoc/latest-memos/",
    "/retirement-center/fers-information/",
    "/healthcare-insurance/healthcare/",
    "/policy-data-oversight/pay-leave/salaries-wages/2024/general-schedule",
    "/healthcare-insurance/healthcare/plan-information/compare-plans/",
    "/opm_maintenance.html",
    "/retirement-center/fers-information/computation/",
    "/support/retirement/contact/",
    "/about-us/",
    "/policy-data-oversight/classification-qualifications/classifying-general-schedule-positions/",
    "/policy-data-oversight/pay-leave/",
    "/retirement-center/fers-information/types-of-retirement/",
    "/policy-data-oversight/",
    "/frequently-asked-questions/pay-and-leave-faq/pay-administration/what-are-federal-holidays/",
    "/retirement-center/my-annuity-and-benefits/",
    "/policy-data-oversight/pay-leave/pay-systems/federal-wage-system/",
    "/healthcare-insurance/guide-me/federal-employees/",
    "/retirement-center/calculators/fegli-calculator/",
    "/healthcare-insurance/life-insurance/",
    "/retirement-center/calculators/fegli-calculator/employee-summary/",
    "/policy-data-oversight/pay-leave/2026-special-rates-for-certain-law-enforcement-personnel/",
    "/healthcare-insurance/healthcare/plan-information/plans/",
    "/retirement-center/fers-information/eligibility/",
    "/retirement-center/csrs-information/planning-and-applying/",
    "/forms/standard-forms/",
    "/policy-data-oversight/pay-leave/leave-administration/",
    "/policy-data-oversight/snow-dismissal-procedures/current-status/",
    "/policy-data-oversight/pay-leave/leave-administration/fact-sheets/annual-leave/",
    "/policy-data-oversight/pay-leave/leave-administration/fact-sheets/family-and-medical-leave/",
    "/retirement-center/calculators/fegli-calculator/check-sheet/",
    "/policy-data-oversight/pay-leave/salaries-wages/salary-tables/25tables/html/dcb.aspx",
    "/retirement-center/quick-guide/",
    "/policy-data-oversight/pay-leave/salaries-wages/salary-tables/25tables/html/rus.aspx",
    "/fedshirevets/",
    "/retirement-center/my-annuity-and-benefits/annuity-payments/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.opm.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 102,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}