module.exports = {
  "site": "https://oge.gov",
  "urls": [
    "/web/oge.nsf/section_landing_publicresources",
    "/web/oge.nsf/resources/e.o.+12674:+principles+of+ethical+conduct+for+government+officers+and+employees",
    "/web/oge.nsf/publicresources_compliance",
    "/web/oge.nsf/publicresources_public-participation",
    "/web/oge.nsf/about_careers",
    "/web/oge.nsf/ethicsofficials_enforcement-resp",
    "/web/oge.nsf/ethicsofficials_oge-oversight",
    "/web/oge.nsf/about_anti-corruption",
    "/web/oge.nsf/ethicsofficials_records-management",
    "/web/oge.nsf/resources/confidential+financial+disclosure+guide+(2023)",
    "/web/oge.nsf/site-index",
    "/web/oge.nsf/freedom+of+information+act+(foia)+reports",
    "/web/oge.nsf/privacy",
    "/web/oge.nsf/oge%20news%20feed",
    "/web/oge.nsf/publicresources_disclosure-quickstart",
    "/web/oge.nsf/ethicsofficials_election-readiness",
    "/web/oge.nsf/ethicsofficials_legal-expense-funds",
    "/web/oge.nsf/news_press",
    "/web/oge.nsf/section_landing_ethics-docs",
    "/web/oge.nsf/freedom%20of%20information%20act%20(foia)%20reports",
    "/web/oge.nsf/resources_legal-expense-funds",
    "/web/oge.nsf/news+releases/afdb5c8d408af29885258cf2005f1d08",
    "/web/oge.nsf/0/fe125a54b5831bea852585b6005a2413/",
    "/web/oge.nsf/advisories-topics",
    "/web/oge.nsf/resources/18+u.s.c.+%C2%A7+205:+activities+of+officers+and+employees+in+claims+against+and+other+matters+affecting+the+government",
    "/web/oge.nsf/agency+ethics+pledge+waivers+(eo+13770)",
    "/web/oge.nsf/resources/18%20u.s.c.%20%C2%A7%20201:%20bribery%20of%20public%20officials%20and%20witnesses",
    "/web/oge.nsf/",
    "/web/oge.nsf/ethicsofficials_require-submission-oge",
    "/web/oge.nsf/resources/stop+trading+on+congressional+knowledge+act+of+2012+(stock+act)",
    "/web/oge.nsf/resources/government+ethics+and+accountability",
    "/web/oge.nsf/resources/la-15-03:+the+standards+of+conduct+as+applied+to+personal+social+media+use",
    "/web/oge.nsf/resources/qualified+trusts",
    "/web/oge.nsf/all%20docs%20by%20cat",
    "/web/oge.nsf/oge%20forms/35562b22edbd9ffc852585b6005a1351",
    "/web/oge.nsf/resources/privacy+impact+assessments",
    "/web/oge.nsf/resources/conflict+of+interest+prosecution+surveys+(by+year)",
    "/web/oge.nsf/resources/a+refresher+on+the+impartiality+rule",
    "/web/oge.nsf/all%20travel%20reports",
    "/web/oge.nsf/resources/oge+form+1353:+semiannual+report+of+payments+accepted+from+a+non-federal+source",
    "/web/oge.nsf/written_materials_for_ethics_education",
    "/web/oge.nsf/publicresources_disclosure-glossary",
    "/web/oge.nsf/resources/part+i:+assets+and+income",
    "/web/oge.nsf/resources/resources%20for%20nominees%20to%20senate-confirmed%20positions",
    "/web/oge.nsf/resources/excepted+investment+funds+(eifs)",
    "/web/oge.nsf/resources/la-16-08:+introduction+to+the+primary+post-government+employment+restrictions+applicable+to+former+executive+branch+employees",
    "/web/oge.nsf/agency+ethics+pledge+waivers+(eo+13989)",
    "/web/oge.nsf/resources/97x5:+restrictions+affecting+spouses+who+work+for+the+same+agency",
    "/web/oge.nsf/news%20releases/4402f9f1e4455c4985258cdf0062fab8",
    "/web/oge.nsf/publicresources_compliance_recommendations"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://oge.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}