module.exports = {
  "site": "https://oge.gov",
  "urls": [
    "/web/oge.nsf/officials%20individual%20disclosures%20search%20collection",
    "/",
    "/web/oge.nsf/a716ba6e5e826838852585ae005546c0/f029088beda3de04852585b6005a1e0e",
    "/web/oge.nsf/legal%20research%20search%20collection",
    "/web/oge.nsf/ethicsofficials_financial-disc",
    "/web/oge.nsf/about_ethics-contact-list",
    "/web/oge.nsf/resources_standards-of-conduct",
    "/web/oge.nsf/home",
    "/web/oge.nsf/resources_resources-fin-disc",
    "/web/oge.nsf/news+releases/4402f9f1e4455c4985258cdf0062fab8",
    "/web/oge.nsf/agency%20ethics%20documents%20search%20collection",
    "/web/oge.nsf/congressional%20correspondence",
    "/web/oge.nsf/about_leadership",
    "/web/oge.nsf/resources/analyzing+potential+conflicts+of+interest",
    "/web/oge.nsf/resources/public+financial+disclosure+guide",
    "/web/oge.nsf/about_what-we-do",
    "/web/oge.nsf/resources/standards+of+ethical+conduct+for+employees+of+the+executive+branch",
    "/web/oge.nsf/oge%20forms",
    "/web/oge.nsf/about_information-management",
    "/web/oge.nsf/about_reporting-misconduct",
    "/web/oge.nsf/publicresources_foia-landing",
    "/web/oge.nsf/about_organization",
    "/web/oge.nsf/about_internal-agency-policies",
    "/web/oge.nsf/ethicsofficials_education-through-training",
    "/web/oge.nsf/resources/compilation+of+federal+ethics+laws",
    "/web/oge.nsf/ethicsofficials_conflict-resolution",
    "/web/oge.nsf/about_reports-to-congress",
    "/web/oge.nsf/about_budget-performance",
    "/web/oge.nsf/about_contacts",
    "/web/oge.nsf/news%20releases",
    "/web/oge.nsf/about_appropriations",
    "/web/oge.nsf/about_ethics-legislation",
    "/web/oge.nsf/section_landing_resources",
    "/web/oge.nsf/resources/18+u.s.c.+%C2%A7+207:+restrictions+on+former+officers,+employees,+and+elected+officials+of+the+executive+and+legislative+branches",
    "/web/oge.nsf/leadership%20notes",
    "/web/oge.nsf/ethics_education_toolkits",
    "/web/oge.nsf/ethicsofficials_professional-development",
    "/web/oge.nsf/resources/oge+form+450+(august+2024+accessible+pdf+version)",
    "/web/oge.nsf/resources/18+u.s.c.+%C2%A7+208:+acts+affecting+a+personal+financial+interest",
    "/web/oge.nsf/about_our-history",
    "/web/oge.nsf/publicresources_summary-reports",
    "/web/oge.nsf/publicresources_disclosure-faq",
    "/web/oge.nsf/resources/oge+form+201:+request+an+individual%E2%80%99s+ethics+documents",
    "/web/oge.nsf/resources/oge+form+278+instructions",
    "/web/oge.nsf/oge+forms",
    "/web/oge.nsf/ethicsofficials_ethical-leadership",
    "/web/oge.nsf/ethicsofficials_mission",
    "/web/oge.nsf/ethicsofficials_oge-support",
    "/web/oge.nsf/about_engagement",
    "/web/oge.nsf/section_landing_about"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://oge.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}