module.exports = {
  "site": "https://www2.oge.gov",
  "urls": [
    "/",
    "/web/oge.nsf/about_information-management",
    "/web/oge.nsf/about_budget-performance",
    "/web/oge.nsf/about_internal-agency-policies",
    "/web/oge.nsf/about_reports-to-congress",
    "/web/oge.nsf/about_ethics-contact-list",
    "/web/oge.nsf/about_appropriations",
    "/web/oge.nsf/officials%20individual%20disclosures%20search%20collection",
    "/web/oge.nsf/about_organization",
    "/web/oge.nsf/home",
    "/web/oge.nsf/agency%20ethics%20documents%20search%20collection",
    "/web/oge.nsf/about_what-we-do",
    "/web/oge.nsf/about_our-history",
    "/web/oge.nsf/about_ethics-legislation",
    "/web/oge.nsf/about_leadership",
    "/web/oge.nsf/about_engagement",
    "/web/oge.nsf/publicresources_foia-landing",
    "/web/oge.nsf/oge%20forms",
    "/web/oge.nsf/resources/5+c.f.r.+part+2635:+standards+of+ethical+conduct+for+employees+of+the+executive+branch",
    "/web/oge.nsf/legal%20research%20search%20collection",
    "/web/oge.nsf/section_landing_about",
    "/web/oge.nsf/about_contacts",
    "/web/oge.nsf/resources/oge+form+450",
    "/web/oge.nsf/ethicsofficials_financial-disc",
    "/web/oge.nsf/about_anti-corruption",
    "/web/oge.nsf/about_reporting-misconduct",
    "/web/oge.nsf/publicresources_summary-reports",
    "/web/oge.nsf/about_careers",
    "/web/oge.nsf/congressional%20correspondence",
    "/web/oge.nsf/site-index",
    "/web/oge.nsf/resources/oge+form+202:+notice+of+conflict+of+interest+referral",
    "/web/oge.nsf/ethicsofficials_records-management",
    "/web/oge.nsf/resources_resources-fin-disc",
    "/web/oge.nsf/ethicsofficials_conflict-resolution",
    "/web/oge.nsf/ethicsofficials_education-through-training",
    "/web/oge.nsf/section_landing_publicresources",
    "/web/oge.nsf/section_landing_resources",
    "/web/oge.nsf/resources_standards-of-conduct",
    "/web/oge.nsf/ethicsofficials_legal-expense-funds",
    "/web/oge.nsf/ethicsofficials_oge-support",
    "/web/oge.nsf/ethicsofficials_mission",
    "/web/oge.nsf/ethicsofficials_enforcement-resp",
    "/web/oge.nsf/ethicsofficials_oge-oversight",
    "/web/oge.nsf/privacy",
    "/web/oge.nsf/news_press",
    "/web/oge.nsf/ethicsofficials_ethical-leadership",
    "/web/oge.nsf/ethicsofficials_election-readiness",
    "/web/oge.nsf/ethicsofficials_professional-development",
    "/web/oge.nsf/publicresources_public-participation",
    "/web/oge.nsf/oge+forms",
    "/web/oge.nsf/resources_legal-expense-funds",
    "/web/oge.nsf/accessdocs_foia-landing"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www2.oge.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 104,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}