module.exports = {
  "site": "https://www.pbgc.gov",
  "urls": [
    "/workers-retirees/manage/survivor-benefits-information",
    "/workers-retirees/manage/qualified-domestic-relations-orders",
    "/workers-retirees/manage/when-pension-plans-ends",
    "/about/faq",
    "/about/reports/performance-measures/customer-satisfaction",
    "/about/who-we-are/director",
    "/glossary",
    "/about/reports/pension-insurance-data",
    "/arp-sfa/faqs",
    "/es",
    "/about/reports",
    "/employers-practitioners/plan-terminations/standard/faq",
    "/about/careers",
    "/workers-retirees/learn/guaranteed-benefits/multiemployer-plans-facts",
    "/employers-practitioners/multiemployer/withdrawal-liability",
    "/about/who-we-are/departments",
    "/workers-retirees/learn/understanding-your-pension-pbgc-coverage",
    "/about/advocate",
    "/about/contact/employers-practitioners",
    "/about/faq/pg/executor-fact-sheet",
    "/es/mypba",
    "/yellow-qa",
    "/employers-practitioners/multiemployer/introduction",
    "/es/search-trusteed-plans",
    "/workers-retirees/faqs",
    "/about/pg/footer/foia",
    "/arp-sfa/sfa-applications/681584",
    "/about/reports/projections",
    "/about/who-we-are/history",
    "/news/press",
    "/workers-retirees/update",
    "/search/help",
    "/about/reports/annual/pbgc-annual-performance-financial-report-2024",
    "/workers-retirees/learn/guaranteed-benefits/single-employer-plans",
    "/employers-practitioners/legal-resources/guidance",
    "/about/reports/budget-performance-planning",
    "/employers-practitioners/reporting-disclosure/erisa-4010",
    "/workers-retirees/transactions/designate-power-attorney",
    "/rite-aid-qa",
    "/arp-sfa/sfa-applications/152081",
    "/workers-retirees/learn/receiving-pension-benefits",
    "/employers-practitioners/federal-register/final-rules",
    "/employers-practitioners/missing-participants-program/payment-instructions",
    "/employers-practitioners/reporting-disclosure",
    "/news/press/pr24-015",
    "/open/index",
    "/workers-retirees/trusteed-plans/plan-21391900",
    "/news/press/pr25-003",
    "/workers-retirees/learn/guaranteed-benefits",
    "/workers-retirees/manage/appeal-benefit-determination"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.pbgc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}