module.exports = {
  "site": "https://www.pbgc.gov",
  "urls": [
    "/workers-retirees/find-unclaimed-retirement-benefits/search-unclaimed",
    "/",
    "/workers-retirees/mypba",
    "/search-plan",
    "/search-all",
    "/workers-retirees/find-unclaimed-retirement-benefits/tips",
    "/news/statements",
    "/about/contact",
    "/employers-practitioners/my-paa",
    "/workers-retirees",
    "/employers-practitioners/premium-filings/payment-instructions",
    "/workers-retirees/transactions/apply",
    "/news/press",
    "/employers-practitioners/interest-rates/variable",
    "/workers-retirees/find-unclaimed-retirement-benefits/other-resources",
    "/workers-retirees/manage",
    "/workers-retirees/learn/payments/payment-dates",
    "/workers-retirees/learn/guaranteed-benefits/monthly-maximum",
    "/workers-retirees/trusteed-plans",
    "/employers-practitioners/premium-filings/rates",
    "/workers-retirees/transactions/direct-deposit",
    "/employers-practitioners/interest-rates/historical-applicable-mid-term",
    "/workers-retirees/learn/pension-benefits-overview",
    "/workers-retirees/transactions/update-address",
    "/workers-retirees/transactions/request-pension-benefit-estimate",
    "/arp-sfa",
    "/workers-retirees/forms",
    "/arp-sfa/applications",
    "/workers-retirees/find-unclaimed-retirement-benefits/documents-to-claim-retirement-benefit",
    "/workers-retirees/learn/understanding-your-pension-pbgc-coverage",
    "/arp-sfa/applications",
    "/workers-retirees/manage/report-death",
    "/employers-practitioners/interest-rates",
    "/workers-retirees/mypba/help",
    "/workers-retirees/learn/annuity-lump-sum",
    "/workers-retirees/learn/find-your-retirement-benefits",
    "/employers-practitioners/premium-filings",
    "/workers-retirees/find-unclaimed-retirement-benefits/eligibility",
    "/workers-retirees/learn/payments",
    "/workers-retirees/learn/guaranteed-benefits",
    "/about/who-we-are",
    "/workers-retirees/transactions/request-1099-r",
    "/employers-practitioners/whats-new",
    "/prac/other-guidance/tu/premium-filing-due-date-change-2025-plan-years",
    "/workers-retirees/learn/how-pension-plans-end",
    "/employers-practitioners/multiemployer",
    "/employers-practitioners/my-paa/demonstrations",
    "/workers-retirees/learn",
    "/employers-practitioners/plan-terminations/standard",
    "/workers-retirees/find-unclaimed-retirement-benefits/search-unclaimed"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.pbgc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}