module.exports = {
  "site": "https://www.pbgc.gov",
  "urls": [
    "/news/press/pr25-005",
    "/news/press/pr25-006",
    "/workers-retirees/find-unclaimed-retirement-benefits/before-contacting",
    "/news/press/pr25-004",
    "/workers-retirees/transactions/income-verification-request",
    "/news/statements/st12",
    "/about",
    "/news/statements/st11",
    "/news/statements/st10",
    "/prac/prem/upcoming-login-changes-my-paa",
    "/wr/sears-holdings-pension-plans",
    "/news/statements/st08",
    "/news/statements/st09",
    "/workers-retirees/learn/not-receiving-pension-benefits",
    "/news/statements/st03",
    "/news/statements/st02",
    "/news/statements/st07",
    "/news/statements/st05",
    "/news/statements/st04",
    "/news/statements/st06",
    "/employers-practitioners/plan-terminations",
    "/about/welcome-to-pbgc",
    "/workers-retirees/transactions",
    "/employers-practitioners/legal-resources/insurance-coverage",
    "/employers-practitioners/missing-participants-program/single-employer",
    "/workers-retirees/new",
    "/workers-retirees/transactions/change-federal-tax-withholding",
    "/employers-practitioners",
    "/a-zindex",
    "/Questions-and-Answers-for-Sears-Participants",
    "/workers-retirees/learn/pension-benefits-overview",
    "/workers-retirees/learn/required-beginning-date",
    "/employers-practitioners/interest-rates/erisa-4022-historical-lump-sum",
    "/about/who-we-are/executive-leadership",
    "/about/who-we-are/pg/board-of-directors-meeting-minutes/bod-meeting-minutes-12102015",
    "/es/encuentre-beneficios-de-jubilacion-no-reclamados",
    "/about/contact/email",
    "/workers-retirees/learn/pension-insurance-coverage",
    "/employers-practitioners/help-finding-missing-participants",
    "/workers-retirees/learn/guaranteed-benefits/single-employer-plans/faqs",
    "/about/faq/pg/Social-Security-Administration-Potential-Private-Pension-Benefit-Information-Notice-FAQs",
    "/workers-retirees/find-unclaimed-retirement-benefits/search-unclaimed",
    "/about/operate",
    "/employers-practitioners/reporting-disclosure/reportable-events",
    "/about/reports/annual",
    "/workers-retirees/transactions/name-your-beneficiary",
    "/prac/prem/outage/my-paa-is-unavailable",
    "/",
    "/employers-practitioners/forms",
    "/workers-retirees/new/understanding-pensions"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.pbgc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}