module.exports = {
  "site": "https://prc.gov",
  "urls": [
    "/commissioner/ashley-poling",
    "/job-openings/financial-data-analyst-0",
    "/node/4566",
    "/faqs/who-can-participate-prc-proceeding-docket-how",
    "/commissioner/ann-fisher",
    "/testimonies/",
    "/offices/pagr",
    "/foia/annual-reports",
    "/press-releases/prc-concludes-rate-system-has-not-achieved-necessary-objectives-and-issues-proposed",
    "/fy-2024-acd-highlights",
    "/press-releases/prc-adopts-final-rules-modify-rate-system-classes-market-dominant-products/5013",
    "/privacy",
    "/job-openings/financial-specialist-1",
    "/offices/ogc",
    "/eeo-contacts",
    "/public-representatives",
    "/offices/obf",
    "/rule-summary-page",
    "/acd-highlights",
    "/press-releases/prc-fiscal-year-2024-budget-justification/5371",
    "/press-releases/postal-regulatory-commission-statement/5451",
    "/press-releases/commission-releases-report-analyzing-postal-service%E2%80%99s-fy-2024-finances/5464",
    "/paper-authors/prc-staff",
    "/post-office-suspensions-dashboard-feedback",
    "/faqs/what-docket",
    "/content/october-14th-hearing-c2009-1",
    "/who-sets-postal-rates",
    "/problems-issues-complaints",
    "/calendar/",
    "/node/182",
    "/prc-ai-catalog",
    "/calendar",
    "/press-releases/commission-issues-determination-required-law-provide-transparency-and-accountability",
    "/filingonline/userguide",
    "/press-releases/prc-adopts-final-rules-minimum-contribution-competitive-products-institutional-cost",
    "/papers/prc-staff/33fc44d10a66607b2820c209b3af275152f3a2ad",
    "/node/5416",
    "/node/1620",
    "/user/password",
    "/node/5360",
    "/about/former-commissioners",
    "/vulnerability-disclosure-policy",
    "/node/2999",
    "/node/4193",
    "/press-releases/postal-regulatory-commission-releases-fiscal-year-2025-budget-justification/5408",
    "/accessibility",
    "/press-releases/prc-releases-report-postal-service-financial-condition-losses-operations-continue",
    "/pagr-consumer-info",
    "/press-releases/prc-assess-usps-pricing-and-service-2018-annual-compliance-determination-directs",
    "/node/4344"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://prc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}