module.exports = {
  "site": "https://prc.gov",
  "urls": [
    "/press-releases/prc-invites-stakeholder-consultation-regarding-study-first-class-service-standards",
    "/press-releases/prc-questions-reliability-usps-service-performance-measurement-system/5402",
    "/press-releases/postal-regulatory-commission-unveils-new-5-year-strategic-plan/5296",
    "/papers/edward-s-pearsall/1ea585c9c48ee16cf5ebbe29579fbff9933e28dc",
    "/papers/tony-hammond/0b7d773df3b3043645f63b651438ef5a4c8d6345",
    "/content/october-2010-monthly-commission-public-meeting",
    "/press-releases/prc-releases-report-and-dashboard-analyzing-postal-service%E2%80%99s-fy-2022-finances/5322",
    "/prc-ipv6-policy",
    "/press-releases/robert-g-taub-elected-vice-chairman-postal-regulatory-commission/5439",
    "/paper-authors/tony-hammond",
    "/usps-reports",
    "/faqs/what-authority-does-new-prc-have",
    "/papers/prc-staff/e36394fe2a18b8761e7019aadcb75ff9908877d3",
    "/press-releases/prc-host-record-technical-conference-stakeholder-participation-rate-design",
    "/node/140",
    "/node/1608",
    "/papers/prc-staff/f401ea6e8f3cdb10ccb8200a7814316031d17046",
    "/content/foia-annual-reports-8",
    "/foia/foia-quarterly-reports",
    "/node/3170",
    "/node/5013",
    "/node/4071",
    "/press-releases/prc-annual-compliance-determination-reveals-progress-and-problems-rate-and-fee",
    "/node/4206",
    "/press-releases/prc-issues-advisory-opinion-postal-service-plan-implement-service-standards-changes",
    "/press-releases/prc-selects-erica-barker-lead-its-office-secretary-and-administration/4793",
    "/node/5117",
    "/fy-2023-acd-highlights",
    "/paper-authors/frank-wolak",
    "/papers/prc-staff/d1996a2a9111c2a9171ec9962181fcc3a0e9d79f",
    "/node/72",
    "/paper-authors/edward-s-pearsall",
    "/node/3180",
    "/fy20-acd-highlights-8-charts",
    "/fy21-acd-highlights-10-charts",
    "/fy22-acd-highlights-10-charts",
    "/node/4234",
    "/node/3021",
    "/press-releases/prc-commissioners-appointed-second-term/5417",
    "/press-releases/postal-regulatory-commission-affirms-its-commitment-timely-review-nsas-and",
    "/foia/privacyactfaqs",
    "/press-releases/commissioner-michael-m-kubayanda-named-prc-vice-chairman/4692",
    "/press-releases/prc-evaluates-postal-service-compliance-pricing-and-service-fy-2020-annual-compliance",
    "/press-releases/prc-host-technical-conference-review-usps-audit-plan/4206",
    "/content/september-16th-hearing-n2010-1",
    "/privacy/sorns",
    "/faqs/what-role-can-public-play-when-postal-service-wants-raise-postage-prices",
    "/search/node/help",
    "/press-releases/chairman-kubayanda-statement-prc-budget/5372",
    "/content/chief-foia-officer-report"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://prc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}