module.exports = {
  "site": "https://prc.gov",
  "urls": [
    "/",
    "/postal-service-information-and-contacts",
    "/consumer-assistance",
    "/contact",
    "/user/login",
    "/prc-reports",
    "/press-releases",
    "/papers",
    "/search/node",
    "/speeches",
    "/speeches/",
    "/foia/onlinerequest",
    "/about",
    "/node/187/webform/confirmation",
    "/post-office-suspensions-dashboard",
    "/state-of-the-postal-service",
    "/user/login/",
    "/oig",
    "/user/password/",
    "/careers",
    "/mail-classification-schedule",
    "/leadership",
    "/foia",
    "/webcasts",
    "/press-releases/",
    "/how-to-file-complaint",
    "/contact/",
    "/job-openings/senior-data-engineer",
    "/faqs/what-do-docket-letters-and-numbers-mean",
    "/testimonies",
    "/postal-service-implements-nationwide-changes-mail-service",
    "/the-offices",
    "/faqs",
    "/commissioner/michael-kubayanda",
    "/mission",
    "/how-to-participate",
    "/references",
    "/prcgov-sitemap",
    "/press-releases/postal-regulatory-commission-issues-advisory-opinion-usps-delivering-america-prc",
    "/offices/oac",
    "/content/technical-conference-review-usps-audit-plan-docket-no-pi2015-1",
    "/papers/prc-staff/32f8a5a6f95a58499e279d5674787d9bd67b7541",
    "/foia/requests",
    "/commissioner/robert-taub",
    "/no-fear-act-data",
    "/offices/osa",
    "/papers/",
    "/offices/oig",
    "/content/may-2017-commission-public-meeting",
    "/commissioner/thomas-day"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://prc.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}