module.exports = {
  "site": "https://rrb.gov",
  "urls": [
    "/Benefits/myRRB",
    "/",
    "/Resources/Jobs",
    "/Benefits/Retirement",
    "/ContactUs",
    "/faq",
    "/Benefits/Sickness",
    "/Benefits",
    "/Field-Office-Locator",
    "/SSFActFAQ",
    "/Benefits/Unemployment",
    "/Benefits/Retirement/GeneralInfoRetirement",
    "/Newsroom/NewsReleases/MedicarePartBPremium",
    "/Newsroom/NewsReleases/RailroadRetirementSpouseBenefits",
    "/Benefits/Disability",
    "/Benefits/Medicare/GeneralInfoMedicare/RB20",
    "/Newsroom/NewsReleases/QA-SSFA",
    "/Newsroom/NewsReleases/UnemploymentandSicknessBenefits",
    "/Benefits/Survivor",
    "/Benefits/myRRB/GetRetirementBenefitsEstimate",
    "/Benefits/Sickness/downloadableforms",
    "/Benefits/Unemployment/GeneralInfoUnemployment/UB9",
    "/Benefits/Forms/G-34",
    "/Benefits/Retirement/downloadableforms",
    "/Newsroom/NewsReleases",
    "/Newsroom/NewsReleases/QA-RetirementSurvivorBenefits",
    "/payschedule",
    "/Benefits/myRRB/SIBenefitsClaims",
    "/Benefits/myRRB/PayUnemploymentOrSicknessBill",
    "/Benefits/myRRB/PayRetirementOrSurvivorBill",
    "/Benefits/RB-1",
    "/Newsroom/NewsReleases/DisabilityAnnuitiesforRailroadEmployees",
    "/Benefits/Survivor/GeneralInfoSurvivor",
    "/Benefits/Disability/GeneralInfoDisability",
    "/RB30/Overview",
    "/REEFActFAQ",
    "/cal_rr_ann",
    "/Newsroom/NewsReleases/ComparisonOfBenefits",
    "/Newsroom/NewsReleases/SSFA",
    "/OurAgency",
    "/Benefits/Sickness/GeneralInfoSickness",
    "/Newsroom/NewsReleases/RetirementUnemploymentInsuranceTaxes",
    "/OurAgency/InspectorGeneral/Library",
    "/Benefits/Unemployment/downloadableforms",
    "/Benefits/Unemployment/GeneralInfoUnemployment",
    "/Benefits/myRRB/RateVerLetter",
    "/Benefits/Medicare",
    "/Benefits/myRRB/ServiceCompHistory",
    "/Benefits/Disability/downloadableforms",
    "/Benefits/Survivor/Articles/GeneralInformationAboutSurvivorBenefits"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://rrb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}