module.exports = {
  "site": "https://rrb.gov",
  "urls": [
    "/Benefits/Disability/GeneralInfoDisability/ProcessingTime",
    "/Benefits/G-177A",
    "/Benefits/IncomeTax",
    "/UB-11/Sick_Pay_and_Supplemental_Sickness_Benefits",
    "/RB-1/Age_Reductions_For_Employees_Who_Have_Less_Than_360_Months_Service",
    "/Employers/Forms",
    "/Resources/LegalInformation/PartitionofRRA/AttorneysGuide",
    "/Newsroom/NewsReleases/CreditableMilitaryService",
    "/Policy",
    "/Field-Office-Locator/Chicago",
    "/OurAgency/InspectorGeneral",
    "/Newsroom/NewsReleases/CurrentConnection",
    "/UB-10/Checking_Your_Benefits_by_Telephone_or_Online",
    "/RB-1D",
    "/Newsroom/NewsReleases/RRBFinancialReports",
    "/Field-Office-Locator/Kansas%20City",
    "/RB-1D/Employee_Disability_Benefits/Application_Forms",
    "/node",
    "/RB17/For_use_with_survivor_annuity_applications/PartIX/CitizenandResidentTaxWithholding",
    "/Benefits/IncomeTax/GeneralInfoIncomeTax",
    "/RB-1/Basic_Formula",
    "/FinancialReporting/FinancialActuarialStatistical/EarningLimits/COLAs",
    "/Field-Office-Locator/Fort%20Worth",
    "/RB17/For_use_with_survivor_annuity_applications/PartIX/TierIAndTierII",
    "/Field-Office-Locator/Jacksonville",
    "/Retirement_and_Survivor_Information",
    "/RecentUpdates",
    "/contact/rrb_website_feedback",
    "/cal_rr_ann/Appendix",
    "/UB-11/Application_for_Sickness_Benefits_%28Form_SI-1a%29",
    "/Field-Office-Locator/Covina",
    "/Employers/EmployerOnlineServices",
    "/Field-Office-Locator/Houston",
    "/Field-Office-Locator/Denver",
    "/Benefits/AB-31",
    "/RB-1D/Employe_Disability_Benefits/Occupational_Disability_Annuity",
    "/RB-1/Applying_for_Annuity",
    "/FinancialReporting/FinancialActuarialStatistical",
    "/UB-11/Waiting_Period",
    "/Benefits/IncomeTax/downloadableforms",
    "/OurAgency/InspectorGeneral/Hotline",
    "/RB30/ApplyingForYourAnnuity",
    "/RB-9/Spouse_or_Employee_Death",
    "/OurAgency/LaborMember/Pre-RetirementSeminars/Videos",
    "/RB30/WhenYourAnnuityCanBegin",
    "/Newsroom/NewsReleases/LegalPartition",
    "/node/6384",
    "/Benefits/Survivor/GeneralInfoSurvivor/Articles/TypesofSurvivorBenefits",
    "/Field-Office-Locator/Central%20Islip"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://rrb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}