module.exports = {
  "site": "https://rrb.gov",
  "urls": [
    "/OurAgency/AgencyOverview",
    "/Newsroom/NewsReleases/RailroadRetirementAgeReductions",
    "/UB-11/Sickness_Benefits_for_Railroad_Employees",
    "/benefits/myRRB/AccountSupport",
    "/search/node",
    "/Benefits/myRRB/PayMedicareBill",
    "/Benefits/Medicare/GeneralInfoMedicare",
    "/cal_rr_ann/BenefitInfo/Determining_the_TierI_amount",
    "/Benefits/myRRB/RUIAAccount",
    "/Benefits/G-177",
    "/Newsroom/NewsReleases/DualBenefitPayments",
    "/Benefits/Survivor/downloadableforms",
    "/Resources",
    "/Benefits/myRRB/ReplacementMedCard",
    "/Benefits/G-77A",
    "/cal_rr_ann/tables",
    "/cal_rr_ann/BenefitInfo/TierII_amount",
    "/OurAgency/OfficeofAdministration/BureauofHumanResources/careers",
    "/Benefits/myRRB/UIBenefitsClaims",
    "/RB-9/Social_Security_Benefits",
    "/Newsroom/NewsReleases/RetirementBenefitsIncrease2025",
    "/UB-10/Unemployment_Benefits_for_Railroad_Employees",
    "/Employers",
    "/Resources/RailroadRetirementHandbook",
    "/sitemap",
    "/FinancialReporting/FinancialActuarialStatistical/EarningLimits",
    "/Benefits/myRRB/UIApp",
    "/Benefits/IncomeTax/TXL1099R",
    "/Benefits/myRRB/AboutRUIATaxDocuments",
    "/cal_rr_ann/Benefit_Information",
    "/Benefits/Articles/DirectDeposit",
    "/FinancialReporting/NRRIT",
    "/Employers/Forms/EmployerReportingForms",
    "/Benefits/RB-40",
    "/Newsroom/NewsReleases/StatementsofService",
    "/Benefits/IncomeTax/TXL-1099",
    "/FinancialReporting",
    "/Newsroom/NewsReleases/Medicare",
    "/Benefits/G-177/Age_Requirement",
    "/Benefits/TXB-85/SectionF",
    "/Benefits/G-177/FRA",
    "/OurAgency/OrganizationChart",
    "/Newsroom",
    "/Benefits/RB-3",
    "/Newsroom/NewsReleases/EarningsLimits",
    "/Benefits/G-177S",
    "/OurAgency/LaborMember/Pre-RetirementSeminars",
    "/Newsroom/NewsReleases/NoncoveredServicePensions",
    "/RB-1/When_Your_Annuity_can_Begin",
    "/RERI_Chapter_5_Form_W-2_Wage_and_Tax_Statement_and_Form_W-3_Transmittal_of_Wage_and_Tax_Statements"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://rrb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}