module.exports = {
  "site": "https://www.sba.gov",
  "urls": [
    "/funding-programs/loans/covid-19-relief-options",
    "/funding-programs/loans/504-loans/list-certified-development-companies",
    "/funding-programs/loans/covid-19-relief-options/eidl",
    "/business-guide/plan-your-business/calculate-your-startup-costs",
    "/funding-programs/disaster-assistance/economic-injury-disaster-loans",
    "/about-sba/sba-locations/sba-district-offices",
    "/sba-learning-platform/boots-business",
    "/business-guide",
    "/document/support-andrews-business-plan-template-traditional",
    "/business-guide/grow-your-business/minority-owned-businesses",
    "/funding-programs/loans/covid-19-relief-options/paycheck-protection-program/ppp-data",
    "/document/support-andrews-business-plan-template-lean",
    "/business-guide/plan-your-business",
    "/document/sop-50-10-lender-development-company-loan-programs",
    "/document/sba-form-413-personal-financial-statement",
    "/federal-contracting/contracting-guide/basic-requirements",
    "/document/sba-form-3508-ppp-loan-forgiveness-application-instructions",
    "/business-guide/plan-your-business/buy-existing-business-or-franchise",
    "/business-guide/launch-your-business/open-business-bank-account",
    "/sba-learning-platform",
    "/local-assistance/resource-partners/womens-business-centers",
    "/business-guide/plan-your-business/establish-business-credit",
    "/funding-programs/disaster-assistance/physical-damage-loans",
    "/local-assistance/resource-partners/veterans-business-outreach-centers-vboc",
    "/es",
    "/contact/contact_your_district_office",
    "/about-sba/sba-newsroom",
    "/federal-contracting",
    "/business-guide/launch-your-business",
    "/business-guide/launch-your-business/pick-your-business-location",
    "/funding-programs/investment-capital",
    "/about-sba/sba-locations",
    "/local-assistance/resource-partners/score-business-mentoring",
    "/federal-contracting/contracting-guide/how-win-contracts",
    "/funding-programs/grants/manufacturing-grants",
    "/national-small-business-week/awards",
    "/federal-contracting/contracting-assistance-programs/small-disadvantaged-business",
    "/business-guide/grow-your-business/get-more-funding",
    "/funding-programs/grants/state-trade-expansion-program-step",
    "/partners",
    "/articles",
    "/federal-contracting/contracting-guide/types-contracts",
    "/funding-programs/surety-bonds/surety-bond-agency-directory",
    "/federal-contracting/contracting-assistance-programs/sba-mentor-protege-program",
    "/es/guia-de-negocios/10-pasos-para-iniciar-su-empresa",
    "/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point",
    "/priorities/american-manufacturers/make-onshoring-great-again-portal",
    "/funding-programs/loans/covid-19-relief-options/sba-debt-relief",
    "/about-sba/organization/sba-leadership",
    "/document/sba-form-borrowers-consent-verify-information-third-party-authorization"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.sba.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}