module.exports = {
  "site": "https://www.sba.gov",
  "urls": [
    "/business-guide/manage-your-business/ai-small-business",
    "/es/programas-de-financiamiento/prestamos",
    "/federal-contracting/contracting-guide/prime-subcontracting",
    "/funding-programs/surety-bonds",
    "/article/2025/09/03/sba-launches-first-ever-loan-program-dedicated-american-manufacturers",
    "/document/support-eligible-naics-women-owned-small-business-federal-contracting-program",
    "/partners/lenders/7a-loan-program",
    "/federal-contracting/contracting-assistance-programs",
    "/partners/lenders/lender-reports",
    "/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point/calculate",
    "/es/programas-de-financiamiento/prestamos/efectuar-un-pago-la-sba",
    "/business-guide/plan-your-business/buy-existing-business-or-franchise/sba-franchise-directory",
    "/partners/sbics",
    "/priorities/american-manufacturers",
    "/about-sba/sba-locations/loan-guaranty-centers/commercial-loan-service-centers",
    "/es/programas-de-financiamiento/prestamos/opciones-de-asistencia-por-covid-19/programa-de-proteccion-de-pago",
    "/about-sba/sba-locations/headquarters-offices/office-veterans-business-development",
    "/business-guide/grow-your-business/rural-businesses",
    "/document/support-calculate-startup-costs",
    "/business-guide/manage-your-business",
    "/document/sba-form-1919-borrower-information-form",
    "/about-sba/work-sba/jobs-sba",
    "/funding-programs/loans/covid-19-relief-options/paycheck-protection-program/first-draw-ppp-loan",
    "/blog/basic-information-about-operating-agreements",
    "/document/support-general-assistance-requirement-letter",
    "/partners/lenders",
    "/blog",
    "/funding-programs/loans/covid-19-relief-options/reporting-identity-theft",
    "/business-guide/manage-your-business/close-or-sell-your-business",
    "/federal-contracting/contracting-guide",
    "/funding-programs/loans/covid-19-relief-options/covid-19-economic-injury-disaster-loan/about-targeted-eidl-advance-supplemental-targeted-advance",
    "/funding-programs/loans/covid-19-relief-options/covid-19-economic-injury-disaster-loan/about-covid-19-eidl",
    "/document/support-cesc-subordination-requirement-letter",
    "/federal-contracting/contracting-guide/assess-your-business",
    "/es/guia-de-negocios/planifique-su-empresa/redacte-su-plan-de-negocios",
    "/district/south-florida",
    "/partners/lenders/7a-loan-program/7a-working-capital-pilot-program",
    "/business-guide/manage-your-business/hire-manage-employees",
    "/business-guide/grow-your-business/become-federal-contractor",
    "/business-guide/manage-your-business/manage-your-finances",
    "/district/dallas-fort-worth",
    "/about-sba/oversight-advocacy/office-inspector-general/office-inspector-general-hotline",
    "/local-assistance/federal-contracting-assistance",
    "/document/report-25-23-sbas-collection-efforts-delinquent-covid-19-eidls",
    "/about-sba",
    "/document/support-change-ownership-requirement-letter",
    "/federal-contracting/contracting-assistance-programs/joint-ventures",
    "/district/georgia",
    "/business-guide/manage-your-business/marketing-sales",
    "/document/sop-50-57-7a-loan-servicing-liquidation"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.sba.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}