module.exports = {
  "site": "https://www.sba.gov",
  "urls": [
    "/",
    "/funding-programs/loans",
    "/about-sba/open-government/about-sbagov-website/sba-account-login-registration-portals",
    "/funding-programs/loans/make-payment-sba",
    "/funding-programs/loans/covid-19-relief-options/paycheck-protection-program",
    "/funding-programs/loans/lender-match-connects-you-lenders",
    "/funding-programs/loans/covid-19-relief-options/paycheck-protection-program/ppp-loan-forgiveness",
    "/business-guide/plan-your-business/write-your-business-plan",
    "/funding-programs/loans/7a-loans",
    "/funding-programs/loans/covid-19-relief-options/covid-19-economic-injury-disaster-loan/manage-your-eidl",
    "/search",
    "/business-guide/10-steps-start-your-business",
    "/funding-programs/grants",
    "/local-assistance/find",
    "/funding-programs/loans/microloans/list-microlenders",
    "/about-sba/organization/contact-sba",
    "/funding-programs/loans/microloans",
    "/events",
    "/business-guide/launch-your-business/choose-business-structure",
    "/funding-programs/disaster-assistance",
    "/documents",
    "/document/support-table-size-standards",
    "/business-guide/launch-your-business/register-your-business",
    "/funding-programs/loans/504-loans",
    "/funding-programs",
    "/business-guide/launch-your-business/choose-your-business-name",
    "/business-guide/plan-your-business/market-research-competitive-analysis",
    "/federal-contracting/contracting-assistance-programs/women-owned-small-business-federal-contract-program",
    "/business-guide/grow-your-business/women-owned-businesses",
    "/business-guide/plan-your-business/fund-your-business",
    "/funding-programs/disaster-assistance/texas-floods",
    "/national-small-business-week",
    "/federal-contracting/contracting-assistance-programs/8a-business-development-program",
    "/business-guide/launch-your-business/get-federal-state-tax-id-numbers",
    "/local-assistance",
    "/document/support-rebeccas-business-plan-template-traditional",
    "/business-guide/grow-your-business/veteran-owned-businesses",
    "/federal-contracting/contracting-assistance-programs/veteran-contracting-assistance-programs",
    "/federal-contracting/contracting-guide/size-standards",
    "/federal-contracting/contracting-assistance-programs/hubzone-program",
    "/funding-programs/investment-capital/sbic-directory",
    "/local-assistance/resource-partners/small-business-development-centers-sbdc",
    "/business-guide/launch-your-business/get-business-insurance",
    "/business-guide/launch-your-business/apply-licenses-permits",
    "/federal-contracting/contracting-guide/size-standards/size-standards-tool",
    "/partners/lenders/7a-loan-program/types-7a-loans",
    "/partners/lenders/7a-loan-program/terms-conditions-eligibility",
    "/document/support-sba-franchise-directory",
    "/article/2025/08/26/sba-orders-lenders-end-practice-debanking",
    "/funding-programs/grants/grants-community-organizations"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.sba.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}