module.exports = {
  "site": "https://travel.state.gov",
  "urls": [
    "/content/travel/en/passports/have-passport/renew-online.html",
    "/content/travel/en/passports.html",
    "/content/travel/en/passports/need-passport/apply-in-person.html",
    "/content/travel/en/legal/visa-law0/visa-bulletin.html",
    "/content/travel/en/passports/have-passport/renew.html",
    "/content/travel/en/passports/how-apply/forms.html",
    "/content/travel.html",
    "/content/travel/en/passports/have-passport.html",
    "/content/travel/en/search.html",
    "/content/travel/en/legal/visa-law0/visa-bulletin/2025/visa-bulletin-for-september-2025.html",
    "/content/travel/en/passports/need-passport/under-16.html",
    "/content/travel/en/passports/how-apply/fees.html",
    "/content/travel/en/us-visas/tourism-visit/visitor.html",
    "/content/travel/en/us-visas/tourism-visit.html",
    "/content/travel/en/passports/need-passport.html",
    "/content/travel/en/us-visas.html",
    "/content/travel/en/passports/how-apply/photos.html",
    "/content/travel/en/legal/visa-law0/visa-bulletin/2025/visa-bulletin-for-august-2025.html",
    "/content/travel/en/passports/get-fast/passport-agencies.html",
    "/content/travel/en/us-visas/visa-information-resources/photos.html",
    "/content/travel/en/us-visas/visa-information-resources/forms/ds-160-online-nonimmigrant-visa-application/ds-160-faqs.html",
    "/content/travel/en/passports/how-apply/processing-times.html",
    "/content/travel/en/passports/need-passport/status.html",
    "/content/travel/en/passports/how-apply/form-finder.html",
    "/content/travel/en/passports/how-apply.html",
    "/content/travel/en/us-visas/visa-information-resources/forms/ds-160-online-nonimmigrant-visa-application.html",
    "/content/travel/en/passports/how-apply/online-renewal-photo.html",
    "/content/travel/en/us-visas/visa-information-resources/wait-times.html",
    "/en/international-travel/travel-advisories.html",
    "/content/travel/en/passports.html/",
    "/content/travel/en/passports/get-fast.html",
    "/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/step-10-prepare-for-the-interview.html",
    "/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/step-1-submit-a-petition/step-2-begin-nvc-processing.html",
    "/content/travel/en/us-visas/visa-information-resources/global-visa-wait-times.html",
    "/content/travel/en/us-visas/visa-information-resources/iv-wait-times.html",
    "/content/travel/en/passports/need-passport/card.html",
    "/en/international-travel.html",
    "/content/travel/en/us-visas/tourism-visit/visa-waiver-program.html",
    "/content/travel/en/us-visas/visa-information-resources/ask-nvc.html",
    "/en/international-travel/travel-advisories/mexico.html",
    "/content/travel/en/us-visas/immigrate/nvc-timeframes.html",
    "/content/travel/en/us-visas/immigrate/diversity-visa-program-entry/diversity-visa-submit-entry1.html",
    "/content/travel/en/us-visas/immigrate/national-visa-center/nvc-contact-information.html",
    "/content/travel/en/passports/how-apply/citizenship-evidence.html",
    "/content/travel/en/passports/have-passport/lost-stolen.html",
    "/content/travel/en/us-visas/visa-information-resources/list-of-posts.html",
    "/content/travel/en/passports/need-passport/16-17.html",
    "/content/travel/en/passports/have-passport/change-correct.html",
    "/content/travel/en/us-visas/visa-information-resources/all-visa-categories.html",
    "/content/travel/en/contact-us/passports.html"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://travel.state.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}