module.exports = {
  "site": "https://www.stb.gov",
  "urls": [
    "/about-stb/board-members/previous-board-members/william-clyburn-jr/",
    "/about-stb/offices/general-counsel/",
    "/news-communications/latest-news/pr-25-20/",
    "/about-stb/board-members/previous-board-members/daniel-r-elliott-iii/",
    "/foia/",
    "/news-communications/latest-news/pr-21-44/",
    "/resources/need-assistance/rcpa/rail-consumer/",
    "/news-communications/latest-news/pr-25-02/",
    "/reports-data/economic-data/annual-report-financial-data-archive/",
    "/whistleblower-protection/",
    "/about-stb/administrative-issuances/",
    "/about-stb/agency-materials/annual-reports/",
    "/news-communications/latest-news/pr-25-03/",
    "/about-stb/board-members/previous-board-members/w-douglas-buttrey/",
    "/privacy/",
    "/resources/litigation-alternatives/",
    "/reports-data/economic-data/condensed-balance-sheet/",
    "/reports-data/economic-data/cars-loaded-and-terminated/",
    "/resources/need-assistance/hhg-moving/hhg-rate-and-rate-disputes/",
    "/about-stb/board-members/previous-board-members/linda-j-morgan/",
    "/about-stb/offices/office-of-proceedings/",
    "/news-communications/latest-news/pr-19-19/",
    "/news-communications/latest-news/pr-25-06/",
    "/policies-and-notices/",
    "/news-communications/latest-news/archived-press-releases/",
    "/about-stb/agency-materials/small-business-compliance/",
    "/news-communications/latest-news/page/3/",
    "/vulnerability-disclosure-policy/",
    "/about-stb/board-members/previous-board-members/charles-d-nottingham/",
    "/page/2/",
    "/reports-data/economic-data/railroad-revenue-deflator-factors/",
    "/about-stb/board-members/previous-board-members/roger-nober/",
    "/about-stb/offices/office-of-the-managing-director/",
    "/about-stb/agency-materials/annual-employee-surveys/",
    "/about-stb/offices/office-of-passenger-rail/",
    "/news-communications/latest-news/pr-21-20/",
    "/news-communications/latest-news/pr-21-31-2/",
    "/news-communications/latest-news/pr-21-48/",
    "/news-communications/latest-news/pr-22-22/",
    "/fd32760/",
    "/news-communications/latest-news/pr-25-10/",
    "/proceedings-actions/recordations/water-recordations/",
    "/about-stb/board-members/previous-board-members/j-j-simmons-iii/",
    "/blog/rail-service-issues-/bnsf-service-update-05-30-2014/",
    "/blog/rail-service-issues-/csx-service-update-08-06-2025/",
    "/blog/rail-service-issues-/kcs-service-update-11-16-2016/",
    "/foia/foia-request/",
    "/resources/litigation-alternatives/mediation/",
    "/about-stb/board-members/previous-board-members/francis-p-mulvey/",
    "/blog/rail-service-issues-/bnsf-service-update-12-25-2024/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.stb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}