module.exports = {
  "site": "https://www.stb.gov",
  "urls": [
    "/",
    "/proceedings-actions/search-stb-records/",
    "/proceedings-actions/filings/",
    "/proceedings-actions/decisions/",
    "/about-stb/board-members/",
    "/news-communications/latest-news/pr-25-27/",
    "/reports-data/rail-service-data/",
    "/resources/major-railroad-mergers/",
    "/proceedings-actions/dockets-and-service-lists/",
    "/proceedings-actions/",
    "/news-communications/latest-news/pr-23-07/",
    "/reports-data/economic-data/",
    "/news-communications/latest-news/",
    "/resources/railroad-map-depot/",
    "/about-stb/board-members/previous-board-members/robert-e-primus/",
    "/resources/major-railroad-mergers/timeline/",
    "/about-stb/",
    "/about-stb/board-members/previous-board-members/",
    "/reports-data/waybill/",
    "/resources/need-assistance/hhg-moving/hhg-lost-or-damaged-items/",
    "/reports-data/economic-data/employment-data/",
    "/news-communications/latest-news/pr-25-31/",
    "/proceedings-actions/e-filing/",
    "/reports-data/economic-data/annual-report-financial-data/",
    "/reports-data/",
    "/news-communications/latest-news/pr-21-01/",
    "/resources/legal-resources/",
    "/about-stb/offices/",
    "/proceedings-actions/recordations/rail-recordations/",
    "/resources/need-assistance/hhg-moving/",
    "/reports-data/economic-data/freight-commodity-statistics/",
    "/news-communications/latest-news/pr-25-30/",
    "/proceedings-actions/recordations/",
    "/news-communications/non-docketed-public-correspondence/",
    "/news-communications/latest-news/pr-25-29/",
    "/resources/stakeholder-committees/grain-car-council/",
    "/resources/stakeholder-committees/rstac/",
    "/resources/need-assistance/rcpa/",
    "/news-communications/latest-news/pr-24-25/",
    "/news-communications/latest-news/pr-25-28/",
    "/about-stb/jobs/",
    "/proceedings-actions/e-filing/formal-filings/",
    "/reports-data/railroad-cost-recovery-factor/",
    "/resources/need-assistance/how-to-file/",
    "/reports-data/uniform-rail-costing-system/",
    "/proceedings-actions/search-stb-records/tips-for-searching-stb-records/",
    "/news-communications/",
    "/proceedings-actions/environmental-comments/",
    "/resources/",
    "/resources/need-assistance/hhg-moving/hhg-tariff-guidance/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.stb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}