module.exports = {
  "site": "https://www.stb.gov",
  "urls": [
    "/proceedings-actions/e-filing/recordations/",
    "/news-communications/latest-news/pr-21-09/",
    "/proceedings-actions/e-filing/other-filings/",
    "/reports-data/reports-studies/",
    "/resources/stakeholder-committees/prac/",
    "/news-communications/latest-news/pr-25-26/",
    "/news-communications/latest-news/pr-25-24/",
    "/reports-data/reports-studies/depreciation/",
    "/resources/environmental/",
    "/resources/environmental/environmental-overview/",
    "/news-communications/meetings-hearings/",
    "/about-stb/offices/office-of-environmental-analysis/",
    "/about-stb/agency-materials/stb-reauthorization-reports/",
    "/about-stb/board-members/previous-board-members/martin-j-oberman/",
    "/news-communications/latest-news/pr-25-21/",
    "/resources/need-assistance/",
    "/reports-data/demurrage-accessorial-charges/",
    "/reports-data/economic-data/quarterly-wage-ab-data/",
    "/reports-data/economic-data/quarterly-earnings-report/",
    "/news-communications/latest-news/pr-25-23/",
    "/about-stb/offices/opagac/",
    "/resources/stakeholder-committees/retac/",
    "/about-stb/agency-materials/budget-requests/",
    "/news-communications/transcripts-statements/",
    "/resources/environmental/faqs/",
    "/reports-data/economic-data/revenue-expense-income/",
    "/about-stb/agency-materials/",
    "/news-communications/latest-news/pr-21-37/",
    "/about-stb/open-government/",
    "/reports-data/water-carrier-annual-certifications/",
    "/news-communications/agency-task-forces/",
    "/news-communications/latest-news/pr-25-18/",
    "/reports-data/economic-data/commodity-revenue-stratification-reports/",
    "/resources/stakeholder-committees/",
    "/news-communications/testimony-speeches/",
    "/reports-data/economic-data/quarterly-rail-fuel-surcharges/",
    "/news-communications/latest-news/pr-25-22/",
    "/proceedings-actions/e-filing/environmental-comments/",
    "/about-stb/offices/office-of-economics/",
    "/news-communications/latest-news/page/2/",
    "/resources/environmental/third-party-contracting/",
    "/reports-data/rail-infrastructure-projects/",
    "/news-communications/latest-news/pr-25-25/",
    "/reports-data/agricultural-contract-summaries/",
    "/about-stb/offices/equal-employment-opportunity/no-fear-act/",
    "/news-communications/latest-news/pr-24-20/",
    "/resources/litigation-alternatives/arbitration/",
    "/about-stb/agency-materials/strategic-plan-and-pars/",
    "/about-stb/board-members/previous-board-members/deb-miller/",
    "/about-stb/board-members/previous-board-members/ann-begeman/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.stb.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}