module.exports = {
  "site": "https://energyright.com",
  "urls": [
    "/",
    "/residential/rebates/",
    "/funinthesun/",
    "/residential/",
    "/residential/services/home-energy-assessment/",
    "/residential/rebates/smartthermostat/",
    "/business-industry/incentives/",
    "/residential/rebates/mini-split/",
    "/residential/rebates/duct-sealing-hvac-tune-up/",
    "/public-sector/",
    "/residential/rebates/heat-pump/",
    "/commercial/",
    "/industrial-facilities/",
    "/residential/home-uplift/",
    "/business-industry/",
    "/residential/rebates/central-air-conditioner/",
    "/residential/rebates/home-insulation-air-sealing/",
    "/residential/quality-contractor-network/",
    "/residential/financing/",
    "/business-industry/incentives/led-lights/",
    "/ev/",
    "/residential/faq/",
    "/business-industry/incentives/hvac/",
    "/residential/rebates/geothermal-heat-pump/",
    "/about-us/",
    "/business-industry/find-a-contractor/",
    "/business-industry/school-uplift/",
    "/business-industry/incentives/applying-for-incentives/",
    "/mte-sign-up/",
    "/heat-pump-water-heater/",
    "/business-industry/compressed-air-training/",
    "/residential/services/home-energy-evaluation/",
    "/residential/energy-assistance/",
    "/business-industry/find-a-contractor/results/",
    "/residential/education-advice/",
    "/business-industry/school-uplift/resources/",
    "/business-industry/incentives/electric-forklifts/",
    "/retrorecharge/",
    "/business-industry/demand-response/",
    "/2024/07/10/how-to-prevent-an-ac-emergency-and-what-to-do-if-your-ac-breaks/",
    "/business-industry/preferred-partners-network/",
    "/ev/fast-charger-program/",
    "/business-industry/incentives/custom-incentive/",
    "/business-industry/commissioning/",
    "/residential/quality-contractor-network/join/",
    "/business-industry/become-a-member/",
    "/ev/charging/",
    "/business-industry/strategic-energy-management/",
    "/thecurrent/",
    "/business-industry/demand-response/powerflex/",
    "/smart-kit-home/",
    "/residential/workshops/",
    "/2024/12/09/seer2-faq/",
    "/residential/services/"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://energyright.com/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 108,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}