module.exports = {
  "site": "https://www.faa.gov",
  "urls": [
    "/",
    "/newsroom",
    "/uas/commercial_operators/become_a_drone_pilot",
    "/regulations_policies/handbooks_manuals/aviation/phak",
    "/regulations_policies/handbooks_manuals/aviation",
    "/regulations_policies/pilot_records_database",
    "/newsroom/statements/accident_incidents",
    "/uas/getting_started/b4ufly",
    "/regulations_policies/airworthiness_directives",
    "/licenses_certificates/airmen_certification",
    "/air_traffic/flight_info/aeronav/digital_products/dtpp/search/",
    "/uas/recreational_flyers/knowledge_test_updates",
    "/newsroom/statements/general-statements",
    "/pilots/amelocator",
    "/atc-hiring",
    "/hazmat/packsafe/lithium-batteries",
    "/uas/recreational_flyers",
    "/uas",
    "/regulations_policies/handbooks_manuals/aviation/airplane_handbook",
    "/training_testing/testing/acs",
    "/uas/commercial_operators",
    "/regulations_policies/faa_regulations",
    "/air_traffic/flight_info/aeronav/procedures/application/",
    "/airports/runway_safety/resources/quiz/",
    "/training_testing/testing",
    "/jobs",
    "/licenses_certificates/aircraft_certification/aircraft_registry",
    "/pilots/medical_certification",
    "/air_traffic",
    "/regulations_policies/advisory_circulars/index.cfm/go/document.list/",
    "/hazmat/packsafe",
    "/forms/index.cfm/go/document.list/",
    "/",
    "/aircraft",
    "/regulations_policies/handbooks_manuals",
    "/pilots",
    "/air_traffic/flight_info/aeronav/digital_products/aero_guide/",
    "/air_traffic/flight_info/aeronav/digital_products/dafd/search/",
    "/regulations_policies/advisory_circulars/",
    "/air_traffic/flight_info/aeronav/digital_products/dafd/",
    "/regulations_policies",
    "/licenses_certificates/airmen_certification/basic_med",
    "/licenses_certificates/airmen_certification/update_address",
    "/pilots/become",
    "/ame_guide",
    "/air_traffic/flight_info/aeronav/digital_products/vfr/",
    "/air-traffic-controller-qualifications",
    "/uas/getting_started/register_drone",
    "/travelers/fly_children",
    "/pilots/medical_certification/get",
    "/licenses_certificates/airmen_certification/interactive_airmen_inquiry",
    "/hazmat/packsafe/portable-electronic-devices-with-batteries",
    "/mechanics/become",
    "/air_traffic/flight_info/aeronav/digital_products/dtpp/search/",
    "/air_traffic/flight_info/aeronav/digital_products/dtpp/",
    "/jobs/career_fields/aviation_careers",
    "/about/office_org/field_offices/fsdo",
    "/nyc-atc",
    "/regulations_policies/orders_notices/index.cfm/go/document.list/",
    "/hazmat",
    "/uas/getting_started/remote_id",
    "/airports/runway_safety/diagrams/",
    "/av-info/facility-dashboard",
    "/air_traffic/flight_info/aeronav/digital_products/dafd/search/",
    "/aircraft/air_cert",
    "/air_traffic/publications/",
    "/regulations_policies/handbooks_manuals/aircraft",
    "/uas/commercial_operators/uas_facility_maps",
    "/regulations_policies/handbooks_manuals/aviation/aviation_instructors_handbook",
    "/faq/do-minors-need-identification-travel",
    "/air_traffic/flight_info/aeronav/productcatalog/vfrcharts/sectional/",
    "/mechanics/testing/test_results/test_results_replacement",
    "/regulations_policies/advisory_circulars/index.cfm/go/document.information/documentid/99861",
    "/licenses_certificates/airmen_certification/certificate_replacement",
    "/av-info",
    "/hazmat/packsafe/medicinal-toiletry-articles",
    "/uas/getting_started/laanc"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.faa.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 154,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}