module.exports = {
  "site": "https://faa.gov",
  "urls": [
    "/",
    "/newsroom",
    "/uas/commercial_operators/become_a_drone_pilot",
    "/uas/getting_started/b4ufly",
    "/newsroom/statements/accident_incidents",
    "/regulations_policies/airworthiness_directives",
    "/regulations_policies/handbooks_manuals/aviation",
    "/regulations_policies/handbooks_manuals/aviation/phak",
    "/licenses_certificates/airmen_certification",
    "/atc-hiring",
    "/hazmat/packsafe/lithium-batteries",
    "/hazmat/packsafe",
    "/newsroom/statements/general-statements",
    "/air-traffic-controller-qualifications",
    "/uas/recreational_flyers/knowledge_test_updates",
    "/faq/do-minors-need-identification-travel",
    "/pilots/amelocator",
    "/uas/commercial_operators",
    "/uas",
    "/uas/recreational_flyers",
    "/training_testing/testing/acs",
    "/jobs",
    "/regulations_policies/faa_regulations",
    "/training_testing/testing",
    "/regulations_policies/handbooks_manuals/aviation/airplane_handbook",
    "/licenses_certificates/aircraft_certification/aircraft_registry",
    "/jobs/career_fields/aviation_careers",
    "/regulations_policies/pilot_records_database",
    "/airports/runway_safety/resources/quiz/",
    "/licenses_certificates/airmen_certification/update_address",
    "/air_traffic/flight_info/aeronav/digital_products/aero_guide/",
    "/aircraft",
    "/regulations_policies/advisory_circulars/",
    "/travelers/fly_children",
    "/pilots",
    "/airports",
    "/regulations_policies/handbooks_manuals",
    "/licenses_certificates/airmen_certification/basic_med",
    "/pilots/medical_certification",
    "/pilots/become",
    "/hazmat/packsafe/portable-electronic-devices-with-batteries",
    "/regulations_policies",
    "/uas/getting_started/register_drone",
    "/mechanics/become",
    "/licenses_certificates/airmen_certification/interactive_airmen_inquiry",
    "/hazmat",
    "/air_traffic/flight_info/aeronav/digital_products/dafd/",
    "/air_traffic/flight_info/aeronav/digital_products/vfr/"
  ],
  "scanner": {
    "crawler": false,
    "sitemap": false,
    "robotsTxt": false
  },
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-dev-shm-usage"
    ]
  }
}