module.exports = {
  "site": "https://www.irs.gov",
  "urls": [
    "/tin/taxpayer-identification-numbers-tin",
    "/filing",
    "/newsroom/one-big-beautiful-bill-act-of-2025-provisions",
    "/payments/payment-plans-installment-agreements",
    "/payments/types-of-payments-available-to-individuals-through-direct-pay",
    "/es/your-account",
    "/filing/where-to-file-paper-tax-returns-with-or-without-a-payment",
    "/businesses",
    "/individuals/understanding-your-irs-notice-or-letter",
    "/charities-and-nonprofits",
    "/publications/p590b",
    "/tax-professionals/transcript-delivery-system-tds",
    "/forms-pubs/prior-year",
    "/tax-professionals/tax-pro-account",
    "/tax-professionals/taxpayer-identification-number-tin-matching",
    "/tax-professionals/submit-forms-2848-and-8821-online",
    "/credits-deductions/used-clean-vehicle-credit",
    "/written-determinations",
    "/retirement-plans/plan-participant-employee/retirement-topics-ira-contribution-limits",
    "/tax-professionals/e-file-provider-services",
    "/businesses/small-businesses-self-employed/limited-liability-company-llc",
    "/tax-professionals/standard-mileage-rates",
    "/forms-pubs/about-form-ss-4",
    "/forms-pubs/about-form-w-2",
    "/filing/individuals/how-to-file",
    "/credits-and-deductions-for-individuals",
    "/forms-pubs/about-form-1040-es",
    "/credits-deductions/energy-efficient-home-improvement-credit",
    "/individuals/check-if-you-need-to-file-a-tax-return",
    "/faqs/irs-procedures/address-changes",
    "/retirement-plans/retirement-plan-and-ira-required-minimum-distributions-faqs",
    "/retirement-plans/plan-participant-employee/retirement-topics-required-minimum-distributions-rmds",
    "/payments/offer-in-compromise",
    "/applicable-federal-rates",
    "/individuals/transcript-types-for-individuals-and-ways-to-order-them",
    "/newsroom/401k-limit-increases-to-23500-for-2025-ira-limit-remains-7000",
    "/charities-non-profits/annual-electronic-filing-requirement-for-small-exempt-organizations-form-990-n-e-postcard",
    "/newsroom/check-the-status-of-a-refund-in-just-a-few-clicks-using-the-wheres-my-refund-tool",
    "/es/wheres-my-refund",
    "/newsroom/recovery-rebate-credit",
    "/es/payments",
    "/filing/where-to-file-addresses-for-taxpayers-and-tax-professionals-filing-form-1040",
    "/businesses/small-businesses-self-employed/frequently-asked-questions-on-gift-taxes",
    "/forms-pubs/about-form-4506-t",
    "/filing/get-an-extension-to-file-your-tax-return",
    "/businesses/small-businesses-self-employed/self-employed-individuals-tax-center",
    "/es",
    "/identity-theft-fraud-scams/retrieve-your-ip-pin",
    "/individuals/understanding-your-cp523-notice",
    "/tin/itin/individual-taxpayer-identification-number-itin"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.irs.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}