module.exports = {
  "site": "https://www.irs.gov",
  "urls": [
    "/",
    "/your-account",
    "/payments",
    "/payments/online-account-for-individuals",
    "/site-index-search",
    "/payments/direct-pay-with-bank-account",
    "/wheres-my-refund",
    "/payments/pay-personal-taxes-from-your-bank-account",
    "/individuals/get-transcript",
    "/businesses/small-businesses-self-employed/get-an-employer-identification-number",
    "/payments/pay-your-taxes-by-debit-or-credit-card",
    "/payments/online-payment-agreement-application",
    "/individuals/tax-withholding-estimator",
    "/filing/wheres-my-amended-return",
    "/forms-instructions",
    "/businesses/employer-identification-number",
    "/refunds",
    "/forms-pubs-search",
    "/filing/federal-income-tax-rates-and-brackets",
    "/help/let-us-help-you",
    "/forms-pubs/about-form-w-9",
    "/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2025",
    "/businesses/small-businesses-self-employed/estimated-taxes",
    "/payments/direct-pay-help",
    "/e-services",
    "/coronavirus/economic-impact-payments",
    "/filing/file-an-amended-return",
    "/payments/online-account-for-individuals-frequently-asked-questions",
    "/businesses/business-tax-account",
    "/forms-pubs/about-form-w-8-imy",
    "/charities-non-profits/tax-exempt-organization-search",
    "/identity-theft-fraud-scams/get-an-identity-protection-pin",
    "/charities-non-profits/search-for-tax-exempt-organizations",
    "/help/tools",
    "/tax-professionals",
    "/help/contact-your-local-irs-office",
    "/prior-year-forms-and-instructions",
    "/forms-instructions-and-publications",
    "/forms-pubs-prior-search",
    "/individual-tax-filing",
    "/newsroom/one-big-beautiful-bill-act-tax-deductions-for-working-americans-and-seniors",
    "/identity-theft-fraud-scams/verify-your-return",
    "/newsroom/irs-statement-on-delay-in-processing-some-electronic-payments",
    "/help/processing-status-for-tax-forms",
    "/payments/pay-business-taxes-from-your-bank-account",
    "/forms-pubs/about-form-w-4",
    "/filing/irs-free-file-do-your-taxes-for-free",
    "/forms-pubs/about-form-1040",
    "/payments/eftps-the-electronic-federal-tax-payment-system",
    "/credits-deductions/credits-for-new-clean-vehicles-purchased-in-2023-or-after"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.irs.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}