module.exports = {
  "site": "https://udall.gov",
  "urls": [
    "/ourprograms/fellowship/whoshouldapply.aspx",
    "/ourprograms/scholarship/alumninetwork.aspx",
    "/ourprograms/parksinfocus/whatispif/ourhistory.aspx",
    "/aboutus/digitalaccessibilitystatement.aspx",
    "/ourprograms/institute/questionsanswers.aspx",
    "/ourprograms/institute/serviceareas.aspx",
    "/ourprograms/parksinfocus/whatispif.aspx",
    "/ourprograms/internship/summerinwashingtondc.aspx",
    "/aboutus/udallarchives.aspx",
    "/ourprograms/scholarship/informationforreferences.aspx",
    "/ourprograms/udallcenter/udallcenter.aspx",
    "/ourprograms/institute/findmediatorfacilitator.aspx",
    "/ourprograms/internship/faqs.aspx",
    "/ourprograms/fellowship/apply.aspx",
    "/ourprograms/internship/apply.aspx",
    "/ourprograms/institute/serviceareaenergy.aspx",
    "/ourprograms/scholarship/tribalpolicy.aspx",
    "/default.aspx",
    "/aboutus/quarterlystories/quarterlystories.aspx",
    "/ourprograms/institute/webinarsonlineresources.aspx",
    "/ourprograms/nativeinstitute/nativeinstitute.aspx",
    "/aboutus/missionandhistory.aspx",
    "/aboutus/budgetandperformance.aspx",
    "/ourprograms/fellowship/application.aspx",
    "/ourprograms/scholarship/spotlights/crystalfilep.aspx",
    "/aboutus/foia.aspx",
    "/ourprograms/internship/adviceandguidance.aspx",
    "/ourprograms/parksinfocus/pifprograms.aspx",
    "/ourprograms/internship/howtoapply.aspx",
    "/ourprograms/fellowship/importantdates.aspx",
    "/ourprograms/scholarship/udallpapers.aspx",
    "/ourprograms/internship/importantdates.aspx",
    "/ourprograms/parksinfocus/pifprograms/grandcanyon.aspx",
    "/ourprograms/parksinfocus/getinvolved/volunteer.aspx",
    "/aboutus/eeo.aspx",
    "/ourprograms/fellowship/howtoapply.aspx",
    "/ourprograms/scholarship/honorablementions.aspx",
    "/ourprograms/institute/ecrreport.aspx",
    "/ourprograms/internship/application.aspx",
    "/ourprograms/scholarship/spotlights/katharinewilkinson.aspx",
    "/ourprograms/fellowship/informationforreferences.aspx",
    "/ourprograms/scholarship/spotlights/wietekeholthuijzen.aspx",
    "/aboutus/guidelinesforpubliccomments.aspx",
    "/robots.txt",
    "/ourprograms/internship/alumninetwork.aspx",
    "/ourprograms/internship/informationforreferences.aspx",
    "/ourprograms/parksinfocus/pifprograms/yosemite.aspx",
    "/privacy",
    "/ourprograms/parksinfocus/pifprograms/tucson.aspx",
    "/ourprograms/institute/customizedtraining.aspx"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://udall.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}