module.exports = {
  "site": "https://udall.gov",
  "urls": [
    "/ourprograms/scholarship/spotlights/jenniferpeyservanhooreweghe.aspx",
    "/basics/glossary.aspx",
    "/newsannouncements/honoringstewart.aspx",
    "/ourprograms/parksinfocus/whatispif/ourimpact.aspx",
    "/ourprograms/institute/projectwebsiteswehost.aspx",
    "/ourprograms/institute/serviceareatransportation.aspx",
    "/ourprograms/parksinfocus/getinvolved.aspx",
    "/ourprograms/parksinfocus/pifprograms/flagstaff.aspx",
    "/aboutus/quarterlystories/changeslives.aspx",
    "/ourprograms/institute/servicearealanduse.aspx",
    "/ourprograms/parksinfocus/partnerledinitiatives/klamath.aspx",
    "/aboutus/nofearact.aspx",
    "/vulnerability-disclosure-policy",
    "/ourprograms/institute/serviceareamarine.aspx",
    "/ourprograms/institute/areaofexpertiseoceans.aspx",
    "/aboutus/ipv6policies.aspx",
    "/sitemap.xml",
    "/ourprograms/institute/serviceareanativeamerican.aspx",
    "/ourprograms/internship/udallpapers.aspx",
    "/ourprograms/parksinfocus/partners.aspx",
    "/pdf/udallfoundationgapinappropriationsplanningdocument2014.pdf",
    "/ourprograms/parksinfocus/partnerledinitiatives/newaygo.aspx",
    "/aboutus/foiaboardminutes.aspx",
    "/ourprograms/parksinfocus/partnerledinitiatives.aspx",
    "/aboutus/quarterlystories/kristie.aspx",
    "/ourprograms/institute/choosingecrprofessional.aspx",
    "/ourprograms/institute/ecrmemo.aspx",
    "/aboutus/quarterlystories/partners.aspx",
    "/ourprograms/mkuscholarship/mkuscholarship.aspx",
    "/ourprograms/institute/nepa.aspx",
    "/crossdomain.xml",
    "/aboutus/quarterlystories/udallarchives.aspx",
    "/aboutus/foiaotherboardmaterials.aspx",
    "/ourprograms/institute/principles.aspx",
    "/ourprograms/institute/roster.aspx",
    "/announcementsevents/conference/ecr2010/home.aspx",
    "/ourprograms/institute/ecr.gov",
    "/ourprograms/institute/ecrforums.aspx",
    "/ourprograms/mkuscholarship/honorablementions.aspx",
    "/aboutus/quarterlystories/drew.aspx",
    "/ourprograms/internship/lawstudents.aspx",
    "/aboutus/quarterlystories/charlotte.aspx",
    "/ourprograms/institute/training/paybycoupon.aspxemy05gealocation.href",
    "/announcementsevents/nationalecrconference.aspx",
    "/images/arizona100birthday.jpg",
    "/images/mschaeferprphoto.jpg",
    "/ourprograms/institute/training.aspxemy05gealocation.href",
    "/news/mailto",
    "/aboutus/foiaexecutivesessionmaterial.aspx",
    "/ourprograms/institute/policies.aspx"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://udall.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}