module.exports = {
  "site": "https://udall.gov",
  "urls": [
    "/data",
    "/",
    "/ourprograms/scholarship/scholarship.aspx",
    "/ourprograms/scholarship/meetscholars.aspx",
    "/aboutus/aboutus.aspx",
    "/news/newsandevents.aspx",
    "/aboutus/meetourstaff.aspx",
    "/ourprograms/institute/projectcasesummary.aspx",
    "/ourprograms/scholarship/findfacrep.aspx",
    "/news/newsarchive.aspx",
    "/ourprograms/institute/institute.aspx",
    "/ourprograms/scholarship/apply.aspx",
    "/ourprograms/institute/projectcasesummaries.aspx",
    "/AboutUs/MeetOurStaff.aspx",
    "/ourprograms/internship/internship.aspx",
    "/ourprograms/scholarship/whoshouldapply.aspx",
    "/ourprograms/internship/meetinterns.aspx",
    "/ourprograms/parksinfocus/parksinfocus.aspx",
    "/ourprograms/fellowship/meetfellows.aspx",
    "/ourprograms/scholarship/aboutscholarship.aspx",
    "/ourprograms/ourprograms.aspx",
    "/aboutus/requiredstatements.aspx",
    "/OurPrograms/Institute/Training.aspx",
    "/OurPrograms/ParksInFocus/StaffAndVolunteers.aspx",
    "/ourprograms/scholarship/howtoapply.aspx",
    "/section508reporting.aspx",
    "/ourprograms/parksinfocus/staffandvolunteers.aspx",
    "/feed/",
    "/ourprograms/scholarship/importantdates.aspx",
    "/ourprograms/fellowship/fellowship.aspx",
    "/ourprograms/scholarship/environment.aspx",
    "/aboutus/meetourboard.aspx",
    "/supportus/supportus.aspx",
    "/ourprograms/institute/opentrainings.aspx",
    "/css/bootstrap5.3.3.min.css",
    "/ourprograms/scholarship/faqs.aspx",
    "/aboutus/search.aspx",
    "/aboutus/contactus.aspx",
    "/ourprograms/institute/leadership.aspx",
    "/ourprograms/institute/trainingcertificate.aspx",
    "/ourprograms/scholarship/orientation.aspx",
    "/search.aspx",
    "/ourprograms/institute/training.aspx",
    "/ourprograms/scholarship/nativehealthcare.aspx",
    "/ourprograms/internship/whoshouldapply.aspx",
    "/ourprograms/internship/aboutinternship.aspx",
    "/ourprograms/scholarship/adviceguidance.aspx",
    "/ourprograms/parksinfocus/supportpif.aspx",
    "/ourprograms/scholarship/facultyreps.aspx",
    "/aboutus/infobystate.aspx"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://udall.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}