module.exports = {
  "site": "https://www.uscourts.gov",
  "urls": [
    "/about-federal-courts/educational-resources/about-educational-outreach/activity-resources/what-does-fourth-amendment-mean",
    "/forms-rules/forms/application-have-chapter-7-filing-fee-waived-0",
    "/about-federal-courts/educational-resources/about-educational-outreach/activity-resources/supreme-court-procedures",
    "/forms-rules/forms/schedule-a-b-property-individuals",
    "/court-programs/fees/bankruptcy-court-miscellaneous-fee-schedule",
    "/about-federal-courts",
    "/about-federal-courts/educational-resources/about-educational-outreach/activity-resources/about",
    "/court-programs/bankruptcy/bankruptcy-basics/discharge-bankruptcy-bankruptcy-basics",
    "/forms-rules/forms/summons-a-civil-action",
    "/about-federal-courts/types-federal-judges",
    "/court-programs/bankruptcy/unclaimed-funds-bankruptcy",
    "/court-programs/jury-service/types-juries",
    "/contact-us",
    "/court-programs/bankruptcy/credit-counseling-and-debtor-education-courses",
    "/administration-policies/judiciary-policies/ethics-policies/code-conduct-united-states-judges",
    "/forms-rules/forms/a-summary-your-assets-and-liabilities-and-certain-statistical-information-individuals",
    "/careers/who-works-judiciary/us-probation-pretrial-services-careers",
    "/data-table-report-names/bankruptcy-filings",
    "/forms-rules/proposed-amendments-published-public-comment",
    "/about-federal-courts/types-cases/criminal-cases",
    "/forms-rules/forms/schedule-c-property-you-claim-exempt-individuals",
    "/forms-rules/current-rules-practice-procedure/federal-rules-appellate-procedure",
    "/privacy-security-policy",
    "/forms-rules/forms/statement-financial-affairs-individuals-filing-bankruptcy",
    "/forms-rules/forms/schedule-i-your-income-individuals",
    "/forms-rules/current-rules-practice-procedure/federal-rules-evidence",
    "/forms-rules/forms/schedule-j-your-expenses-individuals",
    "/forms-rules/forms/chapter-7-statement-your-current-monthly-income-0",
    "/about-federal-courts/court-role-and-structure/about-us-district-courts",
    "/educational-resources/educational-activities/overview-rule-law",
    "/forms-rules/forms/declaration-about-individual-debtors-schedules",
    "/about-federal-courts/educational-resources/educational-activities/sixth-amendment-activities/gideon-v-wainwright/facts-and-case-summary-gideon-v-wainwright",
    "/forms-rules",
    "/forms-rules/forms/your-statement-about-your-social-security-numbers",
    "/forms-rules/forms/schedule-d-creditors-who-hold-claims-secured-property-individuals",
    "/forms-rules/forms/complaint-a-civil-case",
    "/data-news/reports/statistical-reports/bankruptcy-filings-statistics",
    "/about-federal-courts/educational-resources/educational-activities/first-amendment-activities/us-v-alvarez/separation-powers-action-us-v-alvarez",
    "/judges-judgeships/judicial-vacancies",
    "/forms-rules/forms/application-judicial-branch-federal-employment",
    "/statistics-reports/caseload-statistics-data-tables",
    "/about-federal-courts/about-federal-judges/judicial-compensation",
    "/court-programs/jury-service/juror-pay",
    "/forms-rules/forms/subpoena-produce-documents-information-or-objects-or-permit-inspection-premises-a-civil-action",
    "/data-news/judiciary-news/2015/10/02/video-judges-students-welcome-new-citizens-ceremonies-across-us",
    "/forms-rules/forms/application-individuals-pay-filing-fee-installments-0",
    "/data-news/judiciary-news",
    "/data-news/judiciary-news/2025/08/28/new-supreme-court-fellows-begin-term",
    "/court-programs/bankruptcy/bankruptcy-basics/process-bankruptcy-basics",
    "/glossary-legal-terms/habeas-corpus"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.uscourts.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}