module.exports = {
  "site": "https://www.uscourts.gov",
  "urls": [
    "/forms-rules/forms/statement-intention-individuals-filing-under-chapter-7",
    "/forms-rules/current-rules-practice-procedure/federal-rules-bankruptcy-procedure",
    "/court-programs/fees",
    "/forms-rules/forms/criminal-forms",
    "/court-records/court-record-schedules",
    "/forms-rules/forms/schedule-g-executory-contracts-and-unexpired-leases-individuals",
    "/about-federal-courts/educational-resources/educational-activities/brown-v-board-education-re-enactment/history-brown-v-board-education-re-enactment",
    "/about-federal-courts/defender-services",
    "/data-news/judiciary-news/2022/06/23/new-modern-safer-courthouse-opens-san-antonio",
    "/about-federal-courts/educational-resources/educational-activities/first-amendment-activities/hazelwood-v-kuhlmeier/facts-and-case-summary-hazelwood-v-kuhlmeier",
    "/about-federal-courts/types-cases/appeals",
    "/forms-rules/forms/other-forms",
    "/forms-rules/forms/schedule-h-your-codebtors-individuals",
    "/forms-rules/forms/appearance-counsel",
    "/court-programs/federal-court-interpreters",
    "/forms-rules/pending-rules-and-forms-amendments",
    "/rss-feeds",
    "/careers/compensation",
    "/careers/compensation/court-personnel-system-pay-rates-non-law-enforcement-officer",
    "/about-federal-courts/educational-resources/educational-activities/fourth-amendment-activities/new-jersey-v-tlo/facts-and-case-summary-new-jersey-v-tlo",
    "/forms-rules/forms/waiver-service-summons",
    "/about-federal-courts/educational-resources",
    "/careers/benefits",
    "/about-federal-courts/about-federal-judges",
    "/forms-rules/forms/attorney-forms",
    "/forms-rules/forms/proof-claim-attachment-a-0",
    "/about-federal-courts/educational-resources/educational-activities/first-amendment-activities/engel-v-vitale/facts-and-case-summary-engel-v-vitale",
    "/court-records/electronic-public-access-public-user-group",
    "/careers/who-works-judiciary",
    "/data-news/judiciary-news/2023/04/17/modern-courthouse-pennsylvania-opens-public",
    "/administration-policies/judiciary-policies/bankruptcy-case-policies",
    "/court-programs/bankruptcy/trustees-and-administrators",
    "/data-news/judiciary-news/2025/07/31/bankruptcy-filings-rise-115-percent-over-previous-year",
    "/forms-rules/forms/civil-pro-se-forms",
    "/topics/administrative-office-us-courts",
    "/forms-rules/current-rules-practice-procedure/federal-rules-criminal-procedure",
    "/about-federal-courts/educational-resources/educational-activities/first-amendment-activities",
    "/court-programs/federal-court-interpreters/federal-court-interpreter-certification-examination",
    "/about-federal-courts/probation-and-pretrial-services/officers-and-officer-assistants",
    "/court-records/access-court-proceedings/remote-public-access-proceedings",
    "/about-federal-courts/about-federal-judges/types-federal-judges/faqs-federal-judges",
    "/data-news/reports/statistical-reports/bankruptcy-filing-statistics/bankruptcy-statistics-data-visualizations",
    "/data-news/judiciary-news/2025/05/01/bankruptcies-rise-131-percent-over-previous-year",
    "/data-news/judiciary-news/2025/07/15/funding-crisis-leaves-defense-lawyers-working-without-pay",
    "/forms-rules/forms/initial-statement-about-eviction-judgment-against-you-individuals",
    "/about-federal-courts/educational-resources/educational-activities/14th-amendment-and-evolution-title-ix",
    "/court-records/access-court-proceedings/remote-public-access-proceedings/cameras-courts/case-video-archive",
    "/court-programs/federal-court-reporting-program",
    "/about-federal-courts/educational-resources/educational-activities/first-amendment-activities/morse-v-frederick/facts-and-case-summary-morse-v-frederick",
    "/forms-rules/forms/chapter-13-plan"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.uscourts.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}