module.exports = {
  "site": "https://www.uscourts.gov",
  "urls": [
    "/court-records/find-a-case-pacer",
    "/careers/search-judiciary-jobs",
    "/federal-court-finder/find",
    "/",
    "/forms-rules/forms/bankruptcy-forms",
    "/forms-rules/forms",
    "/glossary",
    "/court-programs/bankruptcy/bankruptcy-basics/chapter-7-bankruptcy-basics",
    "/about-federal-courts/educational-resources/about-educational-outreach/activity-resources/us-constitution-preamble",
    "/about-federal-courts/educational-resources/educational-activities/first-amendment-activities/texas-v-johnson/facts-and-case-summary-texas-v-johnson",
    "/forms-rules/current-rules-practice-procedure/federal-rules-civil-procedure",
    "/court-records",
    "/about-federal-courts/court-role-and-structure",
    "/court-programs/bankruptcy/bankruptcy-basics/chapter-13-bankruptcy-basics",
    "/court-programs/bankruptcy",
    "/forms-rules/forms/voluntary-petition-individuals-filing-bankruptcy",
    "/court-programs/bankruptcy/filing-without-attorney",
    "/court-records/electronic-filing-cm-ecf",
    "/about-federal-courts/court-role-and-structure/court-website-links",
    "/court-programs/jury-service/juror-qualifications-exemptions-and-excuses",
    "/data-news/judicial-vacancies/current-judicial-vacancies",
    "/careers",
    "/court-programs/bankruptcy/bankruptcy-basics/chapter-11-bankruptcy-basics",
    "/forms-rules/forms/proof-claim-0",
    "/court-programs/bankruptcy/bankruptcy-case-records-credit-reporting",
    "/court-programs/bankruptcy/bankruptcy-basics",
    "/federal-court-finder/find",
    "/court-records/access-court-proceedings",
    "/about-federal-courts/educational-resources/supreme-court-landmarks",
    "/forms-rules/forms/civil-forms",
    "/data-news/judiciary-news/2025/08/07/cybersecurity-measures-strengthened-light-attacks-judiciarys-case-management-system",
    "/court-programs/jury-service",
    "/court-programs/jury-service/summoned-federal-jury-service",
    "/about-federal-courts/court-role-and-structure/comparing-federal-state-courts",
    "/data-news/judicial-vacancies/future-judicial-vacancies",
    "/about-federal-courts/probation-and-pretrial-services",
    "/about-federal-courts/types-cases/civil-cases",
    "/about-federal-courts/court-role-and-structure/about-us-courts-appeals",
    "/forms-rules/current-rules-practice-procedure",
    "/careers/compensation/judiciary-salary-plan-pay-rates",
    "/forms-rules/forms/civil-cover-sheet",
    "/about-federal-courts/educational-resources/educational-activities/fifth-amendment-activities/miranda-v-arizona/facts-and-case-summary-miranda-v-arizona",
    "/about-federal-courts/educational-resources/about-educational-outreach/activity-resources/first-amendment-and-religion",
    "/about-federal-courts/educational-resources/educational-activities/first-amendment-activities/tinker-v-des-moines/facts-and-case-summary-tinker-v-des-moines",
    "/about-federal-courts/educational-resources/about-educational-outreach/activity-resources/what-does-free-speech-mean",
    "/court-programs/jury-service/juror-selection-process",
    "/forms-rules/forms/chapter-7-means-test-calculation-0",
    "/about-federal-courts/types-cases",
    "/forms-rules/forms/schedule-e-f-creditors-who-have-unsecured-claims-individuals",
    "/court-programs/jury-service/juror-scams"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.uscourts.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}