module.exports = {
  "site": "https://www.va.gov",
  "urls": [
    "/",
    "/my-va/",
    "/auth/login/callback",
    "/",
    "/my-health/",
    "/my-health/medical-records/labs-and-tests",
    "/sign-in/",
    "/my-health/medications",
    "/my-health/medical-records/summaries-and-notes",
    "/my-health",
    "/track-claims/your-claims",
    "/my-health/secure-messages/inbox",
    "/my-health/secure-messages/inbox/",
    "/my-health/medical-records/",
    "/search/",
    "/my-health/medications",
    "/my-health/appointments",
    "/my-health/secure-messages/inbox/",
    "/sign-in/",
    "/find-locations/",
    "/my-health/medical-records",
    "/track-claims/your-claims/",
    "/track-claims/",
    "/disability/view-disability-rating/rating",
    "/claim-or-appeal-status/",
    "/logout/",
    "/health-care/manage-health/",
    "/profile",
    "/reach/",
    "/track-claims/your-claim-letters",
    "/va-payment-history/payments/",
    "/my-health/appointments",
    "/find-locations/",
    "/my-health/secure-messages/new-message/",
    "/my-health/appointments/",
    "/my-health/medical-records/conditions",
    "/my-health/appointments/",
    "/my-health/medications/refill",
    "/search/",
    "/my-health/medical-records/",
    "/health-care/file-travel-pay-reimbursement/",
    "/disability/compensation-rates/veteran-rates/",
    "/education/gi-bill-comparison-tool/schools-and-employers/",
    "/my-health/medical-records/download",
    "/health-care/appointment-check-in/",
    "/track-claims/your-claim-letters",
    "/disability/",
    "/my-health/travel-pay/claims",
    "/my-health/medications/refill",
    "/my-health/appointments/past"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.va.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}