module.exports = {
  "site": "https://www.va.gov",
  "urls": [
    "/find-forms/",
    "/health-care/",
    "/profile/direct-deposit",
    "/my-health/appointments/schedule/type-of-care",
    "/disability/file-disability-claim-form-21-526ez/",
    "/track-claims/your-claims/",
    "/profile",
    "/find-locations",
    "/my-va/welcome-va-setup/contact-information",
    "/resources/the-pact-act-and-your-va-benefits/",
    "/records/download-va-letters/letters/letter-list",
    "/profile/contact-information",
    "/family-and-caregiver-benefits/education-and-careers/dependents-education-assistance/rates/",
    "/health-care/appointment-pre-check-in/complete",
    "/contact-us/ask-va",
    "/track-claims/your-claims",
    "/profile/veteran-status-card",
    "/education/check-remaining-post-9-11-gi-bill-benefits/status",
    "/family-and-caregiver-benefits/education-and-careers/dependents-education-assistance/",
    "/manage-va-debt/summary/copay-balances",
    "/education/gi-bill-comparison-tool/schools-and-employers",
    "/get-help-from-accredited-representative/find-rep/",
    "/my-health/medical-records/labs-and-tests",
    "/my-health/appointments/schedule/type-of-care",
    "/education/download-letters/",
    "/my-health/secure-messages/inbox",
    "/reach/lethal-means/",
    "/profile/military-information",
    "/reach/lethal-means/face-your-dragon/",
    "/health-care/appointment-check-in/travel-mileage",
    "/health-care/appointment-check-in/travel-review",
    "/resources/how-to-renew-a-va-prescription/",
    "/life-insurance/options-eligibility/valife/",
    "/health-care/appointment-check-in/travel-address",
    "/health-care/appointment-pre-check-in/next-of-kin",
    "/family-and-caregiver-benefits/",
    "/health-care/appointment-check-in/travel-vehicle",
    "/disability/file-disability-claim-form-21-526ez/introduction",
    "/education/eligibility/",
    "/health-care/appointment-pre-check-in/emergency-contact",
    "/manage-dependents/view",
    "/resources/creating-an-account-for-vagov/",
    "/records/download-va-letters/letters/letter-page",
    "/health-care/appointment-pre-check-in/contact-information",
    "/manage-va-debt/summary/debt-balances",
    "/health-care/appointment-check-in/error",
    "/resources/getting-started-with-va/",
    "/family-and-caregiver-benefits/education-and-careers/apply-for-dea-fry-form-22-5490/introduction",
    "/profile/direct-deposit",
    "/health-care/apply-for-health-care-form-10-10ez/introduction"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.va.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}