module.exports = {
  "site": "https://www.va.gov",
  "urls": [
    "/health-care/appointment-check-in/verify",
    "/va-payment-history/",
    "/my-health/secure-messages/sent/",
    "/education/verify-school-enrollment/",
    "/health-care/manage-appointments/",
    "/health-care/manage-health/",
    "/records/download-va-letters/letters",
    "/records/download-va-letters/",
    "/disability/view-disability-rating/",
    "/va-payment-history/payments/",
    "/health-care/appointment-check-in/appointments",
    "/education/",
    "/health-care/appointment-pre-check-in/",
    "/contact-us/",
    "/health-care/appointment-pre-check-in/verify",
    "/health-care/manage-prescriptions-medications/",
    "/resources/signing-in-to-vagov/",
    "/health-care/appointment-check-in/arrived",
    "/education/how-to-apply/",
    "/contact-us/ask-va/introduction",
    "/my-health/medical-records/download/date-range",
    "/my-health/appointments/past",
    "/contact-us/ask-va/introduction",
    "/terms-of-use",
    "/my-health/medications/refill/",
    "/my-health/medical-records/download/record-type",
    "/education/check-remaining-post-9-11-gi-bill-benefits/",
    "/my-health/medical-records/download/file-type",
    "/disability/how-to-file-claim/",
    "/find-forms/",
    "/health-care/appointment-check-in/travel-pay",
    "/disability/file-disability-claim-form-21-526ez/introduction",
    "/claim-or-appeal-status/",
    "/disability/about-disability-ratings/",
    "/my-health/secure-messages/new-message/",
    "/records/get-military-service-records/",
    "/health-care/appointment-check-in/emergency-contact",
    "/sign-in-changes-reminder",
    "/disability/file-disability-claim-form-21-526ez/start",
    "/health-care/send-receive-messages/",
    "/health-care/appointment-check-in/contact-information",
    "/health-care/review-medical-records/",
    "/family-and-caregiver-benefits/health-and-disability/champva/",
    "/health-care/appointment-pre-check-in/appointments",
    "/records/download-va-letters/letters/confirm-address",
    "/education/check-remaining-post-9-11-gi-bill-benefits/status/",
    "/my-health/appointments/schedule/location",
    "/education/gi-bill-comparison-tool/",
    "/profile/personal-information",
    "/health-care/appointment-check-in/next-of-kin"
  ],
  "puppeteerOptions": {
    "args": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless=new"
    ],
    "concurrency": 1
  },
  "puppeteerPageUserAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "userAgent": "Mozilla/5.0 (compatible; FederalWebsiteScanner/1.0; +https://github.com/your-org/federal-website-scanner)",
  "disableThrottling": true,
  "disableDeviceEmulation": true,
  "lighthouseOptions": {
    "disableStorageReset": true,
    "disableLantern": true,
    "throttlingMethod": "provided",
    "onlyCategories": [
      "accessibility",
      "seo",
      "best-practices"
    ]
  },
  "scanner": {
    "sitemap": "https://www.va.gov/sitemap.xml",
    "crawler": false,
    "robotsTxt": false,
    "maxRoutes": 100,
    "throttle": false,
    "skipJavascript": true,
    "samples": 1,
    "pageTimeout": 90000,
    "device": "desktop",
    "exclude": [
      "/*.pdf",
      "/*.asp",
      "/*.aspx",
      "/sample-pfs-searches",
      "/security-guidelines-office-location",
      "/status-indicators",
      "/blog",
      "/my-health/*",
      "/my-va/*",
      "/auth/*",
      "/profile/*",
      "/logout",
      "**/callback*",
      "**/login*",
      "**/signin*"
    ]
  },
  "ci": {
    "skipMissing": true,
    "skipRoutesWithoutResults": true
  },
  "chrome": {
    "useSystem": true
  },
  "debug": false
}